name: Build ARM64 Linux
description: 'Build ARM64 Version of the Linux app'

inputs:
  release_build:
    description: 'If true, run the release build script'
    required: false
    default: 'false'

runs:
    using: "composite"
    steps:
      - name: Clean the log directory
        run : rm -rf /tmp/kDrive-logdir/*
        shell: bash

      - name: Fail if not release_build
        if: ${{ inputs.release_build != 'true' }}
        run: |
          echo "This action is only for release builds. Set the input 'release_build' to 'true'."
          exit 1
        shell: bash

      - name: Run the build script
        id: build
        run: |
          /usr/bin/env bash ${{ github.workspace }}/infomaniak-build-tools/linux/build-release-arm64-via-podman.sh --src-dir ${{ github.workspace }}
        shell: bash

      - name: Upload app AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-artifacts-appimage-arm64
          path: ${{ github.workspace }}/build-linux-arm64/install/kDrive-*-arm64.AppImage # kDrive-<full_version>-arm64.AppImage
          retention-days: 1
        if: steps.build.outcome == 'success'


      - name: Download sentry-cli for macOS (ARM64)
        if: steps.build.outcome == 'success'
        run: |
          curl -L https://github.com/getsentry/sentry-cli/releases/download/2.50.2/sentry-cli-Darwin-arm64 -o sentry-cli \
          && chmod +x ./sentry-cli
        shell: bash

      - name: Create sentry server artifacts
        if: steps.build.outcome == 'success'
        run: |
          DBG_FILE="${{ github.workspace }}/build-linux-arm64/kDrive.dbg"
          ./sentry-cli debug-files bundle-sources "$DBG_FILE"
          mkdir "${{ github.workspace }}/build-linux-arm64/sentry-server-artifacts"
          mv "${{ github.workspace }}/build-linux-arm64/kDrive.src.zip" "${{ github.workspace }}/build-linux-arm64/sentry-server-artifacts"
          mv "$DBG_FILE" "${{ github.workspace }}/build-linux-arm64/sentry-server-artifacts"
        shell: bash

      - name: Create sentry client artifacts
        if: steps.build.outcome == 'success'
        run: |
          DBG_FILE="${{ github.workspace }}/build-linux-arm64/kDrive_client.dbg"
          ./sentry-cli debug-files bundle-sources "$DBG_FILE"
          mkdir "${{ github.workspace }}/build-linux-arm64/sentry-client-artifacts"
          mv "${{ github.workspace }}/build-linux-arm64/kDrive_client.src.zip" "${{ github.workspace }}/build-linux-arm64/sentry-client-artifacts"
          mv "$DBG_FILE" "${{ github.workspace }}/build-linux-arm64/sentry-client-artifacts"
        shell: bash

      - name: Upload sentry server artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-artifacts-server-debug-arm64
          path: ${{ github.workspace }}/build-linux-arm64/sentry-server-artifacts
          retention-days: 1
          compression-level: 0

      - name: Upload sentry client artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-artifacts-client-debug-arm64
          path: ${{ github.workspace }}/build-linux-arm64/sentry-client-artifacts
          retention-days: 1
          compression-level: 0

      - name: Clean-up generated code
        run : rm -rf build-linux
        shell: bash
