name: Build ARM Linux
description: 'Build ARM Version of the Linux app'

inputs:
  release_build:
    description: 'If true, run the release build script'
    required: false
    default: 'false'

runs:
    using: "composite"
    steps:
      - name: Clean the log directory
        run : rm -rf /tmp/kDrive-logdir/*
        shell: bash

      - name: Run the build script
        id: build
        run: |
          SCRIPT="./infomaniak-build-tools/linux/build-release-appimage-arm64.sh"
        shell: bash

      - name: Clean-up generated code
        run : rm -rf build-linux
        shell: bash
