name: Build ARM Linux
description: 'Build ARM Version of the Linux app'

inputs:
  release_build:
    description: 'If true, run the release build script'
    required: false
    default: 'false'

runs:
    using: "composite"
    steps:
      - name: Clean the log directory
        run : rm -rf /tmp/kDrive-logdir/*
        shell: bash

      - name: Run the build script
        id: build
        run: |
          /usr/bin/env bash ${{ github.workspace }}/infomaniak-build-tools/linux/build-release-appimage-arm64.sh --src-dir ${{ github.workspace }}
        shell: bash

      - name: Upload app installer
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-artifacts-appimage-arm64
          path: ${{ github.workspace }}/build-linux-arm64/install/kDrive-*-amd64.AppImage # kDrive-<full_version>-amd64.AppImage
          retention-days: 1
        if: steps.build.outcome == 'success'

      - name: Clean-up generated code
        run : rm -rf build-linux
        shell: bash
