//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -GenerateColorBindings -GenerateDependencyObject -Language CSharp -Public -WinUIVersion 3.0 -InputFile check-dark.json
//       
//       Input file:
//           check-dark.json (12231 bytes created 18:23+02:00 Apr 17 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   129 |
// |--------------------------+-------|
// | Expression animators     |    22 |
// | KeyFrame animators       |    24 |
// | Reference parameters     |    22 |
// | Expression operations    |    28 |
// |--------------------------+-------|
// | Animated brushes         |     7 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |    22 |
// | PathKeyFrameAnimations   |     1 |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     8 |
// | CompositionSpriteShapes  |     6 |
// |--------------------------+-------|
// | Brushes                  |     7 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Name:        kDrive-Check-DARK
    // Frame rate:  60 fps
    // Frame count: 168
    // Duration:    2800.0 mS
    sealed class Check_dark
        : DependencyObject
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 2.800 seconds.
        internal const long c_durationTicks = 28000000;

        // Theme property: Color_0A2810.
        internal static readonly Color c_themeColor_0A2810 = Color.FromArgb(0xFF, 0x0A, 0x28, 0x10);

        // Theme property: Color_5FC86B.
        internal static readonly Color c_themeColor_5FC86B = Color.FromArgb(0xFF, 0x5F, 0xC8, 0x6B);

        // Theme property: Color_84A9F9.
        internal static readonly Color c_themeColor_84A9F9 = Color.FromArgb(0xFF, 0x84, 0xA9, 0xF9);

        // Theme property: Color_9EBAF8.
        internal static readonly Color c_themeColor_9EBAF8 = Color.FromArgb(0xFF, 0x9E, 0xBA, 0xF8);

        // Theme property: Color_B6C9F6.
        internal static readonly Color c_themeColor_B6C9F6 = Color.FromArgb(0xFF, 0xB6, 0xC9, 0xF6);

        // Theme property: Color_C2D3F7.
        internal static readonly Color c_themeColor_C2D3F7 = Color.FromArgb(0xFF, 0xC2, 0xD3, 0xF7);

        // Theme property: Color_C3D2F4.
        internal static readonly Color c_themeColor_C3D2F4 = Color.FromArgb(0xFF, 0xC3, 0xD2, 0xF4);

        CompositionPropertySet _themeProperties;

        /// <summary>
        /// Dependency property for Color_0A2810.
        /// </summary>
        public static readonly DependencyProperty Color_0A2810Property =
            DependencyProperty.Register("Color_0A2810", typeof(Color), typeof(Check_dark),
                new PropertyMetadata(Color.FromArgb(0xFF, 0x0A, 0x28, 0x10), OnColor_0A2810Changed));

        /// <summary>
        /// Dependency property for Color_5FC86B.
        /// </summary>
        public static readonly DependencyProperty Color_5FC86BProperty =
            DependencyProperty.Register("Color_5FC86B", typeof(Color), typeof(Check_dark),
                new PropertyMetadata(Color.FromArgb(0xFF, 0x5F, 0xC8, 0x6B), OnColor_5FC86BChanged));

        /// <summary>
        /// Dependency property for Color_84A9F9.
        /// </summary>
        public static readonly DependencyProperty Color_84A9F9Property =
            DependencyProperty.Register("Color_84A9F9", typeof(Color), typeof(Check_dark),
                new PropertyMetadata(Color.FromArgb(0xFF, 0x84, 0xA9, 0xF9), OnColor_84A9F9Changed));

        /// <summary>
        /// Dependency property for Color_9EBAF8.
        /// </summary>
        public static readonly DependencyProperty Color_9EBAF8Property =
            DependencyProperty.Register("Color_9EBAF8", typeof(Color), typeof(Check_dark),
                new PropertyMetadata(Color.FromArgb(0xFF, 0x9E, 0xBA, 0xF8), OnColor_9EBAF8Changed));

        /// <summary>
        /// Dependency property for Color_B6C9F6.
        /// </summary>
        public static readonly DependencyProperty Color_B6C9F6Property =
            DependencyProperty.Register("Color_B6C9F6", typeof(Color), typeof(Check_dark),
                new PropertyMetadata(Color.FromArgb(0xFF, 0xB6, 0xC9, 0xF6), OnColor_B6C9F6Changed));

        /// <summary>
        /// Dependency property for Color_C2D3F7.
        /// </summary>
        public static readonly DependencyProperty Color_C2D3F7Property =
            DependencyProperty.Register("Color_C2D3F7", typeof(Color), typeof(Check_dark),
                new PropertyMetadata(Color.FromArgb(0xFF, 0xC2, 0xD3, 0xF7), OnColor_C2D3F7Changed));

        /// <summary>
        /// Dependency property for Color_C3D2F4.
        /// </summary>
        public static readonly DependencyProperty Color_C3D2F4Property =
            DependencyProperty.Register("Color_C3D2F4", typeof(Color), typeof(Check_dark),
                new PropertyMetadata(Color.FromArgb(0xFF, 0xC3, 0xD2, 0xF4), OnColor_C3D2F4Changed));

        // Theme properties.
        public Color Color_0A2810
        {
            get => (Color)GetValue(Color_0A2810Property);
            set => SetValue(Color_0A2810Property, value);
        }

        public Color Color_5FC86B
        {
            get => (Color)GetValue(Color_5FC86BProperty);
            set => SetValue(Color_5FC86BProperty, value);
        }

        public Color Color_84A9F9
        {
            get => (Color)GetValue(Color_84A9F9Property);
            set => SetValue(Color_84A9F9Property, value);
        }

        public Color Color_9EBAF8
        {
            get => (Color)GetValue(Color_9EBAF8Property);
            set => SetValue(Color_9EBAF8Property, value);
        }

        public Color Color_B6C9F6
        {
            get => (Color)GetValue(Color_B6C9F6Property);
            set => SetValue(Color_B6C9F6Property, value);
        }

        public Color Color_C2D3F7
        {
            get => (Color)GetValue(Color_C2D3F7Property);
            set => SetValue(Color_C2D3F7Property, value);
        }

        public Color Color_C3D2F4
        {
            get => (Color)GetValue(Color_C3D2F4Property);
            set => SetValue(Color_C3D2F4Property, value);
        }

        static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        static void OnColor_0A2810Changed(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((Check_dark)d)._themeProperties?.InsertVector4("Color_0A2810", ColorAsVector4((Color)(Color)args.NewValue));
        }

        static void OnColor_5FC86BChanged(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((Check_dark)d)._themeProperties?.InsertVector4("Color_5FC86B", ColorAsVector4((Color)(Color)args.NewValue));
        }

        static void OnColor_84A9F9Changed(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((Check_dark)d)._themeProperties?.InsertVector4("Color_84A9F9", ColorAsVector4((Color)(Color)args.NewValue));
        }

        static void OnColor_9EBAF8Changed(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((Check_dark)d)._themeProperties?.InsertVector4("Color_9EBAF8", ColorAsVector4((Color)(Color)args.NewValue));
        }

        static void OnColor_B6C9F6Changed(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((Check_dark)d)._themeProperties?.InsertVector4("Color_B6C9F6", ColorAsVector4((Color)(Color)args.NewValue));
        }

        static void OnColor_C2D3F7Changed(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((Check_dark)d)._themeProperties?.InsertVector4("Color_C2D3F7", ColorAsVector4((Color)(Color)args.NewValue));
        }

        static void OnColor_C3D2F4Changed(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((Check_dark)d)._themeProperties?.InsertVector4("Color_C3D2F4", ColorAsVector4((Color)(Color)args.NewValue));
        }

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties == null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Color_0A2810", ColorAsVector4((Color)Color_0A2810));
                _themeProperties.InsertVector4("Color_5FC86B", ColorAsVector4((Color)Color_5FC86B));
                _themeProperties.InsertVector4("Color_84A9F9", ColorAsVector4((Color)Color_84A9F9));
                _themeProperties.InsertVector4("Color_9EBAF8", ColorAsVector4((Color)Color_9EBAF8));
                _themeProperties.InsertVector4("Color_B6C9F6", ColorAsVector4((Color)Color_B6C9F6));
                _themeProperties.InsertVector4("Color_C2D3F7", ColorAsVector4((Color)Color_C2D3F7));
                _themeProperties.InsertVector4("Color_C3D2F4", ColorAsVector4((Color)Color_C3D2F4));
            }
            return _themeProperties;
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            var res = 
                new Check_dark_AnimatedVisual(
                    compositor,
                    _themeProperties
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 168d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(28000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 168d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
            if (propertyName == "Color_0A2810")
            {
                Color_0A2810 = value;
            }
            else if (propertyName == "Color_5FC86B")
            {
                Color_5FC86B = value;
            }
            else if (propertyName == "Color_84A9F9")
            {
                Color_84A9F9 = value;
            }
            else if (propertyName == "Color_9EBAF8")
            {
                Color_9EBAF8 = value;
            }
            else if (propertyName == "Color_B6C9F6")
            {
                Color_B6C9F6 = value;
            }
            else if (propertyName == "Color_C2D3F7")
            {
                Color_C2D3F7 = value;
            }
            else if (propertyName == "Color_C3D2F4")
            {
                Color_C3D2F4 = value;
            }
            else
            {
                return;
            }

            if (_themeProperties != null)
            {
                _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
            }
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Check_dark_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 28000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            AnimationController _animationController_0;
            CompositionColorBrush _themeColor_Color_0A2810;
            CompositionColorBrush _themeColor_Color_5FC86B;
            CompositionColorBrush _themeColor_Color_84A9F9;
            CompositionColorBrush _themeColor_Color_9EBAF8;
            CompositionColorBrush _themeColor_Color_B6C9F6;
            CompositionColorBrush _themeColor_Color_C2D3F7;
            CompositionColorBrush _themeColor_Color_C3D2F4;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionContainerShape _containerShape_3;
            CompositionContainerShape _containerShape_4;
            CompositionContainerShape _containerShape_5;
            CompositionContainerShape _containerShape_6;
            CompositionContainerShape _containerShape_7;
            CompositionPath _path_0;
            CompositionPath _path_1;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_1;
            CompositionSpriteShape _spriteShape_2;
            CompositionSpriteShape _spriteShape_3;
            CompositionSpriteShape _spriteShape_4;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            ScalarKeyFrameAnimation _strokeThicknessScalarAnimation_1_to_1;
            StepEasingFunction _holdThenStepEasingFunction;
            Vector2KeyFrameAnimation _anchorVector2Animation_0;
            Vector2KeyFrameAnimation _anchorVector2Animation_1;
            Vector2KeyFrameAnimation _positionVector2Animation_0;
            Vector2KeyFrameAnimation _positionVector2Animation_1;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(7.921F, 0.465999991F));
                    builder.AddCubicBezier(new Vector2(4.15899992F, -1.171F), new Vector2(0F, 1.70599997F), new Vector2(0F, 5.96299982F));
                    builder.AddLine(new Vector2(0F, 19.8449993F));
                    builder.AddLine(new Vector2(0F, 70.0530014F));
                    builder.AddCubicBezier(new Vector2(0F, 72.6529999F), new Vector2(1.67400002F, 74.9449997F), new Vector2(4.14900017F, 75.7289963F));
                    builder.AddLine(new Vector2(67.5169983F, 95.7819977F));
                    builder.AddCubicBezier(new Vector2(71.348999F, 96.9929962F), new Vector2(75.25F, 94.1360016F), new Vector2(75.25F, 90.1070023F));
                    builder.AddLine(new Vector2(75.25F, 39.0950012F));
                    builder.AddCubicBezier(new Vector2(75.25F, 36.4949989F), new Vector2(73.5759964F, 34.2029991F), new Vector2(71.1009979F, 33.4189987F));
                    builder.AddLine(new Vector2(24.3470001F, 18.625F));
                    builder.AddLine(new Vector2(20.9810009F, 8.33500004F));
                    builder.AddCubicBezier(new Vector2(20.4559994F, 6.71799994F), new Vector2(19.2779999F, 5.41800022F), new Vector2(17.7730007F, 4.76300001F));
                    builder.AddLine(new Vector2(7.921F, 0.465999991F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.36000013F, 12.0100002F));
                    builder.AddCubicBezier(new Vector2(3.25999999F, 7.30999994F), new Vector2(7.65999985F, 2.32999992F), new Vector2(12.5799999F, 3.81999993F));
                    builder.AddCubicBezier(new Vector2(12.5799999F, 3.81999993F), new Vector2(77.3899994F, 23.4799995F), new Vector2(77.3899994F, 23.4799995F));
                    builder.AddCubicBezier(new Vector2(79.0500031F, 23.9799995F), new Vector2(80.4100037F, 25.1900005F), new Vector2(81.1200027F, 26.7700005F));
                    builder.AddCubicBezier(new Vector2(81.1200027F, 26.7700005F), new Vector2(99.4700012F, 67.6699982F), new Vector2(99.4700012F, 67.6699982F));
                    builder.AddCubicBezier(new Vector2(101.599998F, 72.4199982F), new Vector2(97.0899963F, 77.4400024F), new Vector2(92.1399994F, 75.8300018F));
                    builder.AddCubicBezier(new Vector2(92.1399994F, 75.8300018F), new Vector2(26.5400009F, 54.5499992F), new Vector2(26.5400009F, 54.5499992F));
                    builder.AddCubicBezier(new Vector2(24.9200001F, 54.0299988F), new Vector2(23.6000004F, 52.8400002F), new Vector2(22.9099998F, 51.2900009F));
                    builder.AddCubicBezier(new Vector2(22.9099998F, 51.2900009F), new Vector2(5.36000013F, 12.0100002F), new Vector2(5.36000013F, 12.0100002F));
                    builder.AddCubicBezier(new Vector2(5.36000013F, 12.0100002F), new Vector2(5.36000013F, 12.0100002F), new Vector2(5.36000013F, 12.0100002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, 8.21000004F));
                    builder.AddCubicBezier(new Vector2(0F, 4.1500001F), new Vector2(3.96000004F, 1.25999999F), new Vector2(7.82999992F, 2.5F));
                    builder.AddCubicBezier(new Vector2(7.82999992F, 2.5F), new Vector2(71.8300018F, 22.9400005F), new Vector2(71.8300018F, 22.9400005F));
                    builder.AddCubicBezier(new Vector2(74.3199997F, 23.7299995F), new Vector2(76F, 26.0499992F), new Vector2(76F, 28.6599998F));
                    builder.AddCubicBezier(new Vector2(76F, 28.6599998F), new Vector2(76F, 80.7900009F), new Vector2(76F, 80.7900009F));
                    builder.AddCubicBezier(new Vector2(76F, 84.8499985F), new Vector2(72.0400009F, 87.7399979F), new Vector2(68.1699982F, 86.5F));
                    builder.AddCubicBezier(new Vector2(68.1699982F, 86.5F), new Vector2(4.17000008F, 66.0599976F), new Vector2(4.17000008F, 66.0599976F));
                    builder.AddCubicBezier(new Vector2(1.67999995F, 65.2699966F), new Vector2(0F, 62.9599991F), new Vector2(0F, 60.3499985F));
                    builder.AddCubicBezier(new Vector2(0F, 60.3499985F), new Vector2(0F, 8.21000004F), new Vector2(0F, 8.21000004F));
                    builder.AddCubicBezier(new Vector2(0F, 8.21000004F), new Vector2(0F, 8.21000004F), new Vector2(0F, 8.21000004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: fond Offset:<0.5, 0.5>
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(71F, 35.5F));
                    builder.AddCubicBezier(new Vector2(71F, 55.1040001F), new Vector2(55.1040001F, 71F), new Vector2(35.5F, 71F));
                    builder.AddCubicBezier(new Vector2(15.8959999F, 71F), new Vector2(0F, 55.1040001F), new Vector2(0F, 35.5F));
                    builder.AddCubicBezier(new Vector2(0F, 15.8959999F), new Vector2(15.8959999F, 0F), new Vector2(35.5F, 0F));
                    builder.AddCubicBezier(new Vector2(55.1040001F, 0F), new Vector2(71F, 15.8959999F), new Vector2(71F, 35.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: Icons/Actions/check Offset:<16.999998, 16.999998>
            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(32.6399994F, 0.239999995F));
                    builder.AddCubicBezier(new Vector2(32.1199989F, -0.150000006F), new Vector2(31.3799992F, -0.0500000007F), new Vector2(30.9899998F, 0.469999999F));
                    builder.AddLine(new Vector2(10.8900003F, 27.0300007F));
                    builder.AddLine(new Vector2(10.8800001F, 27.0499992F));
                    builder.AddCubicBezier(new Vector2(10.7299995F, 27.2600002F), new Vector2(10.5299997F, 27.4099998F), new Vector2(10.3199997F, 27.5200005F));
                    builder.AddCubicBezier(new Vector2(10.1099997F, 27.6299992F), new Vector2(9.88000011F, 27.6800003F), new Vector2(9.64999962F, 27.6700001F));
                    builder.AddCubicBezier(new Vector2(9.42000008F, 27.6599998F), new Vector2(9.18999958F, 27.6000004F), new Vector2(8.97999954F, 27.4799995F));
                    builder.AddCubicBezier(new Vector2(8.77000046F, 27.3600006F), new Vector2(8.60000038F, 27.1900005F), new Vector2(8.46000004F, 26.9699993F));
                    builder.AddLine(new Vector2(8.43999958F, 26.9400005F));
                    builder.AddLine(new Vector2(2.16000009F, 17.6399994F));
                    builder.AddCubicBezier(new Vector2(1.79999995F, 17.1000004F), new Vector2(1.05999994F, 16.9599991F), new Vector2(0.519999981F, 17.3199997F));
                    builder.AddCubicBezier(new Vector2(-0.0199999996F, 17.6900005F), new Vector2(-0.170000002F, 18.4200001F), new Vector2(0.200000003F, 18.9599991F));
                    builder.AddLine(new Vector2(6.48000002F, 28.2600002F));
                    builder.AddCubicBezier(new Vector2(6.82000017F, 28.7800007F), new Vector2(7.26999998F, 29.2099991F), new Vector2(7.80000019F, 29.5200005F));
                    builder.AddCubicBezier(new Vector2(8.34000015F, 29.8299999F), new Vector2(8.96000004F, 30.0100002F), new Vector2(9.57999992F, 30.0300007F));
                    builder.AddCubicBezier(new Vector2(10.1999998F, 30.0499992F), new Vector2(10.8199997F, 29.9200001F), new Vector2(11.3800001F, 29.6399994F));
                    builder.AddCubicBezier(new Vector2(11.9300003F, 29.3600006F), new Vector2(12.3999996F, 28.9500008F), new Vector2(12.7700005F, 28.4500008F));
                    builder.AddLine(new Vector2(12.7799997F, 28.4599991F));
                    builder.AddLine(new Vector2(32.8800011F, 1.89999998F));
                    builder.AddCubicBezier(new Vector2(33.2700005F, 1.38F), new Vector2(33.1599998F, 0.629999995F), new Vector2(32.6399994F, 0.239999995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - Layer aggregator
            // Transforms: fond Offset:<0.5, 0.5>
            // Color bound to theme property value: Color_0A2810
            CompositionColorBrush ThemeColor_Color_0A2810()
            {
                if (_themeColor_Color_0A2810 != null) { return _themeColor_Color_0A2810; }
                var result = _themeColor_Color_0A2810 = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_0A2810, "Color", "ColorRGB(_theme.Color_0A2810.W,_theme.Color_0A2810.X,_theme.Color_0A2810.Y,_theme.Color_0A2810.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Color_5FC86B
            CompositionColorBrush ThemeColor_Color_5FC86B()
            {
                if (_themeColor_Color_5FC86B != null) { return _themeColor_Color_5FC86B; }
                var result = _themeColor_Color_5FC86B = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_5FC86B, "Color", "ColorRGB(_theme.Color_5FC86B.W,_theme.Color_5FC86B.X,_theme.Color_5FC86B.Y,_theme.Color_5FC86B.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Color_84A9F9
            CompositionColorBrush ThemeColor_Color_84A9F9()
            {
                if (_themeColor_Color_84A9F9 != null) { return _themeColor_Color_84A9F9; }
                var result = _themeColor_Color_84A9F9 = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_84A9F9, "Color", "ColorRGB(_theme.Color_84A9F9.W,_theme.Color_84A9F9.X,_theme.Color_84A9F9.Y,_theme.Color_84A9F9.Z)", "_theme", _themeProperties);
                return result;
            }

            // - Transforms: folder-01
            // Transforms: page-back
            // Color bound to theme property value: Color_9EBAF8
            CompositionColorBrush ThemeColor_Color_9EBAF8()
            {
                if (_themeColor_Color_9EBAF8 != null) { return _themeColor_Color_9EBAF8; }
                var result = _themeColor_Color_9EBAF8 = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_9EBAF8, "Color", "ColorRGB(_theme.Color_9EBAF8.W,_theme.Color_9EBAF8.X,_theme.Color_9EBAF8.Y,_theme.Color_9EBAF8.Z)", "_theme", _themeProperties);
                return result;
            }

            // Transforms: folder-02
            // Color bound to theme property value: Color_B6C9F6
            CompositionColorBrush ThemeColor_Color_B6C9F6()
            {
                if (_themeColor_Color_B6C9F6 != null) { return _themeColor_Color_B6C9F6; }
                var result = _themeColor_Color_B6C9F6 = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_B6C9F6, "Color", "ColorRGB(_theme.Color_B6C9F6.W,_theme.Color_B6C9F6.X,_theme.Color_B6C9F6.Y,_theme.Color_B6C9F6.Z)", "_theme", _themeProperties);
                return result;
            }

            // - Transforms: page-front
            // Color bound to theme property value: Color_C2D3F7
            CompositionColorBrush ThemeColor_Color_C2D3F7()
            {
                if (_themeColor_Color_C2D3F7 != null) { return _themeColor_Color_C2D3F7; }
                var result = _themeColor_Color_C2D3F7 = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_C2D3F7, "Color", "ColorRGB(_theme.Color_C2D3F7.W,_theme.Color_C2D3F7.X,_theme.Color_C2D3F7.Y,_theme.Color_C2D3F7.Z)", "_theme", _themeProperties);
                return result;
            }

            // Transforms: folder-03
            // Color bound to theme property value: Color_C3D2F4
            CompositionColorBrush ThemeColor_Color_C3D2F4()
            {
                if (_themeColor_Color_C3D2F4 != null) { return _themeColor_Color_C3D2F4; }
                var result = _themeColor_Color_C3D2F4 = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_C3D2F4, "Color", "ColorRGB(_theme.Color_C3D2F4.W,_theme.Color_C3D2F4.X,_theme.Color_C3D2F4.Y,_theme.Color_C3D2F4.Z)", "_theme", _themeProperties);
                return result;
            }

            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(65.0100021F, 61.5999985F));
                propertySet.InsertVector2("Position", new Vector2(65.1800003F, 75.4000015F));
                // Transforms: folder-03
                result.Shapes.Add(SpriteShape_0());
                BindProperty(_containerShape_0, "CenterPoint", "my.Anchor", "my", _containerShape_0);
                BindProperty(_containerShape_0, "Offset", "my.Position-my.Anchor", "my", _containerShape_0);
                return result;
            }

            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(65.0100021F, 61.5999985F));
                propertySet.InsertVector2("Position", new Vector2(65.1800003F, 75.4000015F));
                // Transforms: folder-02
                result.Shapes.Add(SpriteShape_1());
                BindProperty(_containerShape_1, "CenterPoint", "my.Anchor", "my", _containerShape_1);
                BindProperty(_containerShape_1, "Offset", "my.Position-my.Anchor", "my", _containerShape_1);
                return result;
            }

            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(65.0100021F, 61.5999985F));
                propertySet.InsertVector2("Position", new Vector2(65.1800003F, 75.4000015F));
                // Transforms: folder-01
                result.Shapes.Add(ContainerShape_3());
                BindProperty(_containerShape_2, "CenterPoint", "my.Anchor", "my", _containerShape_2);
                BindProperty(_containerShape_2, "Offset", "my.Position-my.Anchor", "my", _containerShape_2);
                return result;
            }

            // Transforms for folder-01
            CompositionContainerShape ContainerShape_3()
            {
                if (_containerShape_3 != null) { return _containerShape_3; }
                var result = _containerShape_3 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(52.5F, 50.5999985F));
                propertySet.InsertVector2("Position", new Vector2(52.5F, 72.5999985F));
                // Transforms: page-back
                result.Shapes.Add(SpriteShape_2());
                BindProperty(_containerShape_3, "CenterPoint", "my.Anchor", "my", _containerShape_3);
                BindProperty(_containerShape_3, "Offset", "my.Position-my.Anchor", "my", _containerShape_3);
                return result;
            }

            CompositionContainerShape ContainerShape_4()
            {
                if (_containerShape_4 != null) { return _containerShape_4; }
                var result = _containerShape_4 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(65.0100021F, 61.5999985F));
                propertySet.InsertVector2("Position", new Vector2(65.1800003F, 75.4000015F));
                // Transforms: folder-01
                result.Shapes.Add(ContainerShape_5());
                BindProperty(_containerShape_4, "CenterPoint", "my.Anchor", "my", _containerShape_4);
                BindProperty(_containerShape_4, "Offset", "my.Position-my.Anchor", "my", _containerShape_4);
                return result;
            }

            // Transforms for folder-01
            CompositionContainerShape ContainerShape_5()
            {
                if (_containerShape_5 != null) { return _containerShape_5; }
                var result = _containerShape_5 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(52.5F, 50.5999985F));
                propertySet.InsertVector2("Position", new Vector2(52.5F, 72.5999985F));
                // Transforms: page-front
                result.Shapes.Add(ContainerShape_6());
                BindProperty(_containerShape_5, "CenterPoint", "my.Anchor", "my", _containerShape_5);
                BindProperty(_containerShape_5, "Offset", "my.Position-my.Anchor", "my", _containerShape_5);
                return result;
            }

            // Transforms for page-front
            CompositionContainerShape ContainerShape_6()
            {
                if (_containerShape_6 != null) { return _containerShape_6; }
                var result = _containerShape_6 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(52.5F, 40F));
                propertySet.InsertVector2("Position", new Vector2(52.5F, 61.2000008F));
                result.Shapes.Add(SpriteShape_3());
                BindProperty(_containerShape_6, "CenterPoint", "my.Anchor", "my", _containerShape_6);
                BindProperty(_containerShape_6, "Offset", "my.Position-my.Anchor", "my", _containerShape_6);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_7()
            {
                if (_containerShape_7 != null) { return _containerShape_7; }
                var result = _containerShape_7 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // Transforms: fond Offset:<0.5, 0.5>
                shapes.Add(SpriteShape_4());
                // Transforms: Icons/Actions/check Offset:<16.999998, 16.999998>
                shapes.Add(SpriteShape_5());
                return result;
            }

            CompositionPath Path_0()
            {
                if (_path_0 != null) { return _path_0; }
                var result = _path_0 = new CompositionPath(Geometry_1());
                return result;
            }

            CompositionPath Path_1()
            {
                if (_path_1 != null) { return _path_1; }
                var result = _path_1 = new CompositionPath(Geometry_2());
                return result;
            }

            CompositionPathGeometry PathGeometry_0()
            {
                return (_pathGeometry_0 == null)
                    ? _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()))
                    : _pathGeometry_0;
            }

            // - Transforms: page-front
            CompositionPathGeometry PathGeometry_1()
            {
                if (_pathGeometry_1 != null) { return _pathGeometry_1; }
                var result = _pathGeometry_1 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // Transforms: fond Offset:<0.5, 0.5>
            CompositionPathGeometry PathGeometry_2()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
            }

            // - - Layer aggregator
            // Transforms: Icons/Actions/check Offset:<16.999998, 16.999998>
            CompositionPathGeometry PathGeometry_3()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
            }

            // Transforms for folder-03
            CompositionSpriteShape SpriteShape_0()
            {
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ThemeColor_Color_C3D2F4();
                result.StrokeBrush = ThemeColor_Color_84A9F9();
                result.StrokeMiterLimit = 2F;
                return result;
            }

            // Transforms for folder-02
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ThemeColor_Color_B6C9F6();
                result.StrokeBrush = ThemeColor_Color_84A9F9();
                result.StrokeMiterLimit = 2F;
                return result;
            }

            // Transforms: folder-01
            // Transforms for page-back
            CompositionSpriteShape SpriteShape_2()
            {
                if (_spriteShape_2 != null) { return _spriteShape_2; }
                var result = _spriteShape_2 = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ThemeColor_Color_9EBAF8();
                result.StrokeBrush = ThemeColor_Color_84A9F9();
                result.StrokeMiterLimit = 2F;
                return result;
            }

            // Transforms: page-front
            CompositionSpriteShape SpriteShape_3()
            {
                if (_spriteShape_3 != null) { return _spriteShape_3; }
                var result = _spriteShape_3 = _c.CreateSpriteShape(PathGeometry_1());
                result.FillBrush = ThemeColor_Color_C2D3F7();
                result.StrokeBrush = ThemeColor_Color_84A9F9();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                return result;
            }

            // - Layer aggregator
            // Transforms for fond Offset:<0.5, 0.5>
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<0.5, 0.5>
                var geometry = PathGeometry_2();
                if (_spriteShape_4 != null) { return _spriteShape_4; }
                var result = _spriteShape_4 = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0.5F, 0.5F), ThemeColor_Color_0A2810());;
                result.StrokeBrush = ThemeColor_Color_5FC86B();
                result.StrokeMiterLimit = 2F;
                return result;
            }

            // - Layer aggregator
            // Transforms for icon Offset:<2.3600006, 3.8999996>
            CompositionSpriteShape SpriteShape_5()
            {
                // Offset:<19.359999, 20.899998>
                var geometry = PathGeometry_3();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 19.3599987F, 20.8999977F), ThemeColor_Color_5FC86B());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.649999976F, 0F), new Vector2(0.349999994F, 0F))
                    : _cubicBezierEasingFunction_0;
            }

            // - - Transforms: page-front
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_0(), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, Path_0(), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, Path_1(), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, Path_1(), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, Path_0(), CubicBezierEasingFunction_0());
                return result;
            }

            // StrokeThickness
            ScalarKeyFrameAnimation StrokeThicknessScalarAnimation_1_to_1()
            {
                // Frame 0.
                if (_strokeThicknessScalarAnimation_1_to_1 != null) { return _strokeThicknessScalarAnimation_1_to_1; }
                var result = _strokeThicknessScalarAnimation_1_to_1 = CreateScalarKeyFrameAnimation(0F, 1F, HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, 1F, CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, 1F, CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, 1F, CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(163F, 134F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_0());
                shapes.Add(ContainerShape_1());
                shapes.Add(ContainerShape_2());
                shapes.Add(ContainerShape_4());
                shapes.Add(ContainerShape_7());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // Anchor
            Vector2KeyFrameAnimation AnchorVector2Animation_0()
            {
                // Frame 0.
                if (_anchorVector2Animation_0 != null) { return _anchorVector2Animation_0; }
                var result = _anchorVector2Animation_0 = CreateVector2KeyFrameAnimation(0F, new Vector2(65.0100021F, 61.5999985F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(65.0100021F, 61.5999985F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(38.0099983F, 49.5999985F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(38.0099983F, 49.5999985F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(65.0100021F, 61.5999985F), CubicBezierEasingFunction_0());
                return result;
            }

            // Anchor
            Vector2KeyFrameAnimation AnchorVector2Animation_1()
            {
                // Frame 0.
                if (_anchorVector2Animation_1 != null) { return _anchorVector2Animation_1; }
                var result = _anchorVector2Animation_1 = CreateVector2KeyFrameAnimation(0F, new Vector2(52.5F, 50.5999985F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(52.5F, 50.5999985F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(38.0099983F, 49.5999985F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(38.0099983F, 49.5999985F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(52.5F, 50.5999985F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Transforms: page-front
            // Anchor
            Vector2KeyFrameAnimation AnchorVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(52.5F, 40F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(52.5F, 40F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(38F, 44.5F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(38F, 44.5F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(52.5F, 40F), CubicBezierEasingFunction_0());
                return result;
            }

            // Transforms: folder-03
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(54.4000015F, 0.370000005F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(54.4000015F, 0.370000005F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(0.400000006F, 0.370000005F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(0.400000006F, 0.370000005F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(54.4000015F, 0.370000005F), CubicBezierEasingFunction_0());
                return result;
            }

            // Transforms: folder-02
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(39.4000015F, 12.3699999F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(39.4000015F, 12.3699999F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(0.400000006F, 0.370000005F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(0.400000006F, 0.370000005F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(39.4000015F, 12.3699999F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Transforms: folder-01
            // Transforms: page-back
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(24.3999996F, 0.370000005F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(24.3999996F, 0.370000005F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(0.400000006F, 0.370000005F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(0.400000006F, 0.370000005F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(24.3999996F, 0.370000005F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(88.8300018F, 0F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(88.8300018F, 0F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(88.6699982F, 0F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(88.6699982F, 0F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(88.8300018F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_0()
            {
                // Frame 0.
                if (_positionVector2Animation_0 != null) { return _positionVector2Animation_0; }
                var result = _positionVector2Animation_0 = CreateVector2KeyFrameAnimation(0F, new Vector2(65.1800003F, 75.4000015F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(65.1800003F, 75.4000015F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(77.1800003F, 75.4000015F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(77.1800003F, 75.4000015F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(65.1800003F, 75.4000015F), CubicBezierEasingFunction_0());
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_1()
            {
                // Frame 0.
                if (_positionVector2Animation_1 != null) { return _positionVector2Animation_1; }
                var result = _positionVector2Animation_1 = CreateVector2KeyFrameAnimation(0F, new Vector2(52.5F, 72.5999985F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(52.5F, 72.5999985F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(38.0099983F, 49.5999985F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(38.0099983F, 49.5999985F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(52.5F, 72.5999985F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Transforms: page-front
            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(52.5F, 61.2000008F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.357142866F, new Vector2(52.5F, 61.2000008F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.535714269F, new Vector2(38F, 54.7000008F), CubicBezierEasingFunction_0());
                // Frame 138.
                result.InsertKeyFrame(0.821428597F, new Vector2(38F, 54.7000008F), CubicBezierEasingFunction_0());
                // Frame 168.
                result.InsertKeyFrame(1F, new Vector2(52.5F, 61.2000008F), CubicBezierEasingFunction_0());
                return result;
            }

            internal Check_dark_AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(163F, 134F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape_0.Properties.StartAnimation("Anchor", AnchorVector2Animation_0(), AnimationController_0());
                _containerShape_0.Properties.StartAnimation("Position", PositionVector2Animation_0(), AnimationController_0());
                _containerShape_1.Properties.StartAnimation("Anchor", AnchorVector2Animation_0(), AnimationController_0());
                _containerShape_1.Properties.StartAnimation("Position", PositionVector2Animation_0(), AnimationController_0());
                _containerShape_2.Properties.StartAnimation("Anchor", AnchorVector2Animation_0(), AnimationController_0());
                _containerShape_2.Properties.StartAnimation("Position", PositionVector2Animation_0(), AnimationController_0());
                _containerShape_3.Properties.StartAnimation("Anchor", AnchorVector2Animation_1(), AnimationController_0());
                _containerShape_3.Properties.StartAnimation("Position", PositionVector2Animation_1(), AnimationController_0());
                _containerShape_4.Properties.StartAnimation("Anchor", AnchorVector2Animation_0(), AnimationController_0());
                _containerShape_4.Properties.StartAnimation("Position", PositionVector2Animation_0(), AnimationController_0());
                _containerShape_5.Properties.StartAnimation("Anchor", AnchorVector2Animation_1(), AnimationController_0());
                _containerShape_5.Properties.StartAnimation("Position", PositionVector2Animation_1(), AnimationController_0());
                _containerShape_6.Properties.StartAnimation("Anchor", AnchorVector2Animation_2(), AnimationController_0());
                _containerShape_6.Properties.StartAnimation("Position", PositionVector2Animation_2(), AnimationController_0());
                _containerShape_7.StartAnimation("Offset", OffsetVector2Animation_3(), AnimationController_0());
                _pathGeometry_1.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _spriteShape_0.StartAnimation("StrokeThickness", StrokeThicknessScalarAnimation_1_to_1(), AnimationController_0());
                _spriteShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _spriteShape_1.StartAnimation("StrokeThickness", StrokeThicknessScalarAnimation_1_to_1(), AnimationController_0());
                _spriteShape_1.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
                _spriteShape_2.StartAnimation("StrokeThickness", StrokeThicknessScalarAnimation_1_to_1(), AnimationController_0());
                _spriteShape_2.StartAnimation("Offset", OffsetVector2Animation_2(), AnimationController_0());
                _spriteShape_3.StartAnimation("StrokeThickness", StrokeThicknessScalarAnimation_1_to_1(), AnimationController_0());
                _spriteShape_4.StartAnimation("StrokeThickness", StrokeThicknessScalarAnimation_1_to_1(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape_0.Properties.StopAnimation("Anchor");
                _containerShape_0.Properties.StopAnimation("Position");
                _containerShape_1.Properties.StopAnimation("Anchor");
                _containerShape_1.Properties.StopAnimation("Position");
                _containerShape_2.Properties.StopAnimation("Anchor");
                _containerShape_2.Properties.StopAnimation("Position");
                _containerShape_3.Properties.StopAnimation("Anchor");
                _containerShape_3.Properties.StopAnimation("Position");
                _containerShape_4.Properties.StopAnimation("Anchor");
                _containerShape_4.Properties.StopAnimation("Position");
                _containerShape_5.Properties.StopAnimation("Anchor");
                _containerShape_5.Properties.StopAnimation("Position");
                _containerShape_6.Properties.StopAnimation("Anchor");
                _containerShape_6.Properties.StopAnimation("Position");
                _containerShape_7.StopAnimation("Offset");
                _pathGeometry_1.StopAnimation("Path");
                _spriteShape_0.StopAnimation("StrokeThickness");
                _spriteShape_0.StopAnimation("Offset");
                _spriteShape_1.StopAnimation("StrokeThickness");
                _spriteShape_1.StopAnimation("Offset");
                _spriteShape_2.StopAnimation("StrokeThickness");
                _spriteShape_2.StopAnimation("Offset");
                _spriteShape_3.StopAnimation("StrokeThickness");
                _spriteShape_4.StopAnimation("StrokeThickness");
            }

        }
    }
}
