//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -GenerateColorBindings -GenerateDependencyObject -Language CSharp -Public -WinUIVersion 3.0 -InputFile kDrive-Check.json
//       
//       Input file:
//           kDrive-Check.json (20509 bytes created 14:58+02:00 May 27 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    71 |
// |--------------------------+-------|
// | Expression animators     |     5 |
// | KeyFrame animators       |     8 |
// | Reference parameters     |     6 |
// | Expression operations    |     8 |
// |--------------------------+-------|
// | Animated brushes         |     2 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     5 |
// | PathKeyFrameAnimations   |     1 |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     3 |
// | CompositionSpriteShapes  |     6 |
// |--------------------------+-------|
// | Brushes                  |     2 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Name:        kDrive-Check-LIGHT
    // Frame rate:  60 fps
    // Frame count: 145.12
    // Duration:    2418.7 mS
    sealed class KDrive_Check
        : DependencyObject
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 2.419 seconds.
        internal const long c_durationTicks = 24186666;

        // Theme property: Color_446EDD.
        internal static readonly Color c_themeColor_446EDD = Color.FromArgb(0xFF, 0x44, 0x6E, 0xDD);

        CompositionPropertySet _themeProperties;

        /// <summary>
        /// Dependency property for Color_446EDD.
        /// </summary>
        public static readonly DependencyProperty Color_446EDDProperty =
            DependencyProperty.Register("Color_446EDD", typeof(Color), typeof(KDrive_Check),
                new PropertyMetadata(Color.FromArgb(0xFF, 0x44, 0x6E, 0xDD), OnColor_446EDDChanged));

        // Theme properties.
        public Color Color_446EDD
        {
            get => (Color)GetValue(Color_446EDDProperty);
            set => SetValue(Color_446EDDProperty, value);
        }

        static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        static void OnColor_446EDDChanged(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((KDrive_Check)d)._themeProperties?.InsertVector4("Color_446EDD", ColorAsVector4((Color)(Color)args.NewValue));
        }

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties == null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Color_446EDD", ColorAsVector4((Color)Color_446EDD));
            }
            return _themeProperties;
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            var res = 
                new KDrive_Check_AnimatedVisual(
                    compositor,
                    _themeProperties
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 145.12;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(24186666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 145.12;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
            if (propertyName == "Color_446EDD")
            {
                Color_446EDD = value;
            }
            else
            {
                return;
            }

            if (_themeProperties != null)
            {
                _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
            }
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class KDrive_Check_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 24186666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            AnimationController _animationController_0;
            CanvasGeometry _geometry_03;
            CanvasGeometry _geometry_05;
            CanvasGeometry _geometry_06;
            CanvasGeometry _geometry_07;
            CanvasGeometry _geometry_08;
            CanvasGeometry _geometry_09;
            CanvasGeometry _geometry_10;
            CanvasGeometry _geometry_11;
            CanvasGeometry _geometry_13;
            CanvasGeometry _geometry_14;
            CanvasGeometry _geometry_21;
            CompositionColorBrush _themeColor_Color_446EDD_0;
            CompositionColorBrush _themeColor_Color_446EDD_1;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionPathGeometry _pathGeometry_5;
            CompositionSpriteShape _spriteShape_3;
            CompositionSpriteShape _spriteShape_4;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            ScalarKeyFrameAnimation _strokeThicknessScalarAnimation_1p25_to_1p25;
            StepEasingFunction _holdThenStepEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            void BindProperty2(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName0,
                CompositionObject referencedObject0,
                string referenceParameterName1,
                CompositionObject referencedObject1)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName0, referencedObject0);
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName1, referencedObject1);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: folder-03 Offset:<54.11, 0>
            // - +++++++++++++.PathGeometry
            CanvasGeometry Geometry_00()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_01(), Geometry_02(), Geometry_03(), Geometry_04(), Geometry_05(), Geometry_06(), Geometry_07(), Geometry_08(), Geometry_09(), Geometry_10(), Geometry_11(), Geometry_12(), Geometry_13(), Geometry_14() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-03 Offset:<54.11, 0>
            // - - +++++++++++++.PathGeometry
            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(76F, 90.8099976F));
                    builder.AddLine(new Vector2(76.6299973F, 90.8099976F));
                    builder.AddLine(new Vector2(76.6299973F, 71F));
                    builder.AddLine(new Vector2(76F, 71F));
                    builder.AddLine(new Vector2(75.3799973F, 71F));
                    builder.AddLine(new Vector2(75.3799973F, 90.8099976F));
                    builder.AddLine(new Vector2(76F, 90.8099976F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-03 Offset:<54.11, 0>
            // - - +++++++++++++.PathGeometry
            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(45.8899994F, 25.6000004F));
                    builder.AddLine(new Vector2(46.0800018F, 25.0100002F));
                    builder.AddLine(new Vector2(24.7900009F, 18.1700001F));
                    builder.AddLine(new Vector2(24.5900002F, 18.7700005F));
                    builder.AddLine(new Vector2(24.3999996F, 19.3600006F));
                    builder.AddLine(new Vector2(45.7000008F, 26.2000008F));
                    builder.AddLine(new Vector2(45.8899994F, 25.6000004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(60.8899994F, 94.1999969F));
                    builder.AddLine(new Vector2(60.7000008F, 94.7900009F));
                    builder.AddLine(new Vector2(68F, 97.1299973F));
                    builder.AddLine(new Vector2(68.1900024F, 96.5299988F));
                    builder.AddLine(new Vector2(68.3799973F, 95.9400024F));
                    builder.AddLine(new Vector2(61.0800018F, 93.5999985F));
                    builder.AddLine(new Vector2(60.8899994F, 94.1999969F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_03 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-03 Offset:<54.11, 0>
            // - - +++++++++++++.PathGeometry
            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, 15.6999998F));
                    builder.AddLine(new Vector2(0.629999995F, 15.6999998F));
                    builder.AddLine(new Vector2(0.629999995F, 6.01000023F));
                    builder.AddLine(new Vector2(0F, 6.01000023F));
                    builder.AddLine(new Vector2(-0.620000005F, 6.01000023F));
                    builder.AddLine(new Vector2(-0.620000005F, 15.6999998F));
                    builder.AddLine(new Vector2(0F, 15.6999998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(17.9500008F, 4.80000019F));
                    builder.AddLine(new Vector2(18.2000008F, 4.23000002F));
                    builder.AddLine(new Vector2(8.25F, -0.100000001F));
                    builder.AddLine(new Vector2(8F, 0.469999999F));
                    builder.AddLine(new Vector2(7.75F, 1.03999996F));
                    builder.AddLine(new Vector2(17.7000008F, 5.36999989F));
                    builder.AddLine(new Vector2(17.9500008F, 4.80000019F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_05 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(21.1900005F, 8.39999962F));
                    builder.AddLine(new Vector2(21.7800007F, 8.19999981F));
                    builder.AddCubicBezier(new Vector2(21.1900005F, 6.40999985F), new Vector2(19.8899994F, 4.96999979F), new Vector2(18.2000008F, 4.23000002F));
                    builder.AddLine(new Vector2(17.9500008F, 4.80000019F));
                    builder.AddLine(new Vector2(17.7000008F, 5.36999989F));
                    builder.AddCubicBezier(new Vector2(19.0499992F, 5.96000004F), new Vector2(20.1100006F, 7.13000011F), new Vector2(20.5900002F, 8.59000015F));
                    builder.AddLine(new Vector2(21.1900005F, 8.39999962F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_06 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(24.5900002F, 18.7700005F));
                    builder.AddLine(new Vector2(25.1900005F, 18.5699997F));
                    builder.AddLine(new Vector2(21.7800007F, 8.19999981F));
                    builder.AddLine(new Vector2(21.1900005F, 8.39999962F));
                    builder.AddLine(new Vector2(20.5900002F, 8.59000015F));
                    builder.AddLine(new Vector2(24F, 18.9599991F));
                    builder.AddLine(new Vector2(24.5900002F, 18.7700005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_07 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(68.1900024F, 96.5299988F));
                    builder.AddLine(new Vector2(68.0100021F, 97.1299973F));
                    builder.AddCubicBezier(new Vector2(72.2799988F, 98.4800034F), new Vector2(76.6299973F, 95.2900009F), new Vector2(76.6299973F, 90.8099976F));
                    builder.AddLine(new Vector2(76F, 90.8099976F));
                    builder.AddLine(new Vector2(75.3799973F, 90.8099976F));
                    builder.AddCubicBezier(new Vector2(75.3799973F, 94.4400024F), new Vector2(71.8399963F, 97.0299988F), new Vector2(68.3799973F, 95.9400024F));
                    builder.AddLine(new Vector2(68.1900024F, 96.5299988F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_08 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(8F, 0.469999999F));
                    builder.AddLine(new Vector2(8.25F, -0.100000001F));
                    builder.AddCubicBezier(new Vector2(4F, -1.95000005F), new Vector2(-0.620000005F, 1.30999994F), new Vector2(-0.620000005F, 6.01000023F));
                    builder.AddLine(new Vector2(0F, 6.01000023F));
                    builder.AddLine(new Vector2(0.629999995F, 6.01000023F));
                    builder.AddCubicBezier(new Vector2(0.629999995F, 2.13000011F), new Vector2(4.4000001F, -0.419999987F), new Vector2(7.75F, 1.03999996F));
                    builder.AddLine(new Vector2(8F, 0.469999999F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_09 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(17.9500008F, 4.80000019F));
                    builder.AddLine(new Vector2(18.2000008F, 4.23000002F));
                    builder.AddLine(new Vector2(17.9500008F, 4.80000019F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_10 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(21.1900005F, 8.39999962F));
                    builder.AddLine(new Vector2(21.7800007F, 8.19999981F));
                    builder.AddLine(new Vector2(21.1900005F, 8.39999962F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_11 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-03 Offset:<54.11, 0>
            // - - +++++++++++++.PathGeometry
            CanvasGeometry Geometry_12()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(24.5900002F, 18.7700005F));
                    builder.AddLine(new Vector2(24F, 18.9599991F));
                    builder.AddLine(new Vector2(24.1000004F, 19.2600002F));
                    builder.AddLine(new Vector2(24.3999996F, 19.3600006F));
                    builder.AddLine(new Vector2(24.5900002F, 18.7700005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_13()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(68.1900024F, 96.5299988F));
                    builder.AddLine(new Vector2(68F, 97.1299973F));
                    builder.AddLine(new Vector2(68.0100021F, 97.1299973F));
                    builder.AddLine(new Vector2(68.1900024F, 96.5299988F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_13 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_14()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(8F, 0.469999999F));
                    builder.AddLine(new Vector2(7.75F, 1.03999996F));
                    builder.AddLine(new Vector2(8F, 0.469999999F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_14 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: folder-02 Offset:<39.11, 12>
            // - +++++++++++++++.PathGeometry
            CanvasGeometry Geometry_15()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_16(), Geometry_17(), Geometry_18(), Geometry_19(), Geometry_05(), Geometry_06(), Geometry_07(), Geometry_08(), Geometry_03(), Geometry_09(), Geometry_20(), Geometry_10(), Geometry_11(), Geometry_21(), Geometry_13(), Geometry_14() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-02 Offset:<39.11, 12>
            // - - +++++++++++++++.PathGeometry
            CanvasGeometry Geometry_16()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(76F, 90.8099976F));
                    builder.AddLine(new Vector2(76.6299973F, 90.8099976F));
                    builder.AddLine(new Vector2(76.6299973F, 54F));
                    builder.AddLine(new Vector2(76F, 54F));
                    builder.AddLine(new Vector2(75.3799973F, 54F));
                    builder.AddLine(new Vector2(75.3799973F, 90.8099976F));
                    builder.AddLine(new Vector2(76F, 90.8099976F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-02 Offset:<39.11, 12>
            // - - +++++++++++++++.PathGeometry
            CanvasGeometry Geometry_17()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(60F, 29.9500008F));
                    builder.AddLine(new Vector2(60.1899986F, 29.3500004F));
                    builder.AddLine(new Vector2(48.3899994F, 25.6299992F));
                    builder.AddLine(new Vector2(48.2000008F, 26.2199993F));
                    builder.AddLine(new Vector2(48.0099983F, 26.8199997F));
                    builder.AddLine(new Vector2(59.8199997F, 30.5400009F));
                    builder.AddLine(new Vector2(60F, 29.9500008F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-02 Offset:<39.11, 12>
            // - - +++++++++++++++.PathGeometry
            CanvasGeometry Geometry_18()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(48.2000008F, 26.2199993F));
                    builder.AddLine(new Vector2(48.3899994F, 25.6299992F));
                    builder.AddLine(new Vector2(24.7800007F, 18.1700001F));
                    builder.AddLine(new Vector2(24.5900002F, 18.7700005F));
                    builder.AddLine(new Vector2(24.4099998F, 19.3600006F));
                    builder.AddLine(new Vector2(48.0099983F, 26.8199997F));
                    builder.AddLine(new Vector2(48.2000008F, 26.2199993F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-02 Offset:<39.11, 12>
            // - - +++++++++++++++.PathGeometry
            CanvasGeometry Geometry_19()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, 13.6999998F));
                    builder.AddLine(new Vector2(0.629999995F, 13.6999998F));
                    builder.AddLine(new Vector2(0.629999995F, 6.01000023F));
                    builder.AddLine(new Vector2(0F, 6.01000023F));
                    builder.AddLine(new Vector2(-0.620000005F, 6.01000023F));
                    builder.AddLine(new Vector2(-0.620000005F, 13.6999998F));
                    builder.AddLine(new Vector2(0F, 13.6999998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-02 Offset:<39.11, 12>
            // - - +++++++++++++++.PathGeometry
            CanvasGeometry Geometry_20()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(48.2000008F, 26.2199993F));
                    builder.AddLine(new Vector2(48.0099983F, 26.8199997F));
                    builder.AddLine(new Vector2(48.2000008F, 26.2199993F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_21()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(24.5900002F, 18.7700005F));
                    builder.AddLine(new Vector2(24F, 18.9599991F));
                    builder.AddLine(new Vector2(24.1000004F, 19.2700005F));
                    builder.AddLine(new Vector2(24.4099998F, 19.3600006F));
                    builder.AddLine(new Vector2(24.5900002F, 18.7700005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_21 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: folder-01 Offset:<0, 22.200005>
            // - ++++++++++++.PathGeometry
            CanvasGeometry Geometry_22()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_23(), Geometry_05(), Geometry_06(), Geometry_07(), Geometry_24(), Geometry_25(), Geometry_26(), Geometry_09(), Geometry_10(), Geometry_11(), Geometry_21(), Geometry_27(), Geometry_14() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-01 Offset:<0, 22.200005>
            // - - ++++++++++++.PathGeometry
            CanvasGeometry Geometry_23()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, 28.5F));
                    builder.AddLine(new Vector2(0.629999995F, 28.5F));
                    builder.AddLine(new Vector2(0.629999995F, 6.01000023F));
                    builder.AddLine(new Vector2(0F, 6.01000023F));
                    builder.AddLine(new Vector2(-0.620000005F, 6.01000023F));
                    builder.AddLine(new Vector2(-0.620000005F, 28.5F));
                    builder.AddLine(new Vector2(0F, 28.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-01 Offset:<0, 22.200005>
            // - - ++++++++++++.PathGeometry
            CanvasGeometry Geometry_24()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(71.8099976F, 33.6800003F));
                    builder.AddLine(new Vector2(72F, 33.0800018F));
                    builder.AddLine(new Vector2(24.7800007F, 18.1700001F));
                    builder.AddLine(new Vector2(24.5900002F, 18.7700005F));
                    builder.AddLine(new Vector2(24.4099998F, 19.3600006F));
                    builder.AddLine(new Vector2(71.6200027F, 34.2700005F));
                    builder.AddLine(new Vector2(71.8099976F, 33.6800003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-01 Offset:<0, 22.200005>
            // - - ++++++++++++.PathGeometry
            CanvasGeometry Geometry_25()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(76F, 39.4000015F));
                    builder.AddLine(new Vector2(76.6299973F, 39.4000015F));
                    builder.AddCubicBezier(new Vector2(76.6299973F, 36.5099983F), new Vector2(74.7600021F, 33.9500008F), new Vector2(72F, 33.0800018F));
                    builder.AddLine(new Vector2(71.8099976F, 33.6800003F));
                    builder.AddLine(new Vector2(71.6200027F, 34.2700005F));
                    builder.AddCubicBezier(new Vector2(73.8600006F, 34.9799995F), new Vector2(75.3799973F, 37.0600014F), new Vector2(75.3799973F, 39.4000015F));
                    builder.AddLine(new Vector2(76F, 39.4000015F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-01 Offset:<0, 22.200005>
            // - - ++++++++++++.PathGeometry
            CanvasGeometry Geometry_26()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(76F, 90.8099976F));
                    builder.AddLine(new Vector2(76.6299973F, 90.8099976F));
                    builder.AddLine(new Vector2(76.6299973F, 39.4000015F));
                    builder.AddLine(new Vector2(76F, 39.4000015F));
                    builder.AddLine(new Vector2(75.3799973F, 39.4000015F));
                    builder.AddLine(new Vector2(75.3799973F, 90.8099976F));
                    builder.AddLine(new Vector2(76F, 90.8099976F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: folder-01 Offset:<0, 22.200005>
            // - - ++++++++++++.PathGeometry
            CanvasGeometry Geometry_27()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(71.8099976F, 33.6800003F));
                    builder.AddLine(new Vector2(72F, 33.0800018F));
                    builder.AddLine(new Vector2(71.8099976F, 33.6800003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: folder-01 Offset:<0, 22.200005>
            CanvasGeometry Geometry_28()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(5.36000013F, 12.0100002F));
                    builder.AddCubicBezier(new Vector2(3.25999999F, 7.30999994F), new Vector2(7.65999985F, 2.32999992F), new Vector2(12.5799999F, 3.81999993F));
                    builder.AddLine(new Vector2(77.3899994F, 23.4799995F));
                    builder.AddCubicBezier(new Vector2(79.0500031F, 23.9799995F), new Vector2(80.4100037F, 25.1900005F), new Vector2(81.1200027F, 26.7700005F));
                    builder.AddLine(new Vector2(99.4700012F, 67.6699982F));
                    builder.AddCubicBezier(new Vector2(101.599998F, 72.4199982F), new Vector2(97.0899963F, 77.4400024F), new Vector2(92.1399994F, 75.8300018F));
                    builder.AddLine(new Vector2(26.5400009F, 54.5499992F));
                    builder.AddCubicBezier(new Vector2(24.9200001F, 54.0299988F), new Vector2(23.6000004F, 52.8400002F), new Vector2(22.9099998F, 51.2900009F));
                    builder.AddLine(new Vector2(5.36000013F, 12.0100002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: fond Offset:<0.63000107, 0.63000107>
            CanvasGeometry Geometry_29()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(70.75F, 35.375F));
                    builder.AddCubicBezier(new Vector2(70.75F, 54.9099998F), new Vector2(54.9099998F, 70.75F), new Vector2(35.375F, 70.75F));
                    builder.AddCubicBezier(new Vector2(15.8400002F, 70.75F), new Vector2(0F, 54.9099998F), new Vector2(0F, 35.375F));
                    builder.AddCubicBezier(new Vector2(0F, 15.8400002F), new Vector2(15.8400002F, 0F), new Vector2(35.375F, 0F));
                    builder.AddCubicBezier(new Vector2(54.9099998F, 0F), new Vector2(70.75F, 15.8400002F), new Vector2(70.75F, 35.375F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Transforms: icon
            // - Path
            CanvasGeometry Geometry_30()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2.50999999F, 0.870000005F));
                    builder.AddCubicBezier(new Vector2(2.5F, 0.860000014F), new Vector2(2.50999999F, 0.870000005F), new Vector2(2.50999999F, 0.870000005F));
                    builder.AddCubicBezier(new Vector2(2.5F, 0.860000014F), new Vector2(2.49000001F, 0.839999974F), new Vector2(2.48000002F, 0.829999983F));
                    builder.AddCubicBezier(new Vector2(2.48000002F, 0.829999983F), new Vector2(2.49000001F, 0.839999974F), new Vector2(2.48000002F, 0.829999983F));
                    builder.AddCubicBezier(new Vector2(2.48000002F, 0.829999983F), new Vector2(2.58999991F, 0.939999998F), new Vector2(2.58999991F, 0.939999998F));
                    builder.AddCubicBezier(new Vector2(2.68000007F, 1.00999999F), new Vector2(2.58999991F, 0.939999998F), new Vector2(2.58999991F, 0.939999998F));
                    builder.AddCubicBezier(new Vector2(2.68000007F, 1.00999999F), new Vector2(2.75999999F, 1.08000004F), new Vector2(2.79999995F, 1.13F));
                    builder.AddCubicBezier(new Vector2(2.79999995F, 1.13F), new Vector2(2.81999993F, 1.13999999F), new Vector2(2.81999993F, 1.13999999F));
                    builder.AddCubicBezier(new Vector2(2.81999993F, 1.13999999F), new Vector2(2.58999991F, 0.939999998F), new Vector2(2.58999991F, 0.939999998F));
                    builder.AddCubicBezier(new Vector2(2.55999994F, 0.920000017F), new Vector2(2.53999996F, 0.889999986F), new Vector2(2.50999999F, 0.870000005F));
                    builder.AddCubicBezier(new Vector2(2.8599999F, 1.38999999F), new Vector2(2.73000002F, 2.1099999F), new Vector2(2.22000003F, 2.48000002F));
                    builder.AddCubicBezier(new Vector2(1.69000006F, 2.8599999F), new Vector2(0.959999979F, 2.75999999F), new Vector2(0.569999993F, 2.23000002F));
                    builder.AddCubicBezier(new Vector2(0.569999993F, 2.23000002F), new Vector2(0.469999999F, 2.08999991F), new Vector2(0.469999999F, 2.08999991F));
                    builder.AddCubicBezier(new Vector2(0.389999986F, 1.98000002F), new Vector2(0.289999992F, 1.84000003F), new Vector2(0.180000007F, 1.66999996F));
                    builder.AddCubicBezier(new Vector2(0.170000002F, 1.65999997F), new Vector2(0.170000002F, 1.65999997F), new Vector2(0.159999996F, 1.64999998F));
                    builder.AddCubicBezier(new Vector2(0.159999996F, 1.64999998F), new Vector2(0.200000003F, 1.84000003F), new Vector2(0.200000003F, 1.84000003F));
                    builder.AddCubicBezier(new Vector2(-0.170000002F, 1.29999995F), new Vector2(-0.0199999996F, 0.569999993F), new Vector2(0.519999981F, 0.200000003F));
                    builder.AddCubicBezier(new Vector2(1.05999994F, -0.159999996F), new Vector2(1.79999995F, -0.0199999996F), new Vector2(2.16000009F, 0.519999981F));
                    builder.AddCubicBezier(new Vector2(2.16000009F, 0.519999981F), new Vector2(2.28999996F, 0.730000019F), new Vector2(2.28999996F, 0.730000019F));
                    builder.AddCubicBezier(new Vector2(2.3599999F, 0.779999971F), new Vector2(2.44000006F, 0.819999993F), new Vector2(2.50999999F, 0.870000005F));
                    builder.AddCubicBezier(new Vector2(2.50999999F, 0.870000005F), new Vector2(2.50999999F, 0.870000005F), new Vector2(2.50999999F, 0.870000005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Transforms: icon
            // - Path
            CanvasGeometry Geometry_31()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(12.8800001F, 9.25F));
                    builder.AddCubicBezier(new Vector2(12.3599997F, 8.85999966F), new Vector2(11.6099997F, 8.96000004F), new Vector2(11.2200003F, 9.47999954F));
                    builder.AddCubicBezier(new Vector2(11.2200003F, 9.47999954F), new Vector2(10.8900003F, 9.90999985F), new Vector2(10.8900003F, 9.90999985F));
                    builder.AddCubicBezier(new Vector2(10.8900003F, 9.90999985F), new Vector2(10.8800001F, 9.93000031F), new Vector2(10.8800001F, 9.93000031F));
                    builder.AddCubicBezier(new Vector2(10.7299995F, 10.1400003F), new Vector2(10.5299997F, 10.29F), new Vector2(10.3199997F, 10.3999996F));
                    builder.AddCubicBezier(new Vector2(10.1099997F, 10.5100002F), new Vector2(9.88000011F, 10.5600004F), new Vector2(9.64999962F, 10.5500002F));
                    builder.AddCubicBezier(new Vector2(9.42000008F, 10.54F), new Vector2(9.18999958F, 10.4799995F), new Vector2(8.97999954F, 10.3599997F));
                    builder.AddCubicBezier(new Vector2(8.77000046F, 10.2399998F), new Vector2(8.60000038F, 10.0699997F), new Vector2(8.46000004F, 9.85000038F));
                    builder.AddCubicBezier(new Vector2(8.46000004F, 9.85000038F), new Vector2(8.43999958F, 9.82999992F), new Vector2(8.43999958F, 9.82999992F));
                    builder.AddCubicBezier(new Vector2(8.43999958F, 9.82999992F), new Vector2(2.16000009F, 0.519999981F), new Vector2(2.16000009F, 0.519999981F));
                    builder.AddCubicBezier(new Vector2(1.79999995F, -0.0199999996F), new Vector2(1.05999994F, -0.159999996F), new Vector2(0.519999981F, 0.200000003F));
                    builder.AddCubicBezier(new Vector2(-0.0199999996F, 0.569999993F), new Vector2(-0.170000002F, 1.29999995F), new Vector2(0.200000003F, 1.84000003F));
                    builder.AddCubicBezier(new Vector2(0.200000003F, 1.84000003F), new Vector2(6.48000002F, 11.1499996F), new Vector2(6.48000002F, 11.1499996F));
                    builder.AddCubicBezier(new Vector2(6.82000017F, 11.6700001F), new Vector2(7.26999998F, 12.1000004F), new Vector2(7.80000019F, 12.4099998F));
                    builder.AddCubicBezier(new Vector2(8.34000015F, 12.7200003F), new Vector2(8.96000004F, 12.8900003F), new Vector2(9.57999992F, 12.9099998F));
                    builder.AddCubicBezier(new Vector2(10.1999998F, 12.9300003F), new Vector2(10.8199997F, 12.8000002F), new Vector2(11.3800001F, 12.5200005F));
                    builder.AddCubicBezier(new Vector2(11.9300003F, 12.2399998F), new Vector2(12.3999996F, 11.8400002F), new Vector2(12.7700005F, 11.3400002F));
                    builder.AddCubicBezier(new Vector2(12.7700005F, 11.3400002F), new Vector2(12.7799997F, 11.3400002F), new Vector2(12.7799997F, 11.3400002F));
                    builder.AddCubicBezier(new Vector2(12.7799997F, 11.3400002F), new Vector2(13.1099997F, 10.9099998F), new Vector2(13.1099997F, 10.9099998F));
                    builder.AddCubicBezier(new Vector2(13.5F, 10.3900003F), new Vector2(13.3999996F, 9.64000034F), new Vector2(12.8800001F, 9.25F));
                    builder.AddCubicBezier(new Vector2(12.8800001F, 9.25F), new Vector2(12.8800001F, 9.25F), new Vector2(12.8800001F, 9.25F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Transforms: icon
            // - Path
            CanvasGeometry Geometry_32()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(32.6399994F, 0.239999995F));
                    builder.AddCubicBezier(new Vector2(32.1199989F, -0.150000006F), new Vector2(31.3799992F, -0.0500000007F), new Vector2(30.9899998F, 0.469999999F));
                    builder.AddCubicBezier(new Vector2(30.9899998F, 0.469999999F), new Vector2(10.8900003F, 27.0300007F), new Vector2(10.8900003F, 27.0300007F));
                    builder.AddCubicBezier(new Vector2(10.8900003F, 27.0300007F), new Vector2(10.8800001F, 27.0499992F), new Vector2(10.8800001F, 27.0499992F));
                    builder.AddCubicBezier(new Vector2(10.7299995F, 27.2600002F), new Vector2(10.5299997F, 27.4099998F), new Vector2(10.3199997F, 27.5200005F));
                    builder.AddCubicBezier(new Vector2(10.1099997F, 27.6299992F), new Vector2(9.88000011F, 27.6800003F), new Vector2(9.64999962F, 27.6700001F));
                    builder.AddCubicBezier(new Vector2(9.42000008F, 27.6599998F), new Vector2(9.18999958F, 27.6000004F), new Vector2(8.97999954F, 27.4799995F));
                    builder.AddCubicBezier(new Vector2(8.77000046F, 27.3600006F), new Vector2(8.60000038F, 27.1900005F), new Vector2(8.46000004F, 26.9699993F));
                    builder.AddCubicBezier(new Vector2(8.46000004F, 26.9699993F), new Vector2(8.43999958F, 26.9400005F), new Vector2(8.43999958F, 26.9400005F));
                    builder.AddCubicBezier(new Vector2(8.43999958F, 26.9400005F), new Vector2(2.16000009F, 17.6399994F), new Vector2(2.16000009F, 17.6399994F));
                    builder.AddCubicBezier(new Vector2(1.79999995F, 17.1000004F), new Vector2(1.05999994F, 16.9599991F), new Vector2(0.519999981F, 17.3199997F));
                    builder.AddCubicBezier(new Vector2(-0.0199999996F, 17.6900005F), new Vector2(-0.170000002F, 18.4200001F), new Vector2(0.200000003F, 18.9599991F));
                    builder.AddCubicBezier(new Vector2(0.200000003F, 18.9599991F), new Vector2(6.48000002F, 28.2600002F), new Vector2(6.48000002F, 28.2600002F));
                    builder.AddCubicBezier(new Vector2(6.82000017F, 28.7800007F), new Vector2(7.26999998F, 29.2099991F), new Vector2(7.80000019F, 29.5200005F));
                    builder.AddCubicBezier(new Vector2(8.34000015F, 29.8299999F), new Vector2(8.96000004F, 30.0100002F), new Vector2(9.57999992F, 30.0300007F));
                    builder.AddCubicBezier(new Vector2(10.1999998F, 30.0499992F), new Vector2(10.8199997F, 29.9200001F), new Vector2(11.3800001F, 29.6399994F));
                    builder.AddCubicBezier(new Vector2(11.9300003F, 29.3600006F), new Vector2(12.3999996F, 28.9500008F), new Vector2(12.7700005F, 28.4500008F));
                    builder.AddCubicBezier(new Vector2(12.7700005F, 28.4500008F), new Vector2(12.7799997F, 28.4599991F), new Vector2(12.7799997F, 28.4599991F));
                    builder.AddCubicBezier(new Vector2(12.7799997F, 28.4599991F), new Vector2(32.8800011F, 1.89999998F), new Vector2(32.8800011F, 1.89999998F));
                    builder.AddCubicBezier(new Vector2(33.2700005F, 1.38F), new Vector2(33.1599998F, 0.629999995F), new Vector2(32.6399994F, 0.239999995F));
                    builder.AddCubicBezier(new Vector2(32.6399994F, 0.239999995F), new Vector2(32.6399994F, 0.239999995F), new Vector2(32.6399994F, 0.239999995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Color bound to theme property value: Color_446EDD
            CompositionColorBrush ThemeColor_Color_446EDD_0()
            {
                if (_themeColor_Color_446EDD_0 != null) { return _themeColor_Color_446EDD_0; }
                var result = _themeColor_Color_446EDD_0 = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_446EDD_0, "Color", "ColorRGB(_theme.Color_446EDD.W,_theme.Color_446EDD.X,_theme.Color_446EDD.Y,_theme.Color_446EDD.Z)", "_theme", _themeProperties);
                return result;
            }

            // - Transforms: icon
            // Color bound to theme property value: Color_446EDD
            CompositionColorBrush ThemeColor_Color_446EDD_1()
            {
                if (_themeColor_Color_446EDD_1 != null) { return _themeColor_Color_446EDD_1; }
                var result = _themeColor_Color_446EDD_1 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                BindProperty2(_themeColor_Color_446EDD_1, "Color", "ColorRGB(_theme.Color_446EDD.W*my.Opacity0,_theme.Color_446EDD.X,_theme.Color_446EDD.Y,_theme.Color_446EDD.Z)", "_theme", _themeProperties, "my", propertySet);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // Transforms: folder-03 Offset:<54.11, 0>
                shapes.Add(SpriteShape_0());
                // Transforms: folder-02 Offset:<39.11, 12>
                shapes.Add(SpriteShape_1());
                // Transforms: folder-01 Offset:<0, 22.200005>
                shapes.Add(SpriteShape_2());
                // Transforms: folder-01 Offset:<0, 22.200005>
                shapes.Add(SpriteShape_3());
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // Transforms: fond Offset:<0.63000107, 0.63000107>
                shapes.Add(SpriteShape_4());
                // Transforms: icon
                shapes.Add(ContainerShape_2());
                return result;
            }

            // Transforms for icon
            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(1.40999997F, 1.35000002F));
                propertySet.InsertVector2("Position", new Vector2(20.7700005F, 39.3699989F));
                result.Shapes.Add(SpriteShape_5());
                BindProperty(_containerShape_2, "CenterPoint", "my.Anchor", "my", _containerShape_2);
                BindProperty(_containerShape_2, "Offset", "my.Position-my.Anchor", "my", _containerShape_2);
                return result;
            }

            // - - Layer aggregator
            // Transforms: folder-03 Offset:<54.11, 0>
            // +++++++++++++.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
            }

            // - - Layer aggregator
            // Transforms: folder-02 Offset:<39.11, 12>
            // +++++++++++++++.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_15()));
            }

            // - - Layer aggregator
            // Transforms: folder-01 Offset:<0, 22.200005>
            // ++++++++++++.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_22()));
            }

            // - - Layer aggregator
            // Transforms: folder-01 Offset:<0, 22.200005>
            CompositionPathGeometry PathGeometry_3()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_28()));
            }

            // - - Layer aggregator
            // Transforms: fond Offset:<0.63000107, 0.63000107>
            CompositionPathGeometry PathGeometry_4()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_29()));
            }

            // - Transforms: icon
            CompositionPathGeometry PathGeometry_5()
            {
                if (_pathGeometry_5 != null) { return _pathGeometry_5; }
                var result = _pathGeometry_5 = _c.CreatePathGeometry();
                return result;
            }

            // - Layer aggregator
            // +++++++++++++
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<54.11, 0>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 54.1100006F, 0F), ThemeColor_Color_446EDD_0());;
                return result;
            }

            // - Layer aggregator
            // +++++++++++++++
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<39.11, 12>
                var geometry = PathGeometry_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 39.1100006F, 12F), ThemeColor_Color_446EDD_0());;
                return result;
            }

            // - Layer aggregator
            // ++++++++++++
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<24.029999, 22.200005>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 24.0299988F, 22.2000046F), ThemeColor_Color_446EDD_0());;
                return result;
            }

            // - Layer aggregator
            // Transforms for page-front Offset:<0, 21.2>
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<0, 43.400005>
                if (_spriteShape_3 != null) { return _spriteShape_3; }
                var result = _spriteShape_3 = CreateSpriteShape(PathGeometry_3(), new Matrix3x2(1F, 0F, 0F, 1F, 0F, 43.4000053F));;
                result.StrokeBrush = ThemeColor_Color_446EDD_0();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                return result;
            }

            // - Layer aggregator
            // Transforms for fond Offset:<0.63000107, 0.63000107>
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<0.63000107, 0.63000107>
                if (_spriteShape_4 != null) { return _spriteShape_4; }
                var result = _spriteShape_4 = CreateSpriteShape(PathGeometry_4(), new Matrix3x2(1F, 0F, 0F, 1F, 0.630001068F, 0.630001068F));;
                result.StrokeBrush = ThemeColor_Color_446EDD_0();
                result.StrokeMiterLimit = 2F;
                return result;
            }

            // Transforms: icon
            CompositionSpriteShape SpriteShape_5()
            {
                var result = _c.CreateSpriteShape(PathGeometry_5());
                result.FillBrush = ThemeColor_Color_446EDD_1();
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.319999993F, 0F), new Vector2(0.670000017F, 0F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.330000013F, 1F), new Vector2(0.680000007F, 1F))
                    : _cubicBezierEasingFunction_1;
            }

            // - - Transforms: icon
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, new CompositionPath(Geometry_30()), HoldThenStepEasingFunction());
                // Frame 24.
                result.InsertKeyFrame(0.165380374F, new CompositionPath(Geometry_31()), CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.372105837F, new CompositionPath(Geometry_32()), CubicBezierEasingFunction_1());
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 24.
                result.InsertKeyFrame(0.165380374F, 1F, CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.372105837F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // StrokeThickness
            ScalarKeyFrameAnimation StrokeThicknessScalarAnimation_1p25_to_1p25()
            {
                // Frame 0.
                if (_strokeThicknessScalarAnimation_1p25_to_1p25 != null) { return _strokeThicknessScalarAnimation_1p25_to_1p25; }
                var result = _strokeThicknessScalarAnimation_1p25_to_1p25 = CreateScalarKeyFrameAnimation(0F, 1.25F, HoldThenStepEasingFunction());
                // Frame 24.
                result.InsertKeyFrame(0.165380374F, 1.25F, CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.372105837F, 1.25F, CubicBezierEasingFunction_1());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(178F, 131F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_0());
                shapes.Add(ContainerShape_1());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // - Transforms: icon
            // Anchor
            Vector2KeyFrameAnimation AnchorVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.40999997F, 1.35000002F), HoldThenStepEasingFunction());
                // Frame 24.
                result.InsertKeyFrame(0.165380374F, new Vector2(6.67000008F, 6.46000004F), CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.372105837F, new Vector2(16.5599995F, 15.0200005F), CubicBezierEasingFunction_1());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.180000007F, 8F), HoldThenStepEasingFunction());
                // Frame 24.
                result.InsertKeyFrame(0.165380374F, new Vector2(0.180000007F, 8F), CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.372105837F, new Vector2(0.0500000007F, 8F), CubicBezierEasingFunction_1());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(98.0400009F, 8F), HoldThenStepEasingFunction());
                // Frame 24.
                result.InsertKeyFrame(0.165380374F, new Vector2(97.9100037F, 8F), CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.372105837F, new Vector2(97.9599991F, 8F), CubicBezierEasingFunction_1());
                return result;
            }

            // - Transforms: icon
            // Position
            Vector2KeyFrameAnimation PositionVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(20.7700005F, 39.3699989F), HoldThenStepEasingFunction());
                // Frame 24.
                result.InsertKeyFrame(0.165380374F, new Vector2(26.0400009F, 44.4799995F), CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.372105837F, new Vector2(35.9199982F, 35.9199982F), CubicBezierEasingFunction_1());
                return result;
            }

            internal KDrive_Check_AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(178F, 131F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _themeColor_Color_446EDD_1.Properties.StartAnimation("Opacity0", Opacity0ScalarAnimation_0_to_1(), AnimationController_0());
                _containerShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _containerShape_1.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
                _containerShape_2.Properties.StartAnimation("Anchor", AnchorVector2Animation(), AnimationController_0());
                _containerShape_2.Properties.StartAnimation("Position", PositionVector2Animation(), AnimationController_0());
                _pathGeometry_5.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _spriteShape_3.StartAnimation("StrokeThickness", StrokeThicknessScalarAnimation_1p25_to_1p25(), AnimationController_0());
                _spriteShape_4.StartAnimation("StrokeThickness", StrokeThicknessScalarAnimation_1p25_to_1p25(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _themeColor_Color_446EDD_1.Properties.StopAnimation("Opacity0");
                _containerShape_0.StopAnimation("Offset");
                _containerShape_1.StopAnimation("Offset");
                _containerShape_2.Properties.StopAnimation("Anchor");
                _containerShape_2.Properties.StopAnimation("Position");
                _pathGeometry_5.StopAnimation("Path");
                _spriteShape_3.StopAnimation("StrokeThickness");
                _spriteShape_4.StopAnimation("StrokeThickness");
            }

        }
    }
}
