//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -GenerateColorBindings -GenerateDependencyObject -Language CSharp -Public -WinUIVersion 3.0 -InputFile kDrive-Sync.json
//       
//       Input file:
//           kDrive-Sync.json (18732 bytes created 14:58+02:00 May 27 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    57 |
// |--------------------------+-------|
// | Expression animators     |     6 |
// | KeyFrame animators       |    10 |
// | Reference parameters     |     6 |
// | Expression operations    |     4 |
// |--------------------------+-------|
// | Animated brushes         |     1 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     6 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     3 |
// | CompositionSpriteShapes  |     3 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Name:        kDrive-Sync-LIGHT
    // Frame rate:  60 fps
    // Frame count: 601.18
    // Duration:    10019.7 mS
    sealed class KDrive_Sync
        : DependencyObject
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 10.020 seconds.
        internal const long c_durationTicks = 100196666;

        // Theme property: Color_446EDD.
        internal static readonly Color c_themeColor_446EDD = Color.FromArgb(0xFF, 0x44, 0x6E, 0xDD);

        CompositionPropertySet _themeProperties;

        /// <summary>
        /// Dependency property for Color_446EDD.
        /// </summary>
        public static readonly DependencyProperty Color_446EDDProperty =
            DependencyProperty.Register("Color_446EDD", typeof(Color), typeof(KDrive_Sync),
                new PropertyMetadata(Color.FromArgb(0xFF, 0x44, 0x6E, 0xDD), OnColor_446EDDChanged));

        // Theme properties.
        public Color Color_446EDD
        {
            get => (Color)GetValue(Color_446EDDProperty);
            set => SetValue(Color_446EDDProperty, value);
        }

        static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        static void OnColor_446EDDChanged(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((KDrive_Sync)d)._themeProperties?.InsertVector4("Color_446EDD", ColorAsVector4((Color)(Color)args.NewValue));
        }

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties == null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Color_446EDD", ColorAsVector4((Color)Color_446EDD));
            }
            return _themeProperties;
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            var res = 
                new KDrive_Sync_AnimatedVisual(
                    compositor,
                    _themeProperties
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 601.18;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(100196666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 601.18;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
            if (propertyName == "Color_446EDD")
            {
                Color_446EDD = value;
            }
            else
            {
                return;
            }

            if (_themeProperties != null)
            {
                _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
            }
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class KDrive_Sync_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 100196666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            AnimationController _animationController_0;
            CompositionColorBrush _themeColor_Color_446EDD;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            ScalarKeyFrameAnimation _rotationAngleInDegreesScalarAnimation_0_to_m360;
            StepEasingFunction _holdThenStepEasingFunction;
            Vector2KeyFrameAnimation _anchorVector2Animation;
            Vector2KeyFrameAnimation _positionVector2Animation;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Layer aggregator
            // - - ++++++++++++++++++++++++++++++++++
            // - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_00()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_01(), Geometry_02(), Geometry_03(), Geometry_04(), Geometry_05(), Geometry_06(), Geometry_07(), Geometry_08(), Geometry_09(), Geometry_10(), Geometry_11(), Geometry_12(), Geometry_13(), Geometry_14(), Geometry_15(), Geometry_16(), Geometry_17(), Geometry_18(), Geometry_19(), Geometry_20(), Geometry_21(), Geometry_22(), Geometry_23(), Geometry_24(), Geometry_25(), Geometry_26(), Geometry_27(), Geometry_28(), Geometry_29(), Geometry_30(), Geometry_31(), Geometry_32(), Geometry_33(), Geometry_34(), Geometry_35() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(106.470001F, 0F));
                    builder.AddCubicBezier(new Vector2(107.43F, 0F), new Vector2(108.389999F, 0.0299999993F), new Vector2(109.330002F, 0.100000001F));
                    builder.AddCubicBezier(new Vector2(109.669998F, 0.129999995F), new Vector2(109.93F, 0.430000007F), new Vector2(109.910004F, 0.769999981F));
                    builder.AddCubicBezier(new Vector2(109.879997F, 1.11000001F), new Vector2(109.580002F, 1.37F), new Vector2(109.239998F, 1.35000002F));
                    builder.AddCubicBezier(new Vector2(108.330002F, 1.27999997F), new Vector2(107.400002F, 1.25F), new Vector2(106.470001F, 1.25F));
                    builder.AddCubicBezier(new Vector2(105.510002F, 1.25F), new Vector2(104.550003F, 1.28999996F), new Vector2(103.610001F, 1.36000001F));
                    builder.AddCubicBezier(new Vector2(103.269997F, 1.38999999F), new Vector2(102.970001F, 1.12F), new Vector2(102.940002F, 0.779999971F));
                    builder.AddCubicBezier(new Vector2(102.919998F, 0.439999998F), new Vector2(103.18F, 0.140000001F), new Vector2(103.519997F, 0.109999999F));
                    builder.AddCubicBezier(new Vector2(104.489998F, 0.0399999991F), new Vector2(105.480003F, 0F), new Vector2(106.470001F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(114.989998F, 0.939999998F));
                    builder.AddCubicBezier(new Vector2(116.870003F, 1.36000001F), new Vector2(118.699997F, 1.92999995F), new Vector2(120.470001F, 2.6099999F));
                    builder.AddCubicBezier(new Vector2(120.790001F, 2.73000002F), new Vector2(120.949997F, 3.08999991F), new Vector2(120.82F, 3.41000009F));
                    builder.AddCubicBezier(new Vector2(120.699997F, 3.73000002F), new Vector2(120.330002F, 3.8900001F), new Vector2(120.010002F, 3.76999998F));
                    builder.AddCubicBezier(new Vector2(118.300003F, 3.1099999F), new Vector2(116.540001F, 2.56999993F), new Vector2(114.720001F, 2.16000009F));
                    builder.AddCubicBezier(new Vector2(114.379997F, 2.07999992F), new Vector2(114.160004F, 1.75F), new Vector2(114.239998F, 1.40999997F));
                    builder.AddCubicBezier(new Vector2(114.32F, 1.07000005F), new Vector2(114.650002F, 0.860000014F), new Vector2(114.989998F, 0.939999998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(97.6800003F, 1F));
                    builder.AddCubicBezier(new Vector2(98.0199966F, 0.920000017F), new Vector2(98.3499985F, 1.13F), new Vector2(98.4300003F, 1.47000003F));
                    builder.AddLine(new Vector2(98.4499969F, 1.59000003F));
                    builder.AddCubicBezier(new Vector2(98.4599991F, 1.88F), new Vector2(98.25F, 2.1500001F), new Vector2(97.9599991F, 2.22000003F));
                    builder.AddCubicBezier(new Vector2(96.0899963F, 2.6500001F), new Vector2(94.2699966F, 3.23000002F), new Vector2(92.5199966F, 3.93000007F));
                    builder.AddCubicBezier(new Vector2(92.1999969F, 4.05999994F), new Vector2(91.8300018F, 3.91000009F), new Vector2(91.6999969F, 3.58999991F));
                    builder.AddCubicBezier(new Vector2(91.5699997F, 3.26999998F), new Vector2(91.7300034F, 2.9000001F), new Vector2(92.0500031F, 2.76999998F));
                    builder.AddCubicBezier(new Vector2(93.8600006F, 2.03999996F), new Vector2(95.7399979F, 1.45000005F), new Vector2(97.6800003F, 1F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(124.779999F, 5.30000019F));
                    builder.AddCubicBezier(new Vector2(124.949997F, 5F), new Vector2(125.330002F, 4.88999987F), new Vector2(125.629997F, 5.05999994F));
                    builder.AddCubicBezier(new Vector2(127.290001F, 6.01000023F), new Vector2(128.880005F, 7.07999992F), new Vector2(130.380005F, 8.26000023F));
                    builder.AddCubicBezier(new Vector2(130.649994F, 8.47000027F), new Vector2(130.690002F, 8.85999966F), new Vector2(130.479996F, 9.13000011F));
                    builder.AddCubicBezier(new Vector2(130.270004F, 9.39999962F), new Vector2(129.869995F, 9.44999981F), new Vector2(129.600006F, 9.23999977F));
                    builder.AddCubicBezier(new Vector2(128.149994F, 8.10000038F), new Vector2(126.620003F, 7.07000017F), new Vector2(125.010002F, 6.1500001F));
                    builder.AddCubicBezier(new Vector2(124.709999F, 5.98000002F), new Vector2(124.610001F, 5.5999999F), new Vector2(124.779999F, 5.30000019F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(86.75F, 5.38999987F));
                    builder.AddCubicBezier(new Vector2(87.0500031F, 5.21000004F), new Vector2(87.4300003F, 5.30999994F), new Vector2(87.6100006F, 5.61000013F));
                    builder.AddCubicBezier(new Vector2(87.7900009F, 5.90999985F), new Vector2(87.6900024F, 6.28000021F), new Vector2(87.3899994F, 6.46000004F));
                    builder.AddCubicBezier(new Vector2(85.75F, 7.42999983F), new Vector2(84.1800003F, 8.52999973F), new Vector2(82.7099991F, 9.73999977F));
                    builder.AddCubicBezier(new Vector2(82.4800034F, 9.93000031F), new Vector2(82.1500015F, 9.92000008F), new Vector2(81.9199982F, 9.73999977F));
                    builder.AddLine(new Vector2(81.8300018F, 9.64999962F));
                    builder.AddCubicBezier(new Vector2(81.6100006F, 9.38000011F), new Vector2(81.6500015F, 8.98999977F), new Vector2(81.9199982F, 8.77000046F));
                    builder.AddCubicBezier(new Vector2(83.4400024F, 7.51999998F), new Vector2(85.0500031F, 6.4000001F), new Vector2(86.75F, 5.38999987F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(133.720001F, 12.0900002F));
                    builder.AddCubicBezier(new Vector2(133.970001F, 11.8500004F), new Vector2(134.360001F, 11.8599997F), new Vector2(134.600006F, 12.1099997F));
                    builder.AddCubicBezier(new Vector2(135.910004F, 13.4899998F), new Vector2(137.130005F, 14.9700003F), new Vector2(138.229996F, 16.5400009F));
                    builder.AddCubicBezier(new Vector2(138.429993F, 16.8199997F), new Vector2(138.350006F, 17.2099991F), new Vector2(138.070007F, 17.4099998F));
                    builder.AddCubicBezier(new Vector2(137.789993F, 17.6100006F), new Vector2(137.399994F, 17.5400009F), new Vector2(137.199997F, 17.2600002F));
                    builder.AddCubicBezier(new Vector2(136.139999F, 15.75F), new Vector2(134.970001F, 14.3100004F), new Vector2(133.699997F, 12.9700003F));
                    builder.AddCubicBezier(new Vector2(133.460007F, 12.7200003F), new Vector2(133.470001F, 12.3299999F), new Vector2(133.720001F, 12.0900002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(77.6500015F, 12.8500004F));
                    builder.AddCubicBezier(new Vector2(77.8799973F, 12.5900002F), new Vector2(78.2699966F, 12.5699997F), new Vector2(78.5299988F, 12.8000002F));
                    builder.AddCubicBezier(new Vector2(78.7900009F, 13.0299997F), new Vector2(78.8099976F, 13.4300003F), new Vector2(78.5800018F, 13.6899996F));
                    builder.AddCubicBezier(new Vector2(77.3099976F, 15.1099997F), new Vector2(76.1399994F, 16.6100006F), new Vector2(75.0899963F, 18.2099991F));
                    builder.AddCubicBezier(new Vector2(74.9199982F, 18.4599991F), new Vector2(74.6100006F, 18.5599995F), new Vector2(74.3399963F, 18.4500008F));
                    builder.AddLine(new Vector2(74.2300034F, 18.3899994F));
                    builder.AddCubicBezier(new Vector2(73.9400024F, 18.2000008F), new Vector2(73.8600006F, 17.8199997F), new Vector2(74.0500031F, 17.5300007F));
                    builder.AddLine(new Vector2(74.4599991F, 16.9099998F));
                    builder.AddCubicBezier(new Vector2(75.4300003F, 15.4899998F), new Vector2(76.5F, 14.1300001F), new Vector2(77.6500015F, 12.8500004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(140.320007F, 21.1700001F));
                    builder.AddCubicBezier(new Vector2(140.630005F, 21.0200005F), new Vector2(141.009995F, 21.1399994F), new Vector2(141.160004F, 21.4500008F));
                    builder.AddCubicBezier(new Vector2(141.529999F, 22.1900005F), new Vector2(141.880005F, 22.9500008F), new Vector2(142.199997F, 23.7199993F));
                    builder.AddCubicBezier(new Vector2(143.050003F, 23.8299999F), new Vector2(143.889999F, 23.9500008F), new Vector2(144.720001F, 24.1100006F));
                    builder.AddCubicBezier(new Vector2(145.059998F, 24.1700001F), new Vector2(145.279999F, 24.5F), new Vector2(145.220001F, 24.8400002F));
                    builder.AddCubicBezier(new Vector2(145.160004F, 25.1800003F), new Vector2(144.820007F, 25.3999996F), new Vector2(144.479996F, 25.3400002F));
                    builder.AddCubicBezier(new Vector2(143.559998F, 25.1700001F), new Vector2(142.630005F, 25.0300007F), new Vector2(141.690002F, 24.9200001F));
                    builder.AddLine(new Vector2(141.399994F, 24.8799992F));
                    builder.AddLine(new Vector2(141.320007F, 24.8700008F));
                    builder.AddLine(new Vector2(141.300003F, 24.8099995F));
                    builder.AddLine(new Vector2(141.190002F, 24.5300007F));
                    builder.AddCubicBezier(new Vector2(140.839996F, 23.6700001F), new Vector2(140.449997F, 22.8299999F), new Vector2(140.039993F, 22.0100002F));
                    builder.AddCubicBezier(new Vector2(139.889999F, 21.7000008F), new Vector2(140.009995F, 21.3199997F), new Vector2(140.320007F, 21.1700001F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(65.8600006F, 24.6599998F));
                    builder.AddCubicBezier(new Vector2(66.2699966F, 24.6599998F), new Vector2(66.6699982F, 24.6599998F), new Vector2(67.0800018F, 24.6800003F));
                    builder.AddCubicBezier(new Vector2(67.4199982F, 24.6900005F), new Vector2(67.6900024F, 24.9899998F), new Vector2(67.6800003F, 25.3299999F));
                    builder.AddCubicBezier(new Vector2(67.6699982F, 25.6700001F), new Vector2(67.3799973F, 25.9400005F), new Vector2(67.0400009F, 25.9300003F));
                    builder.AddCubicBezier(new Vector2(66.8399963F, 25.9200001F), new Vector2(66.6500015F, 25.9099998F), new Vector2(66.4499969F, 25.9099998F));
                    builder.AddLine(new Vector2(65.8499985F, 25.9099998F));
                    builder.AddCubicBezier(new Vector2(64.75F, 25.9099998F), new Vector2(63.6800003F, 25.9599991F), new Vector2(62.6100006F, 26.0699997F));
                    builder.AddCubicBezier(new Vector2(62.2700005F, 26.1100006F), new Vector2(61.9599991F, 25.8500004F), new Vector2(61.9199982F, 25.5100002F));
                    builder.AddCubicBezier(new Vector2(61.8800011F, 25.1700001F), new Vector2(62.1399994F, 24.8700008F), new Vector2(62.4799995F, 24.8299999F));
                    builder.AddCubicBezier(new Vector2(63.5900002F, 24.7199993F), new Vector2(64.7200012F, 24.6599998F), new Vector2(65.8600006F, 24.6599998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(71.1900024F, 22.6900005F));
                    builder.AddCubicBezier(new Vector2(71.3300018F, 22.3799992F), new Vector2(71.7099991F, 22.2399998F), new Vector2(72.0199966F, 22.3799992F));
                    builder.AddCubicBezier(new Vector2(72.3300018F, 22.5200005F), new Vector2(72.4700012F, 22.8999996F), new Vector2(72.3300018F, 23.2099991F));
                    builder.AddCubicBezier(new Vector2(71.9400024F, 24.0699997F), new Vector2(71.5699997F, 24.9599991F), new Vector2(71.2399979F, 25.8600006F));
                    builder.AddLine(new Vector2(71.0599976F, 26.3299999F));
                    builder.AddLine(new Vector2(70.9599991F, 26.3199997F));
                    builder.AddLine(new Vector2(70.5599976F, 26.2600002F));
                    builder.AddCubicBezier(new Vector2(70.1699982F, 26.2000008F), new Vector2(69.7799988F, 26.1399994F), new Vector2(69.3899994F, 26.1000004F));
                    builder.AddCubicBezier(new Vector2(69.0500031F, 26.0599995F), new Vector2(68.8000031F, 25.75F), new Vector2(68.8399963F, 25.4099998F));
                    builder.AddCubicBezier(new Vector2(68.8799973F, 25.0699997F), new Vector2(69.1900024F, 24.8199997F), new Vector2(69.5299988F, 24.8600006F));
                    builder.AddCubicBezier(new Vector2(69.7699966F, 24.8899994F), new Vector2(70F, 24.9200001F), new Vector2(70.2399979F, 24.9500008F));
                    builder.AddCubicBezier(new Vector2(70.5299988F, 24.1900005F), new Vector2(70.8499985F, 23.4300003F), new Vector2(71.1900024F, 22.6900005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(149.600006F, 25.8799992F));
                    builder.AddCubicBezier(new Vector2(149.75F, 25.6299992F), new Vector2(150.070007F, 25.5100002F), new Vector2(150.350006F, 25.6100006F));
                    builder.AddCubicBezier(new Vector2(152.199997F, 26.25F), new Vector2(153.979996F, 27.0300007F), new Vector2(155.690002F, 27.9200001F));
                    builder.AddCubicBezier(new Vector2(156F, 28.0799999F), new Vector2(156.119995F, 28.4500008F), new Vector2(155.960007F, 28.7600002F));
                    builder.AddCubicBezier(new Vector2(155.800003F, 29.0699997F), new Vector2(155.419998F, 29.1900005F), new Vector2(155.110001F, 29.0300007F));
                    builder.AddCubicBezier(new Vector2(153.660004F, 28.2700005F), new Vector2(152.149994F, 27.6000004F), new Vector2(150.600006F, 27.0300007F));
                    builder.AddLine(new Vector2(149.940002F, 26.7900009F));
                    builder.AddCubicBezier(new Vector2(149.610001F, 26.6800003F), new Vector2(149.440002F, 26.3299999F), new Vector2(149.550003F, 26F));
                    builder.AddLine(new Vector2(149.600006F, 25.8799992F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_12()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(55.8699989F, 26.2099991F));
                    builder.AddCubicBezier(new Vector2(56.2000008F, 26.1000004F), new Vector2(56.5499992F, 26.2900009F), new Vector2(56.6599998F, 26.6200008F));
                    builder.AddCubicBezier(new Vector2(56.7700005F, 26.9500008F), new Vector2(56.5800018F, 27.2900009F), new Vector2(56.25F, 27.3999996F));
                    builder.AddCubicBezier(new Vector2(54.1699982F, 28.0699997F), new Vector2(52.1899986F, 28.9500008F), new Vector2(50.3199997F, 30.0200005F));
                    builder.AddCubicBezier(new Vector2(50.0200005F, 30.1900005F), new Vector2(49.6300011F, 30.0900002F), new Vector2(49.4599991F, 29.7900009F));
                    builder.AddCubicBezier(new Vector2(49.2900009F, 29.4899998F), new Vector2(49.4000015F, 29.1100006F), new Vector2(49.7000008F, 28.9400005F));
                    builder.AddCubicBezier(new Vector2(51.6399994F, 27.8299999F), new Vector2(53.7000008F, 26.9099998F), new Vector2(55.8699989F, 26.2099991F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_13()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(159.770004F, 31.1200008F));
                    builder.AddCubicBezier(new Vector2(159.970001F, 30.8400002F), new Vector2(160.369995F, 30.7800007F), new Vector2(160.649994F, 30.9799995F));
                    builder.AddLine(new Vector2(161.229996F, 31.4099998F));
                    builder.AddCubicBezier(new Vector2(162.589996F, 32.4300003F), new Vector2(163.880005F, 33.5499992F), new Vector2(165.100006F, 34.7299995F));
                    builder.AddCubicBezier(new Vector2(165.350006F, 34.9700012F), new Vector2(165.360001F, 35.3600006F), new Vector2(165.119995F, 35.6100006F));
                    builder.AddCubicBezier(new Vector2(164.880005F, 35.8600006F), new Vector2(164.479996F, 35.8600006F), new Vector2(164.229996F, 35.6199989F));
                    builder.AddCubicBezier(new Vector2(162.880005F, 34.3100014F), new Vector2(161.440002F, 33.0900002F), new Vector2(159.910004F, 31.9899998F));
                    builder.AddCubicBezier(new Vector2(159.630005F, 31.7900009F), new Vector2(159.570007F, 31.3999996F), new Vector2(159.770004F, 31.1200008F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_14()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(44.3199997F, 32.7999992F));
                    builder.AddCubicBezier(new Vector2(44.5699997F, 32.6500015F), new Vector2(44.9000015F, 32.7000008F), new Vector2(45.0999985F, 32.9300003F));
                    builder.AddCubicBezier(new Vector2(45.3300018F, 33.1899986F), new Vector2(45.2999992F, 33.5800018F), new Vector2(45.0400009F, 33.8100014F));
                    builder.AddCubicBezier(new Vector2(43.4199982F, 35.25F), new Vector2(41.9500008F, 36.8600006F), new Vector2(40.6599998F, 38.5999985F));
                    builder.AddCubicBezier(new Vector2(40.4500008F, 38.8800011F), new Vector2(40.0600014F, 38.9399986F), new Vector2(39.7799988F, 38.7299995F));
                    builder.AddCubicBezier(new Vector2(39.5F, 38.5200005F), new Vector2(39.4399986F, 38.1399994F), new Vector2(39.6500015F, 37.8600006F));
                    builder.AddCubicBezier(new Vector2(41F, 36.0499992F), new Vector2(42.5299988F, 34.3800011F), new Vector2(44.2099991F, 32.8800011F));
                    builder.AddLine(new Vector2(44.3199997F, 32.7999992F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_15()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(168.100006F, 38.9599991F));
                    builder.AddCubicBezier(new Vector2(168.339996F, 38.7799988F), new Vector2(168.669998F, 38.7900009F), new Vector2(168.889999F, 38.9799995F));
                    builder.AddLine(new Vector2(168.979996F, 39.0800018F));
                    builder.AddLine(new Vector2(169.410004F, 39.6599998F));
                    builder.AddCubicBezier(new Vector2(170.419998F, 41.0200005F), new Vector2(171.350006F, 42.4500008F), new Vector2(172.179993F, 43.9399986F));
                    builder.AddCubicBezier(new Vector2(172.350006F, 44.2400017F), new Vector2(172.240005F, 44.6199989F), new Vector2(171.940002F, 44.7900009F));
                    builder.AddCubicBezier(new Vector2(171.639999F, 44.9599991F), new Vector2(171.259995F, 44.8499985F), new Vector2(171.089996F, 44.5499992F));
                    builder.AddCubicBezier(new Vector2(170.169998F, 42.9000015F), new Vector2(169.130005F, 41.3300018F), new Vector2(167.990005F, 39.8400002F));
                    builder.AddCubicBezier(new Vector2(167.779999F, 39.5699997F), new Vector2(167.830002F, 39.1699982F), new Vector2(168.100006F, 38.9599991F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_16()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(28.9300003F, 45.5999985F));
                    builder.AddCubicBezier(new Vector2(29.5F, 45.5999985F), new Vector2(30.0799999F, 45.6199989F), new Vector2(30.6399994F, 45.6500015F));
                    builder.AddCubicBezier(new Vector2(30.9799995F, 45.6699982F), new Vector2(31.25F, 45.9700012F), new Vector2(31.2299995F, 46.3100014F));
                    builder.AddCubicBezier(new Vector2(31.2099991F, 46.6500015F), new Vector2(30.9099998F, 46.9199982F), new Vector2(30.5699997F, 46.9000015F));
                    builder.AddCubicBezier(new Vector2(30.0300007F, 46.8699989F), new Vector2(29.4799995F, 46.8499985F), new Vector2(28.9300003F, 46.8499985F));
                    builder.AddCubicBezier(new Vector2(28.0100002F, 46.8499985F), new Vector2(27.1000004F, 46.8899994F), new Vector2(26.2099991F, 46.9799995F));
                    builder.AddCubicBezier(new Vector2(25.8700008F, 47.0099983F), new Vector2(25.5599995F, 46.7599983F), new Vector2(25.5300007F, 46.4199982F));
                    builder.AddCubicBezier(new Vector2(25.5F, 46.0800018F), new Vector2(25.75F, 45.7700005F), new Vector2(26.0900002F, 45.7400017F));
                    builder.AddCubicBezier(new Vector2(27.0200005F, 45.6500015F), new Vector2(27.9699993F, 45.5999985F), new Vector2(28.9300003F, 45.5999985F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_17()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(36.2099991F, 43.6599998F));
                    builder.AddCubicBezier(new Vector2(36.3499985F, 43.3499985F), new Vector2(36.7299995F, 43.2200012F), new Vector2(37.0400009F, 43.3600006F));
                    builder.AddCubicBezier(new Vector2(37.3499985F, 43.5F), new Vector2(37.4900017F, 43.8699989F), new Vector2(37.3499985F, 44.1800003F));
                    builder.AddCubicBezier(new Vector2(36.9000015F, 45.1599998F), new Vector2(36.4900017F, 46.1800003F), new Vector2(36.1399994F, 47.2099991F));
                    builder.AddLine(new Vector2(36F, 47.6399994F));
                    builder.AddLine(new Vector2(35.9599991F, 47.75F));
                    builder.AddLine(new Vector2(35.8499985F, 47.7200012F));
                    builder.AddLine(new Vector2(35.4099998F, 47.6100006F));
                    builder.AddCubicBezier(new Vector2(34.8800011F, 47.4799995F), new Vector2(34.3499985F, 47.3800011F), new Vector2(33.8100014F, 47.2799988F));
                    builder.AddCubicBezier(new Vector2(33.4700012F, 47.2200012F), new Vector2(33.2400017F, 46.8899994F), new Vector2(33.2999992F, 46.5499992F));
                    builder.AddCubicBezier(new Vector2(33.3600006F, 46.2099991F), new Vector2(33.6899986F, 45.9900017F), new Vector2(34.0299988F, 46.0499992F));
                    builder.AddCubicBezier(new Vector2(34.4099998F, 46.1199989F), new Vector2(34.7799988F, 46.1899986F), new Vector2(35.1500015F, 46.2700005F));
                    builder.AddCubicBezier(new Vector2(35.4700012F, 45.3800011F), new Vector2(35.8199997F, 44.5099983F), new Vector2(36.2099991F, 43.6599998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_18()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(20.5300007F, 46.8400002F));
                    builder.AddCubicBezier(new Vector2(20.8600006F, 46.7400017F), new Vector2(21.2000008F, 46.9300003F), new Vector2(21.2999992F, 47.2599983F));
                    builder.AddCubicBezier(new Vector2(21.3999996F, 47.5900002F), new Vector2(21.2199993F, 47.9399986F), new Vector2(20.8899994F, 48.0400009F));
                    builder.AddCubicBezier(new Vector2(19.1399994F, 48.5699997F), new Vector2(17.4699993F, 49.2700005F), new Vector2(15.8800001F, 50.1199989F));
                    builder.AddCubicBezier(new Vector2(15.5799999F, 50.2799988F), new Vector2(15.1899996F, 50.1599998F), new Vector2(15.0299997F, 49.8600006F));
                    builder.AddCubicBezier(new Vector2(14.8699999F, 49.5600014F), new Vector2(14.9799995F, 49.1800003F), new Vector2(15.2799997F, 49.0200005F));
                    builder.AddCubicBezier(new Vector2(16.9400005F, 48.1300011F), new Vector2(18.7000008F, 47.4000015F), new Vector2(20.5300007F, 46.8400002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_19()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(173.839996F, 48.8499985F));
                    builder.AddCubicBezier(new Vector2(174.160004F, 48.7299995F), new Vector2(174.520004F, 48.9000015F), new Vector2(174.639999F, 49.2200012F));
                    builder.AddCubicBezier(new Vector2(175.330002F, 51.0200005F), new Vector2(175.889999F, 52.8899994F), new Vector2(176.309998F, 54.7999992F));
                    builder.AddCubicBezier(new Vector2(176.380005F, 55.1399994F), new Vector2(176.169998F, 55.4700012F), new Vector2(175.830002F, 55.5400009F));
                    builder.AddCubicBezier(new Vector2(175.490005F, 55.6100006F), new Vector2(175.160004F, 55.4099998F), new Vector2(175.089996F, 55.0699997F));
                    builder.AddCubicBezier(new Vector2(174.679993F, 53.2200012F), new Vector2(174.130005F, 51.4000015F), new Vector2(173.470001F, 49.6599998F));
                    builder.AddCubicBezier(new Vector2(173.350006F, 49.3400002F), new Vector2(173.520004F, 48.9700012F), new Vector2(173.839996F, 48.8499985F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_20()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(10.5699997F, 52.1800003F));
                    builder.AddCubicBezier(new Vector2(10.8400002F, 51.9599991F), new Vector2(11.2299995F, 51.9900017F), new Vector2(11.4499998F, 52.2599983F));
                    builder.AddCubicBezier(new Vector2(11.6700001F, 52.5299988F), new Vector2(11.6300001F, 52.9199982F), new Vector2(11.3599997F, 53.1399994F));
                    builder.AddCubicBezier(new Vector2(9.96000004F, 54.2900009F), new Vector2(8.68000031F, 55.5900002F), new Vector2(7.53000021F, 56.9900017F));
                    builder.AddCubicBezier(new Vector2(7.30999994F, 57.2599983F), new Vector2(6.92000008F, 57.2999992F), new Vector2(6.6500001F, 57.0800018F));
                    builder.AddCubicBezier(new Vector2(6.38000011F, 56.8600006F), new Vector2(6.34000015F, 56.4700012F), new Vector2(6.55999994F, 56.2000008F));
                    builder.AddLine(new Vector2(7.01999998F, 55.6500015F));
                    builder.AddCubicBezier(new Vector2(8.10000038F, 54.3899994F), new Vector2(9.28999996F, 53.2299995F), new Vector2(10.5699997F, 52.1800003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_21()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(3.41000009F, 60.9199982F));
                    builder.AddCubicBezier(new Vector2(3.56999993F, 60.6199989F), new Vector2(3.95000005F, 60.5F), new Vector2(4.25F, 60.6599998F));
                    builder.AddCubicBezier(new Vector2(4.55000019F, 60.8199997F), new Vector2(4.67000008F, 61.2000008F), new Vector2(4.51000023F, 61.5F));
                    builder.AddCubicBezier(new Vector2(3.66000009F, 63.0900002F), new Vector2(2.96000004F, 64.7699966F), new Vector2(2.43000007F, 66.5199966F));
                    builder.AddCubicBezier(new Vector2(2.32999992F, 66.8499985F), new Vector2(1.98000002F, 67.0400009F), new Vector2(1.64999998F, 66.9400024F));
                    builder.AddCubicBezier(new Vector2(1.32000005F, 66.8399963F), new Vector2(1.13999999F, 66.4899979F), new Vector2(1.24000001F, 66.1600037F));
                    builder.AddCubicBezier(new Vector2(1.78999996F, 64.3300018F), new Vector2(2.51999998F, 62.5800018F), new Vector2(3.41000009F, 60.9199982F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_22()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(176.479996F, 59.9799995F));
                    builder.AddCubicBezier(new Vector2(176.820007F, 59.9599991F), new Vector2(177.130005F, 60.2200012F), new Vector2(177.149994F, 60.5600014F));
                    builder.AddCubicBezier(new Vector2(177.220001F, 61.5200005F), new Vector2(177.25F, 62.4900017F), new Vector2(177.25F, 63.4700012F));
                    builder.AddCubicBezier(new Vector2(177.25F, 64.5299988F), new Vector2(177.210007F, 65.5800018F), new Vector2(177.130005F, 66.6200027F));
                    builder.AddCubicBezier(new Vector2(177.100006F, 66.9599991F), new Vector2(176.800003F, 67.2200012F), new Vector2(176.460007F, 67.1900024F));
                    builder.AddCubicBezier(new Vector2(176.119995F, 67.1600037F), new Vector2(175.850006F, 66.8600006F), new Vector2(175.880005F, 66.5199966F));
                    builder.AddCubicBezier(new Vector2(175.960007F, 65.5100021F), new Vector2(176F, 64.5F), new Vector2(176F, 63.4700012F));
                    builder.AddCubicBezier(new Vector2(176F, 62.5200005F), new Vector2(175.970001F, 61.5800018F), new Vector2(175.899994F, 60.6500015F));
                    builder.AddCubicBezier(new Vector2(175.880005F, 60.3100014F), new Vector2(176.139999F, 60F), new Vector2(176.479996F, 59.9799995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_23()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0.819999993F, 71.1699982F));
                    builder.AddCubicBezier(new Vector2(1.15999997F, 71.1999969F), new Vector2(1.40999997F, 71.5100021F), new Vector2(1.38F, 71.8499985F));
                    builder.AddCubicBezier(new Vector2(1.28999996F, 72.7399979F), new Vector2(1.25F, 73.6500015F), new Vector2(1.25F, 74.5699997F));
                    builder.AddCubicBezier(new Vector2(1.25F, 75.4899979F), new Vector2(1.28999996F, 76.4000015F), new Vector2(1.38F, 77.2900009F));
                    builder.AddCubicBezier(new Vector2(1.40999997F, 77.6299973F), new Vector2(1.15999997F, 77.9400024F), new Vector2(0.819999993F, 77.9700012F));
                    builder.AddCubicBezier(new Vector2(0.479999989F, 78F), new Vector2(0.170000002F, 77.75F), new Vector2(0.140000001F, 77.4100037F));
                    builder.AddCubicBezier(new Vector2(0.0500000007F, 76.4800034F), new Vector2(0F, 75.5299988F), new Vector2(0F, 74.5699997F));
                    builder.AddCubicBezier(new Vector2(0F, 73.6100006F), new Vector2(0.0500000007F, 72.6600037F), new Vector2(0.140000001F, 71.7300034F));
                    builder.AddCubicBezier(new Vector2(0.170000002F, 71.3899994F), new Vector2(0.479999989F, 71.1399994F), new Vector2(0.819999993F, 71.1699982F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_24()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(175.690002F, 72.0699997F));
                    builder.AddCubicBezier(new Vector2(176.020004F, 72.1500015F), new Vector2(176.240005F, 72.4800034F), new Vector2(176.160004F, 72.8199997F));
                    builder.AddCubicBezier(new Vector2(175.669998F, 74.8799973F), new Vector2(175.009995F, 76.8799973F), new Vector2(174.220001F, 78.8000031F));
                    builder.AddCubicBezier(new Vector2(174.089996F, 79.1200027F), new Vector2(173.720001F, 79.2699966F), new Vector2(173.399994F, 79.1399994F));
                    builder.AddCubicBezier(new Vector2(173.080002F, 79.0100021F), new Vector2(172.929993F, 78.6399994F), new Vector2(173.059998F, 78.3199997F));
                    builder.AddCubicBezier(new Vector2(173.830002F, 76.4599991F), new Vector2(174.460007F, 74.5199966F), new Vector2(174.940002F, 72.5299988F));
                    builder.AddCubicBezier(new Vector2(175.020004F, 72.1900024F), new Vector2(175.350006F, 71.9899979F), new Vector2(175.690002F, 72.0699997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_25()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(1.64999998F, 82.1999969F));
                    builder.AddCubicBezier(new Vector2(1.98000002F, 82.0999985F), new Vector2(2.32999992F, 82.2799988F), new Vector2(2.43000007F, 82.6100006F));
                    builder.AddCubicBezier(new Vector2(2.96000004F, 84.3600006F), new Vector2(3.66000009F, 86.0400009F), new Vector2(4.51000023F, 87.6299973F));
                    builder.AddCubicBezier(new Vector2(4.67000008F, 87.9300003F), new Vector2(4.55000019F, 88.3199997F), new Vector2(4.25F, 88.4800034F));
                    builder.AddCubicBezier(new Vector2(3.95000005F, 88.6399994F), new Vector2(3.56999993F, 88.5199966F), new Vector2(3.41000009F, 88.2200012F));
                    builder.AddCubicBezier(new Vector2(2.51999998F, 86.5599976F), new Vector2(1.78999996F, 84.8099976F), new Vector2(1.24000001F, 82.9800034F));
                    builder.AddCubicBezier(new Vector2(1.13999999F, 82.6500015F), new Vector2(1.32000005F, 82.3000031F), new Vector2(1.64999998F, 82.1999969F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_26()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(170.300003F, 83.7399979F));
                    builder.AddCubicBezier(new Vector2(170.479996F, 83.4499969F), new Vector2(170.869995F, 83.3600006F), new Vector2(171.160004F, 83.5400009F));
                    builder.AddCubicBezier(new Vector2(171.449997F, 83.7200012F), new Vector2(171.550003F, 84.1100006F), new Vector2(171.369995F, 84.4000015F));
                    builder.AddCubicBezier(new Vector2(170.270004F, 86.1900024F), new Vector2(169.029999F, 87.8899994F), new Vector2(167.669998F, 89.4800034F));
                    builder.AddCubicBezier(new Vector2(167.449997F, 89.7399979F), new Vector2(167.050003F, 89.7699966F), new Vector2(166.789993F, 89.5500031F));
                    builder.AddCubicBezier(new Vector2(166.529999F, 89.3300018F), new Vector2(166.5F, 88.9300003F), new Vector2(166.720001F, 88.6699982F));
                    builder.AddCubicBezier(new Vector2(168.029999F, 87.1299973F), new Vector2(169.240005F, 85.4800034F), new Vector2(170.300003F, 83.7399979F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_27()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(6.6500001F, 92.0599976F));
                    builder.AddCubicBezier(new Vector2(6.92000008F, 91.8399963F), new Vector2(7.30999994F, 91.8799973F), new Vector2(7.53000021F, 92.1500015F));
                    builder.AddCubicBezier(new Vector2(8.68000031F, 93.5500031F), new Vector2(9.96000004F, 94.8399963F), new Vector2(11.3599997F, 95.9899979F));
                    builder.AddCubicBezier(new Vector2(11.6300001F, 96.2099991F), new Vector2(11.6700001F, 96.5999985F), new Vector2(11.4499998F, 96.8700027F));
                    builder.AddCubicBezier(new Vector2(11.2299995F, 97.1399994F), new Vector2(10.8400002F, 97.1800003F), new Vector2(10.5699997F, 96.9599991F));
                    builder.AddCubicBezier(new Vector2(9.28999996F, 95.9100037F), new Vector2(8.10000038F, 94.7399979F), new Vector2(7.01999998F, 93.4800034F));
                    builder.AddLine(new Vector2(6.55999994F, 92.9400024F));
                    builder.AddCubicBezier(new Vector2(6.34000015F, 92.6699982F), new Vector2(6.38000011F, 92.2799988F), new Vector2(6.6500001F, 92.0599976F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_28()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(162.419998F, 92.9800034F));
                    builder.AddCubicBezier(new Vector2(162.679993F, 92.7600021F), new Vector2(163.080002F, 92.7900009F), new Vector2(163.300003F, 93.0500031F));
                    builder.AddCubicBezier(new Vector2(163.520004F, 93.3099976F), new Vector2(163.5F, 93.7099991F), new Vector2(163.240005F, 93.9300003F));
                    builder.AddCubicBezier(new Vector2(161.649994F, 95.2900009F), new Vector2(159.949997F, 96.5299988F), new Vector2(158.160004F, 97.6299973F));
                    builder.AddCubicBezier(new Vector2(157.869995F, 97.8099976F), new Vector2(157.479996F, 97.7099991F), new Vector2(157.300003F, 97.4199982F));
                    builder.AddCubicBezier(new Vector2(157.119995F, 97.1299973F), new Vector2(157.210007F, 96.75F), new Vector2(157.5F, 96.5699997F));
                    builder.AddCubicBezier(new Vector2(159.229996F, 95.5F), new Vector2(160.880005F, 94.3000031F), new Vector2(162.419998F, 92.9800034F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_29()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(15.0299997F, 99.2699966F));
                    builder.AddCubicBezier(new Vector2(15.1899996F, 98.9700012F), new Vector2(15.5799999F, 98.8600006F), new Vector2(15.8800001F, 99.0199966F));
                    builder.AddCubicBezier(new Vector2(17.4699993F, 99.8700027F), new Vector2(19.1399994F, 100.57F), new Vector2(20.8899994F, 101.099998F));
                    builder.AddCubicBezier(new Vector2(21.2199993F, 101.199997F), new Vector2(21.4099998F, 101.550003F), new Vector2(21.3099995F, 101.879997F));
                    builder.AddCubicBezier(new Vector2(21.2099991F, 102.209999F), new Vector2(20.8600006F, 102.400002F), new Vector2(20.5300007F, 102.300003F));
                    builder.AddCubicBezier(new Vector2(18.7000008F, 101.739998F), new Vector2(16.9400005F, 101.010002F), new Vector2(15.2799997F, 100.120003F));
                    builder.AddCubicBezier(new Vector2(14.9799995F, 99.9599991F), new Vector2(14.8699999F, 99.5699997F), new Vector2(15.0299997F, 99.2699966F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_30()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(152.089996F, 99.3399963F));
                    builder.AddCubicBezier(new Vector2(152.410004F, 99.2099991F), new Vector2(152.770004F, 99.3499985F), new Vector2(152.899994F, 99.6699982F));
                    builder.AddCubicBezier(new Vector2(153.029999F, 99.9899979F), new Vector2(152.880005F, 100.360001F), new Vector2(152.559998F, 100.489998F));
                    builder.AddCubicBezier(new Vector2(150.639999F, 101.290001F), new Vector2(148.649994F, 101.949997F), new Vector2(146.589996F, 102.440002F));
                    builder.AddCubicBezier(new Vector2(146.25F, 102.519997F), new Vector2(145.919998F, 102.300003F), new Vector2(145.839996F, 101.970001F));
                    builder.AddCubicBezier(new Vector2(145.759995F, 101.629997F), new Vector2(145.960007F, 101.300003F), new Vector2(146.300003F, 101.220001F));
                    builder.AddCubicBezier(new Vector2(148.289993F, 100.739998F), new Vector2(150.229996F, 100.110001F), new Vector2(152.089996F, 99.3399963F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_31()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(140.289993F, 102.169998F));
                    builder.AddCubicBezier(new Vector2(140.630005F, 102.139999F), new Vector2(140.929993F, 102.400002F), new Vector2(140.960007F, 102.739998F));
                    builder.AddLine(new Vector2(140.960007F, 102.870003F));
                    builder.AddCubicBezier(new Vector2(140.919998F, 103.160004F), new Vector2(140.679993F, 103.389999F), new Vector2(140.380005F, 103.410004F));
                    builder.AddCubicBezier(new Vector2(139.550003F, 103.470001F), new Vector2(138.720001F, 103.519997F), new Vector2(137.869995F, 103.529999F));
                    builder.AddLine(new Vector2(137.869995F, 103.540001F));
                    builder.AddLine(new Vector2(134.229996F, 103.540001F));
                    builder.AddCubicBezier(new Vector2(133.889999F, 103.540001F), new Vector2(133.610001F, 103.260002F), new Vector2(133.610001F, 102.919998F));
                    builder.AddCubicBezier(new Vector2(133.610001F, 102.580002F), new Vector2(133.889999F, 102.290001F), new Vector2(134.229996F, 102.290001F));
                    builder.AddLine(new Vector2(136.619995F, 102.290001F));
                    builder.AddLine(new Vector2(137.240005F, 102.290001F));
                    builder.AddCubicBezier(new Vector2(138.270004F, 102.290001F), new Vector2(139.289993F, 102.25F), new Vector2(140.289993F, 102.169998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_32()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(128.220001F, 102.290001F));
                    builder.AddCubicBezier(new Vector2(128.559998F, 102.290001F), new Vector2(128.839996F, 102.580002F), new Vector2(128.839996F, 102.919998F));
                    builder.AddCubicBezier(new Vector2(128.839996F, 103.260002F), new Vector2(128.559998F, 103.540001F), new Vector2(128.220001F, 103.540001F));
                    builder.AddLine(new Vector2(122.199997F, 103.540001F));
                    builder.AddCubicBezier(new Vector2(121.860001F, 103.540001F), new Vector2(121.57F, 103.260002F), new Vector2(121.57F, 102.919998F));
                    builder.AddCubicBezier(new Vector2(121.57F, 102.580002F), new Vector2(121.860001F, 102.290001F), new Vector2(122.199997F, 102.290001F));
                    builder.AddLine(new Vector2(128.220001F, 102.290001F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_33()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(56.0099983F, 102.290001F));
                    builder.AddCubicBezier(new Vector2(56.3499985F, 102.290001F), new Vector2(56.6300011F, 102.580002F), new Vector2(56.6300011F, 102.919998F));
                    builder.AddCubicBezier(new Vector2(56.6300011F, 103.260002F), new Vector2(56.3499985F, 103.540001F), new Vector2(56.0099983F, 103.540001F));
                    builder.AddLine(new Vector2(49.9900017F, 103.540001F));
                    builder.AddCubicBezier(new Vector2(49.6500015F, 103.540001F), new Vector2(49.3699989F, 103.260002F), new Vector2(49.3699989F, 102.919998F));
                    builder.AddCubicBezier(new Vector2(49.3699989F, 102.580002F), new Vector2(49.6500015F, 102.290001F), new Vector2(49.9900017F, 102.290001F));
                    builder.AddLine(new Vector2(56.0099983F, 102.290001F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_34()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(43.9799995F, 102.290001F));
                    builder.AddCubicBezier(new Vector2(44.3199997F, 102.290001F), new Vector2(44.5999985F, 102.580002F), new Vector2(44.5999985F, 102.919998F));
                    builder.AddCubicBezier(new Vector2(44.5999985F, 103.260002F), new Vector2(44.3199997F, 103.540001F), new Vector2(43.9799995F, 103.540001F));
                    builder.AddLine(new Vector2(37.9599991F, 103.540001F));
                    builder.AddCubicBezier(new Vector2(37.6199989F, 103.540001F), new Vector2(37.3300018F, 103.260002F), new Vector2(37.3300018F, 102.919998F));
                    builder.AddCubicBezier(new Vector2(37.3300018F, 102.580002F), new Vector2(37.6199989F, 102.290001F), new Vector2(37.9599991F, 102.290001F));
                    builder.AddLine(new Vector2(43.9799995F, 102.290001F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - ++++++++++++++++++++++++++++++++++
            // - - ++++++++++++++++++++++++++++++++++.PathGeometry
            CanvasGeometry Geometry_35()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(26.2099991F, 102.160004F));
                    builder.AddCubicBezier(new Vector2(27.1000004F, 102.25F), new Vector2(28.0100002F, 102.290001F), new Vector2(28.9300003F, 102.290001F));
                    builder.AddLine(new Vector2(29.5599995F, 102.290001F));
                    builder.AddLine(new Vector2(31.9400005F, 102.290001F));
                    builder.AddCubicBezier(new Vector2(32.2799988F, 102.290001F), new Vector2(32.5699997F, 102.580002F), new Vector2(32.5699997F, 102.919998F));
                    builder.AddCubicBezier(new Vector2(32.5699997F, 103.260002F), new Vector2(32.2799988F, 103.540001F), new Vector2(31.9400005F, 103.540001F));
                    builder.AddLine(new Vector2(28.3099995F, 103.540001F));
                    builder.AddLine(new Vector2(28.3099995F, 103.529999F));
                    builder.AddCubicBezier(new Vector2(27.5699997F, 103.510002F), new Vector2(26.8199997F, 103.470001F), new Vector2(26.0900002F, 103.400002F));
                    builder.AddCubicBezier(new Vector2(25.75F, 103.370003F), new Vector2(25.5F, 103.059998F), new Vector2(25.5300007F, 102.720001F));
                    builder.AddLine(new Vector2(25.5599995F, 102.599998F));
                    builder.AddCubicBezier(new Vector2(25.6499996F, 102.32F), new Vector2(25.9099998F, 102.129997F), new Vector2(26.2099991F, 102.160004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - Transforms: fond
            CanvasGeometry Geometry_36()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(70.75F, 35.375F));
                    builder.AddCubicBezier(new Vector2(70.75F, 54.9099998F), new Vector2(54.9099998F, 70.75F), new Vector2(35.375F, 70.75F));
                    builder.AddCubicBezier(new Vector2(15.8400002F, 70.75F), new Vector2(0F, 54.9099998F), new Vector2(0F, 35.375F));
                    builder.AddCubicBezier(new Vector2(0F, 15.8400002F), new Vector2(15.8400002F, 0F), new Vector2(35.375F, 0F));
                    builder.AddCubicBezier(new Vector2(54.9099998F, 0F), new Vector2(70.75F, 15.8400002F), new Vector2(70.75F, 35.375F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Transforms: Icons/Arrows/arrows-loop
            // - - Transforms: icon Offset:<0, 5>
            // - +.PathGeometry
            CanvasGeometry Geometry_37()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_38(), Geometry_39() },
                    CanvasFilledRegionDetermination.Alternate);
                return result;
            }

            // - - - - Transforms: Icons/Arrows/arrows-loop
            // - - - Transforms: icon Offset:<0, 5>
            // - - +.PathGeometry
            CanvasGeometry Geometry_38()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(32.8699989F, 11.6099997F));
                    builder.AddCubicBezier(new Vector2(33.3600006F, 11.1199999F), new Vector2(34.1399994F, 11.1199999F), new Vector2(34.6300011F, 11.6099997F));
                    builder.AddLine(new Vector2(39.6300011F, 16.6100006F));
                    builder.AddCubicBezier(new Vector2(40.1199989F, 17.1000004F), new Vector2(40.1199989F, 17.8799992F), new Vector2(39.6300011F, 18.3700008F));
                    builder.AddCubicBezier(new Vector2(39.1399994F, 18.8600006F), new Vector2(38.3600006F, 18.8600006F), new Vector2(37.8699989F, 18.3700008F));
                    builder.AddLine(new Vector2(34.9900017F, 15.5F));
                    builder.AddCubicBezier(new Vector2(34.8899994F, 18.3299999F), new Vector2(34F, 21.0699997F), new Vector2(32.4099998F, 23.4099998F));
                    builder.AddCubicBezier(new Vector2(30.7199993F, 25.8899994F), new Vector2(28.3299999F, 27.8199997F), new Vector2(25.5400009F, 28.9300003F));
                    builder.AddCubicBezier(new Vector2(22.75F, 30.0400009F), new Vector2(19.6800003F, 30.2800007F), new Vector2(16.75F, 29.6299992F));
                    builder.AddCubicBezier(new Vector2(13.8199997F, 28.9799995F), new Vector2(11.1499996F, 27.4599991F), new Vector2(9.09000015F, 25.2800007F));
                    builder.AddCubicBezier(new Vector2(8.61999989F, 24.7800007F), new Vector2(8.64000034F, 23.9899998F), new Vector2(9.14000034F, 23.5200005F));
                    builder.AddCubicBezier(new Vector2(9.64000034F, 23.0499992F), new Vector2(10.4399996F, 23.0699997F), new Vector2(10.9099998F, 23.5699997F));
                    builder.AddCubicBezier(new Vector2(12.6300001F, 25.3899994F), new Vector2(14.8599997F, 26.6499996F), new Vector2(17.2999992F, 27.1900005F));
                    builder.AddCubicBezier(new Vector2(19.7399998F, 27.7299995F), new Vector2(22.2900009F, 27.5300007F), new Vector2(24.6200008F, 26.6100006F));
                    builder.AddCubicBezier(new Vector2(26.9500008F, 25.6900005F), new Vector2(28.9300003F, 24.0799999F), new Vector2(30.3400002F, 22.0100002F));
                    builder.AddCubicBezier(new Vector2(31.6499996F, 20.0900002F), new Vector2(32.3899994F, 17.8400002F), new Vector2(32.4900017F, 15.5200005F));
                    builder.AddLine(new Vector2(29.6299992F, 18.3700008F));
                    builder.AddCubicBezier(new Vector2(29.1399994F, 18.8600006F), new Vector2(28.3600006F, 18.8600006F), new Vector2(27.8700008F, 18.3700008F));
                    builder.AddCubicBezier(new Vector2(27.3799992F, 17.8799992F), new Vector2(27.3799992F, 17.1000004F), new Vector2(27.8700008F, 16.6100006F));
                    builder.AddLine(new Vector2(32.8699989F, 11.6099997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Transforms: Icons/Arrows/arrows-loop
            // - - - Transforms: icon Offset:<0, 5>
            // - - +.PathGeometry
            CanvasGeometry Geometry_39()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(14.9300003F, 0.879999995F));
                    builder.AddCubicBezier(new Vector2(17.8400002F, -0.159999996F), new Vector2(20.9899998F, -0.280000001F), new Vector2(23.9699993F, 0.540000021F));
                    builder.AddCubicBezier(new Vector2(26.9500008F, 1.36000001F), new Vector2(29.6000004F, 3.06999993F), new Vector2(31.5699997F, 5.44999981F));
                    builder.AddCubicBezier(new Vector2(32.0099983F, 5.98000002F), new Vector2(31.9300003F, 6.76999998F), new Vector2(31.3999996F, 7.21000004F));
                    builder.AddCubicBezier(new Vector2(30.8700008F, 7.6500001F), new Vector2(30.0799999F, 7.57000017F), new Vector2(29.6399994F, 7.03999996F));
                    builder.AddCubicBezier(new Vector2(28F, 5.05999994F), new Vector2(25.7900009F, 3.63000011F), new Vector2(23.3099995F, 2.95000005F));
                    builder.AddCubicBezier(new Vector2(20.8299999F, 2.26999998F), new Vector2(18.2000008F, 2.36999989F), new Vector2(15.7799997F, 3.24000001F));
                    builder.AddCubicBezier(new Vector2(13.3599997F, 4.11000013F), new Vector2(11.2600002F, 5.69999981F), new Vector2(9.77999973F, 7.80000019F));
                    builder.AddCubicBezier(new Vector2(8.30000019F, 9.89999962F), new Vector2(7.5F, 12.4200001F), new Vector2(7.5F, 14.9899998F));
                    builder.AddLine(new Vector2(7.5F, 15.7200003F));
                    builder.AddLine(new Vector2(10.3699999F, 12.8599997F));
                    builder.AddCubicBezier(new Vector2(10.8599997F, 12.3699999F), new Vector2(11.6400003F, 12.3699999F), new Vector2(12.1300001F, 12.8599997F));
                    builder.AddCubicBezier(new Vector2(12.6199999F, 13.3500004F), new Vector2(12.6199999F, 14.1300001F), new Vector2(12.1300001F, 14.6199999F));
                    builder.AddLine(new Vector2(7.19999981F, 19.5599995F));
                    builder.AddCubicBezier(new Vector2(6.96999979F, 19.8299999F), new Vector2(6.63000011F, 20F), new Vector2(6.25F, 20F));
                    builder.AddCubicBezier(new Vector2(5.86999989F, 20F), new Vector2(5.53000021F, 19.8299999F), new Vector2(5.30000019F, 19.5599995F));
                    builder.AddLine(new Vector2(0.370000005F, 14.6199999F));
                    builder.AddCubicBezier(new Vector2(-0.119999997F, 14.1300001F), new Vector2(-0.119999997F, 13.3500004F), new Vector2(0.370000005F, 12.8599997F));
                    builder.AddCubicBezier(new Vector2(0.860000014F, 12.3699999F), new Vector2(1.63999999F, 12.3699999F), new Vector2(2.13000011F, 12.8599997F));
                    builder.AddLine(new Vector2(5F, 15.7200003F));
                    builder.AddLine(new Vector2(5F, 14.9899998F));
                    builder.AddCubicBezier(new Vector2(5F, 11.8999996F), new Vector2(5.94999981F, 8.89000034F), new Vector2(7.73000002F, 6.36999989F));
                    builder.AddCubicBezier(new Vector2(9.51000023F, 3.8499999F), new Vector2(12.0200005F, 1.91999996F), new Vector2(14.9300003F, 0.879999995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Color bound to theme property value: Color_446EDD
            CompositionColorBrush ThemeColor_Color_446EDD()
            {
                if (_themeColor_Color_446EDD != null) { return _themeColor_Color_446EDD; }
                var result = _themeColor_Color_446EDD = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_446EDD, "Color", "ColorRGB(_theme.Color_446EDD.W,_theme.Color_446EDD.X,_theme.Color_446EDD.Y,_theme.Color_446EDD.Z)", "_theme", _themeProperties);
                return result;
            }

            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(36F, 36F));
                propertySet.InsertVector2("Position", new Vector2(89.0400009F, 87F));
                // Transforms: fond
                result.Shapes.Add(SpriteShape_1());
                BindProperty(_containerShape_0, "CenterPoint", "my.Anchor", "my", _containerShape_0);
                BindProperty(_containerShape_0, "Offset", "my.Position-my.Anchor", "my", _containerShape_0);
                return result;
            }

            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(36F, 36F));
                propertySet.InsertVector2("Position", new Vector2(89.0400009F, 87F));
                // Transforms: Icons/Arrows/arrows-loop
                result.Shapes.Add(ContainerShape_2());
                BindProperty(_containerShape_1, "CenterPoint", "my.Anchor", "my", _containerShape_1);
                BindProperty(_containerShape_1, "Offset", "my.Position-my.Anchor", "my", _containerShape_1);
                return result;
            }

            // Transforms for Icons/Arrows/arrows-loop
            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                // Transforms: icon Offset:<0, 5>
                result.Shapes.Add(SpriteShape_2());
                return result;
            }

            // - Layer aggregator
            // ++++++++++++++++++++++++++++++++++
            // ++++++++++++++++++++++++++++++++++.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
            }

            // Transforms: fond
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_36()));
            }

            // - Transforms: Icons/Arrows/arrows-loop
            // Transforms: icon Offset:<0, 5>
            // +.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_37()));
            }

            // Layer aggregator
            // ++++++++++++++++++++++++++++++++++
            CompositionSpriteShape SpriteShape_0()
            {
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ThemeColor_Color_446EDD();
                return result;
            }

            // Transforms for fond
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry_1());
                result.CenterPoint = new Vector2(36F, 36F);
                result.StrokeBrush = ThemeColor_Color_446EDD();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 1.25F;
                return result;
            }

            // Transforms: Icons/Arrows/arrows-loop
            // +
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<0, 5>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 5F), ThemeColor_Color_446EDD());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_0;
            }

            // Transforms: fond
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 300.
                result.InsertKeyFrame(0.49901861F, -180F, CubicBezierEasingFunction_0());
                // Frame 600.
                result.InsertKeyFrame(0.998037219F, -1F, CubicBezierEasingFunction_0());
                // Frame 601.
                result.InsertKeyFrame(0.999700606F, 0F, HoldThenStepEasingFunction());
                return result;
            }

            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_m360()
            {
                // Frame 0.
                if (_rotationAngleInDegreesScalarAnimation_0_to_m360 != null) { return _rotationAngleInDegreesScalarAnimation_0_to_m360; }
                var result = _rotationAngleInDegreesScalarAnimation_0_to_m360 = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 300.
                result.InsertKeyFrame(0.49901861F, -180F, CubicBezierEasingFunction_0());
                // Frame 600.
                result.InsertKeyFrame(0.998037219F, -359F, CubicBezierEasingFunction_0());
                // Frame 601.
                result.InsertKeyFrame(0.999700606F, -360F, HoldThenStepEasingFunction());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(178F, 131F);
                var shapes = result.Shapes;
                // ++++++++++++++++++++++++++++++++++
                shapes.Add(SpriteShape_0());
                shapes.Add(ContainerShape_0());
                shapes.Add(ContainerShape_1());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // Anchor
            Vector2KeyFrameAnimation AnchorVector2Animation()
            {
                // Frame 0.
                if (_anchorVector2Animation != null) { return _anchorVector2Animation; }
                var result = _anchorVector2Animation = CreateVector2KeyFrameAnimation(0F, new Vector2(36F, 36F), HoldThenStepEasingFunction());
                // Frame 300.
                result.InsertKeyFrame(0.49901861F, new Vector2(36F, 36F), CubicBezierEasingFunction_0());
                // Frame 600.
                result.InsertKeyFrame(0.998037219F, new Vector2(36.6199989F, 36.6199989F), CubicBezierEasingFunction_0());
                // Frame 601.
                result.InsertKeyFrame(0.999700606F, new Vector2(36F, 36F), HoldThenStepEasingFunction());
                return result;
            }

            // - Layer aggregator
            // ++++++++++++++++++++++++++++++++++
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.0399999991F, 0F), HoldThenStepEasingFunction());
                // Frame 300.
                result.InsertKeyFrame(0.49901861F, new Vector2(0.129999995F, 0F), CubicBezierEasingFunction_0());
                // Frame 600.
                result.InsertKeyFrame(0.998037219F, new Vector2(0.0399999991F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // Transforms: fond
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.629999995F, 0.629999995F), HoldThenStepEasingFunction());
                // Frame 300.
                result.InsertKeyFrame(0.49901861F, new Vector2(-0.620000005F, -0.620000005F), CubicBezierEasingFunction_0());
                // Frame 600.
                result.InsertKeyFrame(0.998037219F, new Vector2(1.25999999F, 1.24000001F), CubicBezierEasingFunction_0());
                // Frame 601.
                result.InsertKeyFrame(0.999700606F, new Vector2(0.629999995F, 0.629999995F), HoldThenStepEasingFunction());
                return result;
            }

            // Transforms: Icons/Arrows/arrows-loop
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(16F, 16F), HoldThenStepEasingFunction());
                // Frame 300.
                result.InsertKeyFrame(0.49901861F, new Vector2(16F, 16F), CubicBezierEasingFunction_0());
                // Frame 600.
                result.InsertKeyFrame(0.998037219F, new Vector2(17.2600002F, 17.2299995F), CubicBezierEasingFunction_0());
                // Frame 601.
                result.InsertKeyFrame(0.999700606F, new Vector2(16F, 16F), HoldThenStepEasingFunction());
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation()
            {
                // Frame 0.
                if (_positionVector2Animation != null) { return _positionVector2Animation; }
                var result = _positionVector2Animation = CreateVector2KeyFrameAnimation(0F, new Vector2(89.0400009F, 87F), HoldThenStepEasingFunction());
                // Frame 300.
                result.InsertKeyFrame(0.49901861F, new Vector2(89.1299973F, 87F), CubicBezierEasingFunction_0());
                // Frame 600.
                result.InsertKeyFrame(0.998037219F, new Vector2(88.3799973F, 86.3799973F), CubicBezierEasingFunction_0());
                // Frame 601.
                result.InsertKeyFrame(0.999700606F, new Vector2(89.0400009F, 87F), HoldThenStepEasingFunction());
                return result;
            }

            internal KDrive_Sync_AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(178F, 131F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape_0.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_m360(), AnimationController_0());
                _containerShape_0.Properties.StartAnimation("Anchor", AnchorVector2Animation(), AnimationController_0());
                _containerShape_0.Properties.StartAnimation("Position", PositionVector2Animation(), AnimationController_0());
                _containerShape_1.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_m360(), AnimationController_0());
                _containerShape_1.Properties.StartAnimation("Anchor", AnchorVector2Animation(), AnimationController_0());
                _containerShape_1.Properties.StartAnimation("Position", PositionVector2Animation(), AnimationController_0());
                _containerShape_2.StartAnimation("Offset", OffsetVector2Animation_2(), AnimationController_0());
                _spriteShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _spriteShape_1.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0(), AnimationController_0());
                _spriteShape_1.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape_0.StopAnimation("RotationAngleInDegrees");
                _containerShape_0.Properties.StopAnimation("Anchor");
                _containerShape_0.Properties.StopAnimation("Position");
                _containerShape_1.StopAnimation("RotationAngleInDegrees");
                _containerShape_1.Properties.StopAnimation("Anchor");
                _containerShape_1.Properties.StopAnimation("Position");
                _containerShape_2.StopAnimation("Offset");
                _spriteShape_0.StopAnimation("Offset");
                _spriteShape_1.StopAnimation("RotationAngleInDegrees");
                _spriteShape_1.StopAnimation("Offset");
            }

        }
    }
}
