name: Build macOS
description: 'Build macOS app'

runs:
    using: "composite"
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Clean the log directory
        run : rm -rf /tmp/kDrive-logdir/*
        shell: bash

      - name: Grant building script execute permission
        run : chmod +x ./infomaniak-build-tools/linux/build-ci-amd64.sh
        shell: bash


      - name: Build kDrive desktop
        run : ./infomaniak-build-tools/linux/build-ci-amd64.sh -u
        shell: bash

      - name: Fetch dependencies
        run: |
          mkdir dependencies
        shell: bash

      - name: Upload build common files
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-common-files
          path: |
              cp ${{ github.workspace }}/build-linux/build/bin/sync-exclude.lst ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Widgets.* ./dependencies/ 
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Gui.* ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Network.* ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Sql.* ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Core.* ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6DBus.* ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libicui18n.* ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libicuuc.* ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libicudata.* ./dependencies/
              cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Svg.* ./dependencies/
              cp /usr/local/lib/libcppunit.so ./dependencies/ 
              cp /usr/local/lib/libPocoUtil.so ./dependencies/
              cp /usr/local/lib/libPocoJSON.so ./dependencies/
              cp /usr/local/lib/libPocoXML.so ./dependencies/
              cp /usr/local/lib/libPocoFoundation.so ./dependencies/
              cp /usr/local/lib/libPocoNetSSL.so ./dependencies/
              cp /usr/local/lib/libPocoCrypto.so ./dependencies/
              cp /usr/local/lib/libPocoNet.so ./dependencies/
              cp /usr/local/lib/liblog4cplus.so ./dependencies/
              cp /usr/local/lib/libsentry.so ./dependencies/
              cp /usr/local/lib/libzip.so ./dependencies/
              cp /usr/local/lib/libxxhash* ./dependencies/
          retention-days: 1
        if: always()

      - name: Upload build test common files
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-common-files
          path: ./dependencies/
          retention-days: 1
        if: always()

      - name: Upload build test common executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_common
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_common
          retention-days: 1
        if: always()

      - name: Upload build test common server executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_common_server
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_common_server
          retention-days: 1
        if: always()

      - name: Upload build test server executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_server
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_server
          retention-days: 1
        if: always()

      - name: Upload build test syncengine executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_syncengine
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_syncengine
          retention-days: 1
        if: always()

      - name: Upload build test parms executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_parms
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_parms
          retention-days: 1
        if: always()

      - name: Clean-up generated code
        run : rm -rf build-linux
        shell: bash
