// Infomaniak kDrive - Desktop
// Copyright (C) 2023-2026 Infomaniak Network SA
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
// Generated by lottietoqml. Do not edit geometry or timing manually.
// Palette bindings use IKColors for automatic Light/Dark adaptation.
// Generated from Lottie file WIN_LINUX_kDrive-Check-LIGHT.normalized.json
import QtQuick
import QtQuick.VectorImage
import QtQuick.VectorImage.Helpers
import QtQuick.Shapes
import QtQuick.Effects
import Qt.labs.lottieqt.VectorImageHelpers
import kDrive.UI

Item {
    implicitWidth: 178
    implicitHeight: 131
    component AnimationsInfo : QtObject
    {
        property bool paused: false
        property int loops: 1
        signal restart()
    }
    property AnimationsInfo animations : AnimationsInfo {}
    transform: [
        Scale { xScale: width / 178; yScale: height / 131 }
    ]
    objectName: "_q_animation"
    id: _qt_node0
    transformOrigin: Item.TopLeft
    LayerItem {
        objectName: "folder-03"
        id: _qt_node1
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node1_transform_base_group
            Translate { x: 54.11; y: 0}
            Matrix4x4 { matrix: _qt_node2.transformMatrix }
        }
        Shape {
            preferredRendererType: Shape.CurveRenderer
            id: _qt_node3
            transformOrigin: Item.TopLeft
            ShapePath {
                id: _qt_node3_path_fill_stroke
                strokeColor: "transparent"
                fillColor: IKColors.homeIdleIllustrationStroke
                fillRule: ShapePath.WindingFill
                pathHints: ShapePath.PathQuadratic | ShapePath.PathNonOverlappingControlPointTriangles
                PathSvg { path: "M 8 0.47 L 7.75 1.04 L 8 0.47 M 68.19 96.53 L 68 97.13 L 68.01 97.13 L 68.19 96.53 M 24.59 18.77 L 24 18.96 L 24.1 19.26 L 24.4 19.36 L 24.59 18.77 M 21.19 8.4 L 21.78 8.2 L 21.19 8.4 M 17.95 4.8 L 18.075 4.515 L 18.2 4.23 L 18.075 4.515 L 17.95 4.8 M 8 0.47 L 8.25 -0.1 Q 6.66189 -0.791294 5.1547 -0.641606 Q 3.64752 -0.491919 2.22125 0.49875 Q 0.800625 1.4855 0.0903125 2.86331 Q -0.62 4.24113 -0.62 6.01 L 0 6.01 L 0.63 6.01 Q 0.63 3.11334 2.93375 1.5225 Q 5.22566 -0.0601599 7.75 1.04 L 8 0.47 M 68.19 96.53 L 68.01 97.13 Q 69.6112 97.6362 71.089 97.3928 Q 72.5668 97.1494 73.9212 96.1563 Q 76.63 94.1701 76.63 90.81 L 76 90.81 L 75.38 90.81 Q 75.38 92.1709 74.8294 93.2546 Q 74.2787 94.3384 73.1775 95.145 Q 70.9757 96.7577 68.38 95.94 L 68.19 96.53 M 24.59 18.77 L 25.19 18.57 L 23.485 13.385 L 21.78 8.2 L 21.19 8.4 L 20.59 8.59 L 22.295 13.775 L 24 18.96 L 24.59 18.77 M 21.19 8.4 L 21.78 8.2 Q 20.8546 5.39236 18.2 4.23 L 18.075 4.515 L 17.95 4.8 L 17.7 5.37 Q 19.8387 6.30467 20.59 8.59 L 21.19 8.4 M 17.95 4.8 L 18.075 4.515 L 18.2 4.23 L 8.25 -0.1 L 8 0.47 L 7.75 1.04 L 17.7 5.37 L 17.95 4.8 M 0 15.7 L 0.63 15.7 L 0.63 6.01 L 0 6.01 L -0.62 6.01 L -0.62 15.7 L 0 15.7 M 60.89 94.2 L 60.7 94.79 L 64.35 95.96 L 68 97.13 L 68.19 96.53 L 68.38 95.94 L 64.73 94.77 L 61.08 93.6 L 60.89 94.2 M 45.89 25.6 L 46.08 25.01 L 24.79 18.17 L 24.59 18.77 L 24.4 19.36 L 35.05 22.78 L 45.7 26.2 L 45.89 25.6 M 76 90.81 L 76.63 90.81 L 76.63 71 L 76 71 L 75.38 71 L 75.38 90.81 L 76 90.81 " }
            }
        }
    }
    LayerItem {
        objectName: "folder-02"
        id: _qt_node4
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node4_transform_base_group
            Translate { x: 39.11; y: 12}
            Matrix4x4 { matrix: _qt_node2.transformMatrix }
        }
        Shape {
            preferredRendererType: Shape.CurveRenderer
            id: _qt_node5
            transformOrigin: Item.TopLeft
            ShapePath {
                id: _qt_node5_path_fill_stroke
                strokeColor: "transparent"
                fillColor: IKColors.homeIdleIllustrationStroke
                fillRule: ShapePath.WindingFill
                pathHints: ShapePath.PathQuadratic | ShapePath.PathNonOverlappingControlPointTriangles
                PathSvg { path: "M 8 0.47 L 7.75 1.04 L 8 0.47 M 68.19 96.53 L 68 97.13 L 68.01 97.13 L 68.19 96.53 M 24.59 18.77 L 24 18.96 L 24.05 19.115 L 24.1 19.27 L 24.41 19.36 L 24.59 18.77 M 21.19 8.4 L 21.78 8.2 L 21.19 8.4 M 17.95 4.8 L 18.075 4.515 L 18.2 4.23 L 18.075 4.515 L 17.95 4.8 M 48.2 26.22 L 48.01 26.82 L 48.2 26.22 M 8 0.47 L 8.25 -0.1 Q 6.66189 -0.791294 5.1547 -0.641606 Q 3.64752 -0.491919 2.22125 0.49875 Q 0.800625 1.4855 0.0903125 2.86331 Q -0.62 4.24113 -0.62 6.01 L 0 6.01 L 0.63 6.01 Q 0.63 3.11334 2.93375 1.5225 Q 5.22566 -0.0601599 7.75 1.04 L 8 0.47 M 60.89 94.2 L 60.7 94.79 L 64.35 95.96 L 68 97.13 L 68.19 96.53 L 68.38 95.94 L 64.73 94.77 L 61.08 93.6 L 60.89 94.2 M 68.19 96.53 L 68.01 97.13 Q 69.6112 97.6362 71.089 97.3928 Q 72.5668 97.1494 73.9212 96.1563 Q 76.63 94.1701 76.63 90.81 L 76 90.81 L 75.38 90.81 Q 75.38 92.1709 74.8294 93.2546 Q 74.2787 94.3384 73.1775 95.145 Q 70.9757 96.7577 68.38 95.94 L 68.19 96.53 M 24.59 18.77 L 25.19 18.57 L 23.485 13.385 L 21.78 8.2 L 21.19 8.4 L 20.59 8.59 L 22.295 13.775 L 24 18.96 L 24.59 18.77 M 21.19 8.4 L 21.78 8.2 Q 20.8546 5.39236 18.2 4.23 L 18.075 4.515 L 17.95 4.8 L 17.7 5.37 Q 19.8387 6.30467 20.59 8.59 L 21.19 8.4 M 17.95 4.8 L 18.075 4.515 L 18.2 4.23 L 8.25 -0.1 L 8 0.47 L 7.75 1.04 L 17.7 5.37 L 17.95 4.8 M 0 13.7 L 0.63 13.7 L 0.63 6.01 L 0 6.01 L -0.62 6.01 L -0.62 13.7 L 0 13.7 M 48.2 26.22 L 48.39 25.63 L 24.78 18.17 L 24.59 18.77 L 24.41 19.36 L 48.01 26.82 L 48.2 26.22 M 60 29.95 L 60.19 29.35 L 48.39 25.63 L 48.2 26.22 L 48.01 26.82 L 59.82 30.54 L 60 29.95 M 76 90.81 L 76.63 90.81 L 76.63 54 L 76 54 L 75.38 54 L 75.38 90.81 L 76 90.81 " }
            }
        }
    }
    LayerItem {
        objectName: "page-back"
        id: _qt_node6
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node6_transform_base_group
            Translate { x: 24.03; y: 0}
            Matrix4x4 { matrix: _qt_node7.transformMatrix }
        }
        Shape {
            preferredRendererType: Shape.CurveRenderer
            id: _qt_node8
            transformOrigin: Item.TopLeft
            ShapePath {
                id: _qt_node8_path_fill_stroke
                strokeColor: "transparent"
                fillColor: IKColors.homeIdleIllustrationStroke
                fillRule: ShapePath.WindingFill
                pathHints: ShapePath.PathQuadratic | ShapePath.PathNonOverlappingControlPointTriangles
                PathSvg { path: "M 8 0.47 L 7.75 1.04 L 8 0.47 M 71.81 33.68 L 72 33.08 L 71.81 33.68 M 24.59 18.77 L 24 18.96 L 24.05 19.115 L 24.1 19.27 L 24.41 19.36 L 24.59 18.77 M 21.19 8.4 L 21.78 8.2 L 21.19 8.4 M 17.95 4.8 L 18.075 4.515 L 18.2 4.23 L 18.075 4.515 L 17.95 4.8 M 8 0.47 L 8.25 -0.1 Q 6.66189 -0.791294 5.1547 -0.641606 Q 3.64752 -0.491919 2.22125 0.49875 Q 0.800625 1.4855 0.0903125 2.86331 Q -0.62 4.24113 -0.62 6.01 L 0 6.01 L 0.63 6.01 Q 0.63 3.11334 2.93375 1.5225 Q 5.22566 -0.0601599 7.75 1.04 L 8 0.47 M 76 90.81 L 76.63 90.81 L 76.63 39.4 L 76 39.4 L 75.38 39.4 L 75.38 90.81 L 76 90.81 M 76 39.4 L 76.63 39.4 Q 76.63 37.2312 75.35 35.4825 Q 74.0687 33.7321 72 33.08 L 71.81 33.68 L 71.715 33.975 L 71.62 34.27 Q 73.299 34.8022 74.34 36.2238 Q 75.38 37.6439 75.38 39.4 L 76 39.4 M 71.81 33.68 L 72 33.08 L 24.78 18.17 L 24.59 18.77 L 24.41 19.36 L 48.015 26.815 L 71.62 34.27 L 71.81 33.68 M 24.59 18.77 L 25.19 18.57 L 23.485 13.385 L 21.78 8.2 L 21.19 8.4 L 20.59 8.59 L 22.295 13.775 L 24 18.96 L 24.59 18.77 M 21.19 8.4 L 21.78 8.2 Q 20.8546 5.39236 18.2 4.23 L 18.075 4.515 L 17.95 4.8 L 17.7 5.37 Q 19.8387 6.30467 20.59 8.59 L 21.19 8.4 M 17.95 4.8 L 18.075 4.515 L 18.2 4.23 L 8.25 -0.1 L 8 0.47 L 7.75 1.04 L 17.7 5.37 L 17.95 4.8 M 0 28.5 L 0.63 28.5 L 0.63 6.01 L 0 6.01 L -0.62 6.01 L -0.62 28.5 L 0 28.5 " }
            }
        }
    }
    LayerItem {
        objectName: "page-front"
        id: _qt_node9
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node9_transform_base_group
            Translate { x: 0; y: 21.2}
            Matrix4x4 { matrix: _qt_node7.transformMatrix }
        }
        Shape {
            preferredRendererType: Shape.CurveRenderer
            id: _qt_node10
            transformOrigin: Item.TopLeft
            ShapePath {
                id: _qt_node10_path_fill_stroke
                strokeColor: IKColors.homeIdleIllustrationStroke
                strokeWidth: 1.25
                capStyle: ShapePath.RoundCap
                joinStyle: ShapePath.MiterJoin
                miterLimit: 4
                fillColor: "#00000000"
                fillRule: ShapePath.WindingFill
                pathHints: ShapePath.PathQuadratic | ShapePath.PathNonIntersecting | ShapePath.PathNonOverlappingControlPointTriangles
                PathSvg { path: "M 5.36 12.01 Q 3.78551 8.48615 6.3375 5.59375 Q 8.8888 2.70214 12.58 3.82 L 44.985 13.65 L 77.39 23.48 Q 79.994 24.2644 81.12 26.77 L 90.295 47.22 L 99.47 67.67 Q 101.067 71.2324 98.46 74.135 Q 95.8526 77.0375 92.14 75.83 L 26.54 54.55 Q 23.998 53.734 22.91 51.29 L 14.135 31.65 L 5.36 12.01 " }
            }
        }
    }
    LayerItem {
        objectName: "folder-01"
        id: _qt_node7
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node7_transform_base_group
            Translate { x: 0; y: 22.2}
            Matrix4x4 { matrix: _qt_node2.transformMatrix }
        }
    }
    LayerItem {
        objectName: "drawer"
        id: _qt_node2
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node2_transform_base_group
            TransformGroup {
                id: _qt_node2_transform_group_0
                Translate { x: -65.05; y: -61.7 }
                Translate { id: _qt_node2_transform_0_0 }
            }
        }
        Connections { target: _qt_node0.animations; function onRestart() {_qt_node2_transform_animation.restart() } }
        ParallelAnimation {
            id:_qt_node2_transform_animation
            loops: _qt_node0.animations.loops
            paused: _qt_node0.animations.paused
            running: true
            onLoopsChanged: { if (running) { restart() } }
            SequentialAnimation {
                loops: 1
                ParallelAnimation {
                    SequentialAnimation {
                        ParallelAnimation {
                            ScriptAction {
                                script:_qt_node2_transform_0_0.x = 65.23
                            }
                            ScriptAction {
                                script:_qt_node2_transform_0_0.y = 69.7
                            }
                        }
                        PauseAnimation { duration: 400 }
                        ParallelAnimation {
                            PropertyAnimation {
                                duration: 500
                                target: _qt_node2_transform_0_0
                                property: "x"
                                to: 65.1
                                easing: _qt_node0.easing_00
                            }
                            PropertyAnimation {
                                duration: 500
                                target: _qt_node2_transform_0_0
                                property: "y"
                                to: 69.7
                                easing: _qt_node0.easing_00
                            }
                        }
                        PauseAnimation { duration: 2517 }
                    }
                }
                ScriptAction {
                    script: {
                        _qt_node2_transform_base_group.deactivateOverride(_qt_node2_transform_group_0)
                    }
                }
            }
        }
    }
    LayerItem {
        objectName: "fond"
        id: _qt_node11
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node11_transform_base_group
            Matrix4x4 { matrix: _qt_node12.transformMatrix }
        }
        Shape {
            preferredRendererType: Shape.CurveRenderer
            id: _qt_node13
            transformOrigin: Item.TopLeft
            ShapePath {
                id: _qt_node13_path_fill_stroke
                strokeColor: "transparent"
                fillColor: IKColors.homeIdleBadgeSurface
                fillRule: ShapePath.WindingFill
                pathHints: ShapePath.PathQuadratic | ShapePath.PathNonIntersecting | ShapePath.PathNonOverlappingControlPointTriangles
                PathSvg { path: "M 72 36 Q 72 50.91 61.455 61.455 Q 50.91 72 36 72 Q 21.09 72 10.545 61.455 Q 0 50.91 0 36 Q 0 21.09 10.545 10.545 Q 21.09 0 36 0 Q 50.91 0 61.455 10.545 Q 72 21.09 72 36 " }
            }
        }
    }
    LayerItem {
        objectName: "fond (Stroke)"
        id: _qt_node14
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node14_transform_base_group
            Matrix4x4 { matrix: _qt_node12.transformMatrix }
        }
        Shape {
            preferredRendererType: Shape.CurveRenderer
            id: _qt_node15
            transformOrigin: Item.TopLeft
            ShapePath {
                id: _qt_node15_path_fill
                strokeColor: "transparent"
                fillColor: IKColors.homeIdleBadgeForeground
                fillRule: ShapePath.WindingFill
                pathHints: ShapePath.PathNonIntersecting | ShapePath.PathNonOverlappingControlPointTriangles
                PathSvg { path: "M 70.75 36 Q 70.75 32.4019 70.1138 29.0671 Q 69.4777 25.7323 68.2053 22.6609 Q 66.933 19.5895 65.0245 16.7815 Q 63.1159 13.9734 60.5713 11.4288 Q 55.4819 6.33938 49.3391 3.79469 Q 43.1963 1.25 36 1.25 Q 28.8037 1.25 22.6609 3.79469 Q 16.5181 6.33938 11.4288 11.4288 Q 6.33938 16.5181 3.79469 22.6609 Q 1.25 28.8037 1.25 36 Q 1.25 43.1963 3.79469 49.3391 Q 6.33938 55.4819 11.4288 60.5713 Q 16.5181 65.6606 22.6609 68.2053 Q 28.8037 70.75 36 70.75 Q 43.1963 70.75 49.3391 68.2053 Q 55.4819 65.6606 60.5713 60.5713 Q 63.1159 58.0266 65.0245 55.2185 Q 66.933 52.4105 68.2053 49.3391 Q 69.4777 46.2677 70.1138 42.9329 Q 70.75 39.5981 70.75 36 M 36 72 Q 32.2725 72 28.8178 71.3409 Q 25.3631 70.6819 22.1812 69.3638 Q 18.9994 68.0456 16.0903 66.0684 Q 13.1812 64.0912 10.545 61.455 Q 7.90875 58.8188 5.93156 55.9097 Q 3.95438 53.0006 2.63625 49.8187 Q 1.31813 46.6369 0.659063 43.1822 Q 0 39.7275 0 36 Q 0 32.2725 0.659063 28.8178 Q 1.31813 25.3631 2.63625 22.1812 Q 3.95438 18.9994 5.93156 16.0903 Q 7.90875 13.1812 10.545 10.545 Q 13.1812 7.90875 16.0903 5.93156 Q 18.9994 3.95438 22.1812 2.63625 Q 25.3631 1.31813 28.8178 0.659063 Q 32.2725 0 36 0 Q 39.7275 0 43.1822 0.659063 Q 46.6369 1.31813 49.8188 2.63625 Q 53.0006 3.95438 55.9097 5.93156 Q 58.8188 7.90875 61.455 10.545 Q 66.7275 15.8175 69.3638 22.1812 Q 72 28.545 72 36 Q 72 43.455 69.3638 49.8188 Q 66.7275 56.1825 61.455 61.455 Q 58.8188 64.0912 55.9097 66.0684 Q 53.0006 68.0456 49.8187 69.3638 Q 46.6369 70.6819 43.1822 71.3409 Q 39.7275 72 36 72 M 36 72 L 36 70.75 L 36 72 " }
            }
        }
    }
    LayerItem {
        objectName: "icon"
        id: _qt_node16
        transformOrigin: Item.TopLeft
        opacity: 0
        transform: TransformGroup {
            id: _qt_node16_transform_base_group
            TransformGroup {
                id: _qt_node16_transform_group_0
                Translate { id: _qt_node16_transform_0_3 }
                Translate { id: _qt_node16_transform_0_0 }
            }
            Matrix4x4 { matrix: _qt_node12.transformMatrix }
        }
        Connections { target: _qt_node0.animations; function onRestart() {_qt_node16_transform_animation.restart() } }
        ParallelAnimation {
            id:_qt_node16_transform_animation
            loops: _qt_node0.animations.loops
            paused: _qt_node0.animations.paused
            running: true
            onLoopsChanged: { if (running) { restart() } }
            SequentialAnimation {
                loops: 1
                ParallelAnimation {
                    SequentialAnimation {
                        ParallelAnimation {
                            ScriptAction {
                                script:_qt_node16_transform_0_0.x = 20.77
                            }
                            ScriptAction {
                                script:_qt_node16_transform_0_0.y = 39.37
                            }
                        }
                        ParallelAnimation {
                            PropertyAnimation {
                                duration: 400
                                target: _qt_node16_transform_0_0
                                property: "x"
                                to: 26.04
                                easing: _qt_node0.easing_01
                            }
                            PropertyAnimation {
                                duration: 400
                                target: _qt_node16_transform_0_0
                                property: "y"
                                to: 44.48
                                easing: _qt_node0.easing_01
                            }
                        }
                        ParallelAnimation {
                            PropertyAnimation {
                                duration: 500
                                target: _qt_node16_transform_0_0
                                property: "x"
                                to: 35.92
                                easing: _qt_node0.easing_00
                            }
                            PropertyAnimation {
                                duration: 500
                                target: _qt_node16_transform_0_0
                                property: "y"
                                to: 35.92
                                easing: _qt_node0.easing_00
                            }
                        }
                        PauseAnimation { duration: 2517 }
                    }
                    SequentialAnimation {
                        ParallelAnimation {
                            ScriptAction {
                                script:_qt_node16_transform_0_3.x = -1.41
                            }
                            ScriptAction {
                                script:_qt_node16_transform_0_3.y = -1.35
                            }
                        }
                        ParallelAnimation {
                            PropertyAnimation {
                                duration: 400
                                target: _qt_node16_transform_0_3
                                property: "x"
                                to: -6.67
                                easing: _qt_node0.easing_01
                            }
                            PropertyAnimation {
                                duration: 400
                                target: _qt_node16_transform_0_3
                                property: "y"
                                to: -6.46
                                easing: _qt_node0.easing_01
                            }
                        }
                        ParallelAnimation {
                            PropertyAnimation {
                                duration: 500
                                target: _qt_node16_transform_0_3
                                property: "x"
                                to: -16.56
                                easing: _qt_node0.easing_00
                            }
                            PropertyAnimation {
                                duration: 500
                                target: _qt_node16_transform_0_3
                                property: "y"
                                to: -15.02
                                easing: _qt_node0.easing_00
                            }
                        }
                        PauseAnimation { duration: 2517 }
                    }
                }
                ScriptAction {
                    script: {
                        _qt_node16_transform_base_group.deactivateOverride(_qt_node16_transform_group_0)
                    }
                }
            }
        }
        Connections { target: _qt_node0.animations; function onRestart() {_qt_node16_opacity_animation.restart() } }
        ParallelAnimation {
            id: _qt_node16_opacity_animation
            loops: _qt_node0.animations.loops
            paused: _qt_node0.animations.paused
            running: true
            onLoopsChanged: { if (running) { restart() } }
            SequentialAnimation {
                SequentialAnimation {
                    loops: 1
                    ScriptAction {
                        script:_qt_node16.opacity = 0
                    }
                    PropertyAnimation {
                        duration: 400
                        target: _qt_node16
                        property: "opacity"
                        to: 1
                    }
                    PauseAnimation { duration: 3017 }
                }
            }
        }
        Shape {
            preferredRendererType: Shape.CurveRenderer
            id: _qt_node17
            transformOrigin: Item.TopLeft
            ShapePath {
                id: _qt_node17_path_fill_stroke
                strokeColor: "transparent"
                fillColor: IKColors.homeIdleBadgeForeground
                fillRule: ShapePath.WindingFill
                PathInterpolated {
                    id: _qt_node17_path_fill_stroke_ip
                    svgPaths: [
                        "M 2.51 0.87 C 2.5 0.86 2.51 0.87 2.51 0.87 C 2.5 0.86 2.49 0.84 2.48 0.83 C 2.48 0.83 2.49 0.84 2.48 0.83 C 2.48 0.83 2.59 0.94 2.59 0.94 C 2.68 1.01 2.59 0.94 2.59 0.94 C 2.68 1.01 2.76 1.08 2.8 1.13 C 2.8 1.13 2.82 1.14 2.82 1.14 C 2.82 1.14 2.59 0.94 2.59 0.94 C 2.56 0.92 2.54 0.89 2.51 0.87 C 2.86 1.39 2.73 2.11 2.22 2.48 C 1.69 2.86 0.96 2.76 0.57 2.23 C 0.57 2.23 0.47 2.09 0.47 2.09 C 0.39 1.98 0.29 1.84 0.18 1.67 C 0.17 1.66 0.17 1.66 0.16 1.65 C 0.16 1.65 0.2 1.84 0.2 1.84 C -0.17 1.3 -0.02 0.57 0.52 0.2 C 1.06 -0.16 1.8 -0.02 2.16 0.52 C 2.16 0.52 2.29 0.73 2.29 0.73 C 2.36 0.78 2.44 0.82 2.51 0.87 C 2.51 0.87 2.51 0.87 2.511 0.871 ",
                        "M 12.88 9.25 C 12.36 8.86 11.61 8.96 11.22 9.48 C 11.22 9.48 10.89 9.91 10.89 9.91 C 10.89 9.91 10.88 9.93 10.88 9.93 C 10.73 10.14 10.53 10.29 10.32 10.4 C 10.11 10.51 9.88 10.56 9.65 10.55 C 9.42 10.54 9.19 10.48 8.98 10.36 C 8.77 10.24 8.6 10.07 8.46 9.85 C 8.46 9.85 8.44 9.83 8.44 9.83 C 8.44 9.83 2.16 0.52 2.16 0.52 C 1.8 -0.02 1.06 -0.16 0.52 0.2 C -0.02 0.57 -0.17 1.3 0.2 1.84 C 0.2 1.84 6.48 11.15 6.48 11.15 C 6.82 11.67 7.27 12.1 7.8 12.41 C 8.34 12.72 8.96 12.89 9.58 12.91 C 10.2 12.93 10.82 12.8 11.38 12.52 C 11.93 12.24 12.4 11.84 12.77 11.34 C 12.77 11.34 12.78 11.34 12.78 11.34 C 12.78 11.34 13.11 10.91 13.11 10.91 C 13.5 10.39 13.4 9.64 12.88 9.25 C 12.88 9.25 12.88 9.25 12.881 9.251 ",
                        "M 32.64 0.24 C 32.12 -0.15 31.38 -0.05 30.99 0.47 C 30.99 0.47 10.89 27.03 10.89 27.03 C 10.89 27.03 10.88 27.05 10.88 27.05 C 10.73 27.26 10.53 27.41 10.32 27.52 C 10.11 27.63 9.88 27.68 9.65 27.67 C 9.42 27.66 9.19 27.6 8.98 27.48 C 8.77 27.36 8.6 27.19 8.46 26.97 C 8.46 26.97 8.44 26.94 8.44 26.94 C 8.44 26.94 2.16 17.64 2.16 17.64 C 1.8 17.1 1.06 16.96 0.52 17.32 C -0.02 17.69 -0.17 18.42 0.2 18.96 C 0.2 18.96 6.48 28.26 6.48 28.26 C 6.82 28.78 7.27 29.21 7.8 29.52 C 8.34 29.83 8.96 30.01 9.58 30.03 C 10.2 30.05 10.82 29.92 11.38 29.64 C 11.93 29.36 12.4 28.95 12.77 28.45 C 12.77 28.45 12.78 28.46 12.78 28.46 C 12.78 28.46 32.88 1.9 32.88 1.9 C 33.27 1.38 33.16 0.63 32.64 0.24 C 32.64 0.24 32.64 0.24 32.641 0.241 "
                    ]
                }
            }
            Connections { target: _qt_node0.animations; function onRestart() {_qt_node17_path_fill_stroke_ip_factor_animation.restart() } }
            ParallelAnimation {
                id: _qt_node17_path_fill_stroke_ip_factor_animation
                loops: _qt_node0.animations.loops
                paused: _qt_node0.animations.paused
                running: true
                onLoopsChanged: { if (running) { restart() } }
                SequentialAnimation {
                    SequentialAnimation {
                        loops: 1
                        ScriptAction {
                            script:_qt_node17_path_fill_stroke_ip.factor = 0
                        }
                        PropertyAnimation {
                            duration: 400
                            target: _qt_node17_path_fill_stroke_ip
                            property: "factor"
                            to: 1
                            easing: _qt_node0.easing_01
                        }
                        PropertyAnimation {
                            duration: 500
                            target: _qt_node17_path_fill_stroke_ip
                            property: "factor"
                            to: 2
                            easing: _qt_node0.easing_00
                        }
                        PauseAnimation { duration: 2517 }
                    }
                }
            }
        }
    }
    LayerItem {
        objectName: "icon"
        id: _qt_node12
        transformOrigin: Item.TopLeft
        transform: TransformGroup {
            id: _qt_node12_transform_base_group
            TransformGroup {
                id: _qt_node12_transform_group_0
                Translate { x: -36; y: -36 }
                Translate { id: _qt_node12_transform_0_0 }
            }
        }
        Connections { target: _qt_node0.animations; function onRestart() {_qt_node12_transform_animation.restart() } }
        ParallelAnimation {
            id:_qt_node12_transform_animation
            loops: _qt_node0.animations.loops
            paused: _qt_node0.animations.paused
            running: true
            onLoopsChanged: { if (running) { restart() } }
            SequentialAnimation {
                loops: 1
                ParallelAnimation {
                    SequentialAnimation {
                        ParallelAnimation {
                            ScriptAction {
                                script:_qt_node12_transform_0_0.x = 134.04
                            }
                            ScriptAction {
                                script:_qt_node12_transform_0_0.y = 44
                            }
                        }
                        ParallelAnimation {
                            PropertyAnimation {
                                duration: 400
                                target: _qt_node12_transform_0_0
                                property: "x"
                                to: 133.91
                                easing: _qt_node0.easing_01
                            }
                            PropertyAnimation {
                                duration: 400
                                target: _qt_node12_transform_0_0
                                property: "y"
                                to: 44
                                easing: _qt_node0.easing_01
                            }
                        }
                        ParallelAnimation {
                            PropertyAnimation {
                                duration: 500
                                target: _qt_node12_transform_0_0
                                property: "x"
                                to: 133.96
                                easing: _qt_node0.easing_00
                            }
                            PropertyAnimation {
                                duration: 500
                                target: _qt_node12_transform_0_0
                                property: "y"
                                to: 44
                                easing: _qt_node0.easing_00
                            }
                        }
                        PauseAnimation { duration: 2517 }
                    }
                }
                ScriptAction {
                    script: {
                        _qt_node12_transform_base_group.deactivateOverride(_qt_node12_transform_group_0)
                    }
                }
            }
        }
    }
    readonly property easingCurve easing_01: ({ type: Easing.BezierSpline, bezierCurve: [ 0.32, 0, 0.67, 0, 1, 1 ] })
    readonly property easingCurve easing_00: ({ type: Easing.BezierSpline, bezierCurve: [ 0.33, 1, 0.68, 1, 1, 1 ] })
}
