name: Build AMD64 Linux
description: 'Build AMD64 Version of the Linux app'

inputs:
  release_build:
    description: 'If true, run the release build script'
    required: false
    default: 'false'

runs:
    using: "composite"
    steps:
      - name: Clean the log directory
        run : rm -rf /tmp/kDrive-logdir/*
        shell: bash

      - name: Run the build script
        id: build
        run: |
          if [[ "${{ inputs.release_build }}" == "true" ]]; then
            SCRIPT="${{ github.workspace }}/infomaniak-build-tools/linux/build-release-amd64.sh"
            ARGS="-u"
          else
            SCRIPT="${{ github.workspace }}/infomaniak-build-tools/linux/build-ci-amd64.sh"
            ARGS="-u -t release"
          fi
          
          /usr/bin/env bash "$SCRIPT" $ARGS
        shell: bash

      - name: Upload app AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-artifacts-appimage-amd64
          path: ${{ github.workspace }}/build-linux/install/kDrive-*-amd64.AppImage # kDrive-<full_version>-amd64.AppImage
          retention-days: 1
        if: steps.build.outcome == 'success' && ${{ inputs.release_build == 'true' }}

      - name: Download sentry-cli for Linux
        if: ${{ steps.build.outcome == 'success' &&  inputs.release_build == 'true' }}
        run: |
          curl -L https://github.com/getsentry/sentry-cli/releases/download/2.46.0/sentry-cli-Linux-x86_64 -o sentry-cli \
          && chmod +x ./sentry-cli
        shell: bash

      - name: Create sentry server artifacts
        if: ${{ steps.build.outcome == 'success' &&  inputs.release_build == 'true' }}
        run: |
          DBG_FILE="${{ github.workspace }}/build-linux/kDrive.dbg"
          ./sentry-cli debug-files bundle-sources "$DBG_FILE"
          mkdir "${{ github.workspace }}/build-linux/sentry-server-artifacts"
          mv "${{ github.workspace }}/build-linux/kDrive.src.zip" "${{ github.workspace }}/build-linux/sentry-server-artifacts"
          mv "$DBG_FILE" "${{ github.workspace }}/build-linux/sentry-server-artifacts"
        shell: bash

      - name: Create sentry client artifacts
        if: ${{ steps.build.outcome == 'success' &&  inputs.release_build == 'true' }}
        run: |
          DBG_FILE="${{ github.workspace }}/build-linux/kDrive_client.dbg"
          ./sentry-cli debug-files bundle-sources "$DBG_FILE"
          mkdir "${{ github.workspace }}/build-linux/sentry-client-artifacts"
          mv "${{ github.workspace }}/build-linux/kDrive_client.src.zip" "${{ github.workspace }}/build-linux/sentry-client-artifacts"
          mv "$DBG_FILE" "${{ github.workspace }}/build-linux/sentry-client-artifacts"
        shell: bash

      - name: Upload sentry server artifacts
        if: ${{ steps.build.outcome == 'success' &&  inputs.release_build == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-artifacts-server-debug-amd64
          path: ${{ github.workspace }}/build-linux/sentry-server-artifacts
          retention-days: 1
          compression-level: 0

      - name: Upload sentry client artifacts
        if: ${{ steps.build.outcome == 'success' &&  inputs.release_build == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-artifacts-client-debug-amd64
          path: ${{ github.workspace }}/build-linux/sentry-client-artifacts
          retention-days: 1
          compression-level: 0

      - name: Fetch dependencies
        run: | 
          mkdir dependencies
          cp ${{ github.workspace }}/build-linux/build/bin/sync-exclude.lst ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Widgets.* ./dependencies/ 
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Gui.* ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Network.* ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Sql.* ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Core.* ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6DBus.* ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libicui18n.* ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libicuuc.* ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libicudata.* ./dependencies/
          cp /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Svg.* ./dependencies/
          mkdir dependencies/platforms
          cp /home/runner/Qt/6.2.3/gcc_64/plugins/platforms/libqoffscreen.so ./dependencies/platforms/
          cp /usr/local/lib/libcppunit-1.15.so.2 ./dependencies/ 
          cp /usr/local/lib/libPocoUtil* ./dependencies/
          cp /usr/local/lib/libPocoJSON* ./dependencies/
          cp /usr/local/lib/libPocoXML* ./dependencies/
          cp /usr/local/lib/libPocoFoundation* ./dependencies/
          cp /usr/local/lib/libPocoNetSSL* ./dependencies/
          cp /usr/local/lib/libPocoCrypto* ./dependencies/
          cp /usr/local/lib/libPocoNet* ./dependencies/
          cp /usr/local/lib/libsentry* ./dependencies/
          cp /usr/local/lib/libzip* ./dependencies/
          cp /usr/lib/x86_64-linux-gnu/libglib* ./dependencies/
          cp /usr/lib/x86_64-linux-gnu/libsecret* ./dependencies/
          cp /usr/lib/x86_64-linux-gnu/libgthread* ./dependencies/
          cp /usr/lib/x86_64-linux-gnu/libdbus-1.so.3 ./dependencies/
        shell: bash
        if: steps.build.outcome == 'success'

      - name: Fetch Conan dependencies
        run: |
          echo "Sourcing conanrun.sh to get LD_LIBRARY_PATH..."
          source $(find "${{ github.workspace }}/build-linux" -name conanrun.sh | head -n 1)
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
          IFS=':' read -ra dirs <<< "$LD_LIBRARY_PATH"
          for dir in "${dirs[@]}"; do
            if [[ "$dir" == *".conan2/p"* ]]; then
              echo "Looking in $dir"
              find "$dir" \
                \( -iname 'libxxhash*.so*' \
                -o -iname 'liblog4cplus*.so.*' \
                -o -iname 'libssl*.so*' \
                -o -iname 'libcrypto*.so*' \) \
                -exec cp {} ./dependencies/ \; \
                -exec echo "Conan dependency found -> " {} \;
            fi
          done
        shell: bash
        if: steps.build.outcome == 'success'

      - name: Upload build common files
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-common-files
          path: ./dependencies/
          retention-days: 1
          compression-level: 0
        if: steps.build.outcome == 'success'

      - name: Upload build test common executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_common
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_common
          retention-days: 1
          compression-level: 0
        if: steps.build.outcome == 'success'

      - name: Upload build test common server executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_common_server
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_common_server
          retention-days: 1
          compression-level: 0
        if: steps.build.outcome == 'success'

      - name: Upload build test server executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_server
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_server
          retention-days: 1
          compression-level: 0
        if: steps.build.outcome == 'success'

      - name: Upload build test syncengine executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_syncengine
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_syncengine
          retention-days: 1
          compression-level: 0
        if: steps.build.outcome == 'success'

      - name: Upload build test parms executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-kDrive_test_parms
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_parms
          retention-days: 1
          compression-level: 0
        if: steps.build.outcome == 'success'

      - name: Clean-up generated code
        run : rm -rf build-linux
        shell: bash
