/*
 * Infomaniak kDrive - Desktop
 * Copyright (C) 2023-2024 Infomaniak Network SA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#define COMM_SHORT_TIMEOUT 1000
#define COMM_AVERAGE_TIMEOUT 10000
#define COMM_LONG_TIMEOUT 60000

#define MSG_TYPE "type"

#define MSG_REQUEST_ID "id"
#define MSG_REQUEST_NUM "num"
#define MSG_REQUEST_PARAMS "params"

#define MSG_REPLY_ID "id"
#define MSG_REPLY_RESULT "result"

#define MSG_SIGNAL_ID "id"
#define MSG_SIGNAL_NUM "num"
#define MSG_SIGNAL_PARAMS "params"

#define EXECUTE_ERROR_MSG "C/S function call timeout or error!"

typedef enum { REQUEST = 0, REPLY, SIGNAL } MsgType;

enum class RequestNum {
    LOGIN_REQUESTTOKEN = 1,
    USER_DBIDLIST,
    USER_INFOLIST,
    USER_DELETE,
    USER_AVAILABLEDRIVES,
    USER_ID_FROM_USERDBID,
    ACCOUNT_INFOLIST,
    DRIVE_INFOLIST,
    DRIVE_INFO,
    DRIVE_ID_FROM_DRIVEDBID,
    DRIVE_ID_FROM_SYNCDBID,
    DRIVE_DEFAULTCOLOR,
    DRIVE_UPDATE,
    DRIVE_DELETE,
    SYNC_INFOLIST,
    SYNC_START,
    SYNC_STOP,
    SYNC_STATUS,
    SYNC_ISRUNNING,
    SYNC_ADD,
    SYNC_ADD2,
    SYNC_START_AFTER_LOGIN,
    SYNC_DELETE,
    SYNC_GETPUBLICLINKURL,
    SYNC_GETPRIVATELINKURL,
    SYNC_ASKFORSTATUS,
    SYNC_SETSUPPORTSVIRTUALFILES,
    SYNC_SETROOTPINSTATE,
    SYNC_PROPAGATE_SYNCLIST_CHANGE,
    SYNCNODE_LIST,
    SYNCNODE_SETLIST,
    NODE_PATH,
    NODE_INFO,
    NODE_SUBFOLDERS,
    NODE_SUBFOLDERS2,
    NODE_FOLDER_SIZE,
    NODE_CREATEMISSINGFOLDERS,
    ERROR_INFOLIST,
    ERROR_GET_CONFLICTS,
    ERROR_DELETE_SERVER,
    ERROR_DELETE_SYNC,
    ERROR_DELETE_INVALIDTOKEN,
    ERROR_RESOLVE_CONFLICTS,
    ERROR_RESOLVE_UNSUPPORTED_CHAR,
    EXCLTEMPL_GETEXCLUDED,
    EXCLTEMPL_GETLIST,
    EXCLTEMPL_SETLIST,
    EXCLTEMPL_PROPAGATE_CHANGE,
#ifdef __APPLE__
    EXCLAPP_GETLIST,
    EXCLAPP_SETLIST,
    GET_FETCHING_APP_LIST,
#endif
    PARAMETERS_INFO,
    PARAMETERS_UPDATE,
    UTILITY_FINDGOODPATHFORNEWSYNC,
    UTILITY_BESTVFSAVAILABLEMODE,
#ifdef WIN32
    UTILITY_SHOWSHORTCUT,
    UTILITY_SETSHOWSHORTCUT,
#endif
    UTILITY_ACTIVATELOADINFO,
    UTILITY_CHECKCOMMSTATUS,
    UTILITY_HASSYSTEMLAUNCHONSTARTUP,
    UTILITY_HASLAUNCHONSTARTUP,
    UTILITY_SETLAUNCHONSTARTUP,
    UTILITY_SET_APPSTATE,
    UTILITY_GET_APPSTATE,
    UTILITY_SEND_LOG_TO_SUPPORT,
    UTILITY_CANCEL_LOG_TO_SUPPORT,
    UTILITY_GET_LOG_ESTIMATED_SIZE,
    UPDATER_VERSION,
    UPDATER_ISKDCUPDATER,
    UPDATER_ISSPARKLEUPDATER,
    UPDATER_STATUSSTRING,
    UPDATER_STATUS,
    UPDATER_DOWNLOADCOMPLETED,
    UPDATER_UPDATEFOUND,
    UPDATER_STARTINSTALLER,
    UPDATER_UPDATE_DIALOG_RESULT,
    RECONSIDER_SKIPPED_UPDATE,
    UTILITY_QUIT,
};

enum class SignalNum{
    // User
    USER_ADDED = 0,
    USER_UPDATED,
    USER_STATUSCHANGED,
    USER_REMOVED,
    // Account
    ACCOUNT_ADDED,
    ACCOUNT_UPDATED,
    ACCOUNT_REMOVED,
    // Drive
    DRIVE_ADDED,
    DRIVE_UPDATED,
    DRIVE_QUOTAUPDATED,
    DRIVE_REMOVED,
    DRIVE_DELETE_FAILED,
    // Sync
    SYNC_ADDED,
    SYNC_UPDATED,
    SYNC_REMOVED,
    SYNC_PROGRESSINFO,
    SYNC_COMPLETEDITEM,
    SYNC_VFS_CONVERSION_COMPLETED,
    SYNC_DELETE_FAILED,
    // Node
    NODE_FOLDER_SIZE_COMPLETED,
    NODE_FIX_CONFLICTED_FILES_COMPLETED,
    // Updater
    UPDATER_SHOW_DIALOG,
    // Utility
    UTILITY_SHOW_NOTIFICATION,
    UTILITY_NEW_BIG_FOLDER,
    UTILITY_ERROR_ADDED,
    UTILITY_ERRORS_CLEARED,
    UTILITY_SHOW_SETTINGS,
    UTILITY_SHOW_SYNTHESIS,
    UTILITY_LOG_UPLOAD_STATUS_UPDATED,
};
