name: Get the kDrive version of the current commit
description: 'Get the kDrive version of the current commit'

outputs:
  kDrive_version:
    description: 'The kDrive version of the current commit'
    value: ${{ steps.get-version-step.outputs.kDrive_version }}

runs:
  using: "composite"
  steps:
    - name: Get version from version.json
      id: get-version-step
      shell: bash
      run: |
        source "${{ github.workspace }}/infomaniak-build-tools/version-helpers.sh"
        VERSION=$(GetVersionFromJson "${{ github.workspace }}" true)

        echo "Detected version: $VERSION"
        echo "kDrive_version=$VERSION" >> "$GITHUB_OUTPUT"