name: Update branch marked auto merge

on:
  # Runs every 15 minutes
  schedule:
    - cron: '*/15 7-19 * * 1-5'

concurrency:
  group: auto-update
  cancel-in-progress: true

jobs:
  update-branch:
    if: ${{ (github.event.pull_request.auto_merge) && (github.event.pull_request.mergeable) }}
    runs-on: [ macOS ]
    steps:
      - uses: lcdsmao/update-branch@v3
        with:
          requiredApprovals: 1