name: Update branch marked auto merge

on:
    # Runs every 15 minutes
    schedule:
        - cron: '*/15 * * * *'

concurrency:
  group: auto-update
  cancel-in-progress: true

jobs:
  update-branch:
    if: ${{ github.event.pull_request.auto_merge }}
    runs-on: [ self-hosted, macOS, desktop-kdrive ]
    steps:
      - uses: lcdsmao/update-branch@v3
        with:
          requiredApprovals: 1