name: Convert PR to Draft on Non-Approval Review

on:
  pull_request_review:
    types: [submitted]

jobs:
  convert-to-draft:
    if: github.event.review.state != 'approved'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Convert PR to draft
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              draft: true
            });
