name: Dependent Issues

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
  pull_request_target:
    types:
      - opened
      - edited
      - closed
      - reopened
      # Makes sure we always add status check for PRs. Useful only if
      # this action is required to pass before merging. Otherwise, it
      # can be removed.
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: depends-on/depends-on-action@0.15.0
        with:
          token: ${{ github.token }}
