name: kDrive desktop CI

on:
  workflow_dispatch:  
  pull_request:
    branches-ignore:
        - 'release/**'
    types: [synchronize, review_requested, opened]

concurrency:
  group: kDrive-desktop-ci-${{ github.head_ref }}
  cancel-in-progress: true

env:
  KDRIVE_TEST_CI_API_TOKEN: ${{ secrets.KDRIVE_TOKEN }}
  KDRIVE_TEST_CI_ACCOUNT_ID: ${{ vars.KDRIVE_TEST_CI_ACCOUNT_ID }}
  KDRIVE_TEST_CI_USER_ID: ${{ vars.KDRIVE_TEST_CI_USER_ID }}
  KDRIVE_TEST_CI_DRIVE_ID: ${{ vars.KDRIVE_TEST_CI_DRIVE_ID }}
  KDRIVE_TEST_CI_REMOTE_DIR_ID: ${{ vars.KDRIVE_TEST_CI_REMOTE_DIR_ID }}
  KDRIVE_TEST_CI_LOCAL_PATH: ${{ vars.KDRIVE_TEST_CI_LOCAL_PATH }}
  KDRIVE_TEST_CI_REMOTE_PATH: ${{ vars.KDRIVE_TEST_CI_REMOTE_PATH }}
  KDRIVE_TEST_CI_RUNNING_ON_CI: true


jobs:

# Build apps
  build-Windows:
    runs-on: [ self-hosted, Windows, desktop-kdrive ]
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Windows
        uses: ./.github/actions/build_windows
        with:  
          virtual_cert_id: ${{ secrets.WINDOWS_VIRTUAL_CERT }}
          virtual_cert_pass: ${{ secrets.WINDOWS_VIRTUAL_CERT_PASSWORD }}
    
  build-Linux:
    if: false
    runs-on: [ self-hosted, Linux, X64, desktop-kdrive ]

    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Clean the log directory
        run : rm -rf /tmp/kDrive-logdir/*

      - name: Grant building script execute permission
        run : chmod +x ./infomaniak-build-tools/linux/build-ci-amd64.sh
      - name: Build kDrive desktop
        run : ./infomaniak-build-tools/linux/build-ci-amd64.sh -u
      
      - name: Upload build common files
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-common-files
          path: ${{ github.workspace }}/build-linux/build/bin/sync-exclude.lst
          retention-days: 1
        if: always()

      - name: Upload build qt libs
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-qt-libs
          path: |
              /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Widgets.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Gui.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Network.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Sql.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Core.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libQt6DBus.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libicui18n.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libicuuc.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libicudata.*
              /home/runner/Qt/6.2.3/gcc_64/lib/libQt6Svg.*
          retention-days: 1
        if: always()

      - name: Upload build usr lib
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-usr-lib
          path: |
              /usr/local/lib/libcppunit.so
              /usr/local/lib/libPocoUtil.so
              /usr/local/lib/libPocoJSON.so
              /usr/local/lib/libPocoXML.so
              /usr/local/lib/libPocoFoundation.so
              /usr/local/lib/libPocoNetSSL.so
              /usr/local/lib/libPocoCrypto.so
              /usr/local/lib/libPocoNet.so
              /usr/local/lib/liblog4cplus.so
              /usr/local/lib/libsentry.so
              /usr/local/lib/libzip.so
              /usr/local/lib/libxxhash*
          retention-days: 1
        if: always()

      - name: Upload build test common executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-test-common
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_common
          retention-days: 1
        if: always()

      - name: Upload build test common server executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-test-common-server
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_common_server
          retention-days: 1
        if: always()

      - name: Upload build test server executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-test-server
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_server
          retention-days: 1
        if: always()

      - name: Upload build test syncengine executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-test-syncengine
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_syncengine
          retention-days: 1
        if: always()

      - name: Upload build test parms executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-test-parms
          path: ${{ github.workspace }}/build-linux/build/bin/kDrive_test_parms
          retention-days: 1
        if: always()

      - name: Clean-up generated code
        run : rm -rf build-linux

  build-MacOS:
    runs-on: [ self-hosted, macOS, desktop-kdrive ]
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build macOS
        uses: ./.github/actions/build_macos
        with:  
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
    

  Tests:
    needs: build-Windows
    strategy:
      matrix:
        os: [Windows ,macOS]
    uses: ./.github/workflows/run-tests.yml
    with: 
      test_dependencies_version: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}
      test_common_name: kDrive_test_common
      test_common_server_name: kDrive_test_common_server
      test_server_name: kDrive_test_server
      test_syncengine_name: kDrive_test_syncengine
      test_parms_name: kDrive_test_parms
    secrets: inherit


# Tests Linux
  test-common-Linux:
    runs-on: [ self-hosted, Linux, X64]
    env:
      KDRIVE_TEST_CI_8MO_PARTITION_PATH: ${{ vars.KDRIVE_TEST_CI_8MO_PARTITION_PATH_LINUX }}
    needs: build-Linux
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Download common files
        uses: actions/download-artifact@v4
        with:
          name: linux-build-common-files
          path: ${{ github.workspace }}/build-linux/test/

      - name: Load cached dependencies
        id: cache
        uses: herve-er/local-cache@v2
        with:
          path: build-linux/cache
          base: ${{ github.workspace }}/../local-cache
          key: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}
          clean-key: true        

      - name: Download usr libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-usr-lib
          path: ${{ github.workspace }}/build-linux/cache/

      - name: Download QT libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-qt-libs
          path: ${{ github.workspace }}/build-linux/cache/
          
      - name: Copy the cache to the test directory
        run: cp -r ${{ github.workspace }}/build-linux/cache/* ${{ github.workspace }}/build-linux/test/
        
      - name: Download test executable
        uses: actions/download-artifact@v4
        with:
          name: linux-build-test-common
          path: ${{ github.workspace }}/build-linux/test/

      - name: Grant tests script execute permission
        run : chmod +x ./infomaniak-build-tools/run-test.sh
      - name: Execute tests
        run : |
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/build-linux/test/
            ./infomaniak-build-tools/run-test.sh ./build-linux/test/ kDrive_test_common

      - name: Upload tests logs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-tests-logs-tests-common
          path: /tmp/kDrive-logdir/*
          retention-days: 1
        if: always()

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Clean up
        run : rm -rf ${{ github.workspace }}/build-linux/test/*

  test-commonServer-Linux:
    runs-on: [ self-hosted, Linux, X64 ]
    env:
      KDRIVE_TEST_CI_8MO_PARTITION_PATH: ${{ vars.KDRIVE_TEST_CI_8MO_PARTITION_PATH_LINUX }}
    needs: build-Linux
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Download common files
        uses: actions/download-artifact@v4
        with:
          name: linux-build-common-files
          path: ${{ github.workspace }}/build-linux/test/

      - name: Load cached dependencies
        id: cache
        uses: herve-er/local-cache@v2
        with:
          path: build-linux/cache
          base: ${{ github.workspace }}/../local-cache
          key: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}
          clean-key: true        

      - name: Download usr libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-usr-lib
          path: ${{ github.workspace }}/build-linux/cache/

      - name: Download QT libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-qt-libs
          path: ${{ github.workspace }}/build-linux/cache/
          
      - name: Copy the cache to the test directory
        run: cp -r ${{ github.workspace }}/build-linux/cache/* ${{ github.workspace }}/build-linux/test/

      - name: Download test executable
        uses: actions/download-artifact@v4
        with:
          name: linux-build-test-common-server
          path: ${{ github.workspace }}/build-linux/test/

      - name: Grant tests script execute permission
        run : chmod +x ./infomaniak-build-tools/run-test.sh
      - name: Execute tests
        run : |
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/build-linux/test/
            ./infomaniak-build-tools/run-test.sh ./build-linux/test/ kDrive_test_common_server

      - name: Upload tests logs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-tests-logs-tests-common-server
          path: /tmp/kDrive-logdir/*
          retention-days: 1
        if: always()

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Clean up
        run : rm -rf ${{ github.workspace }}/build-linux/test/*

  test-server-Linux:
    runs-on: [ self-hosted, Linux, X64 ]
    env:
      KDRIVE_TEST_CI_8MO_PARTITION_PATH: ${{ vars.KDRIVE_TEST_CI_8MO_PARTITION_PATH_LINUX }}
    needs: build-Linux
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Download common files
        uses: actions/download-artifact@v4
        with:
          name: linux-build-common-files
          path: ${{ github.workspace }}/build-linux/test/

      - name: Load cached dependencies
        id: cache
        uses: herve-er/local-cache@v2
        with:
          path: build-linux/cache
          base: ${{ github.workspace }}/../local-cache
          key: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}
          clean-key: true        

      - name: Download usr libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-usr-lib
          path: ${{ github.workspace }}/build-linux/cache/

      - name: Download QT libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-qt-libs
          path: ${{ github.workspace }}/build-linux/cache/
          
      - name: Copy the cache to the test directory
        run: cp -r ${{ github.workspace }}/build-linux/cache/* ${{ github.workspace }}/build-linux/test/

      - name: Download test executable
        uses: actions/download-artifact@v4
        with:
          name: linux-build-test-server
          path: ${{ github.workspace }}/build-linux/test/

      - name: Grant tests script execute permission
        run : chmod +x ./infomaniak-build-tools/run-test.sh
      - name: Execute tests
        run : |
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/build-linux/test/
            ./infomaniak-build-tools/run-test.sh ./build-linux/test/ kDrive_test_server

      - name: Upload tests logs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-tests-logs-tests-server
          path: /tmp/kDrive-logdir/*
          retention-days: 1
        if: always()

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Clean up
        run : rm -rf ${{ github.workspace }}/build-linux/test/*

  test-syncengine-Linux:
    runs-on: [ self-hosted, Linux, X64 ]
    env:
      KDRIVE_TEST_CI_8MO_PARTITION_PATH: ${{ vars.KDRIVE_TEST_CI_8MO_PARTITION_PATH_LINUX }}
    needs: build-Linux
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Download common files
        uses: actions/download-artifact@v4
        with:
          name: linux-build-common-files
          path: ${{ github.workspace }}/build-linux/test/

      - name: Load cached dependencies
        id: cache
        uses: herve-er/local-cache@v2
        with:
          path: build-linux/cache
          base: ${{ github.workspace }}/../local-cache
          key: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}
          clean-key: true        

      - name: Download usr libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-usr-lib
          path: ${{ github.workspace }}/build-linux/cache/

      - name: Download QT libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-qt-libs
          path: ${{ github.workspace }}/build-linux/cache/
          
      - name: Copy the cache to the test directory
        run: cp -r ${{ github.workspace }}/build-linux/cache/* ${{ github.workspace }}/build-linux/test/

      - name: Download test executable
        uses: actions/download-artifact@v4
        with:
          name: linux-build-test-syncengine
          path: ${{ github.workspace }}/build-linux/test/

      - name: Grant tests script execute permission
        run : chmod +x ./infomaniak-build-tools/run-test.sh
      - name: Execute tests
        run : |
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/build-linux/test/
            ./infomaniak-build-tools/run-test.sh ./build-linux/test/ kDrive_test_syncengine

      - name: Upload tests logs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-tests-logs-tests-syncengine
          path: /tmp/kDrive-logdir/*
          retention-days: 1
        if: always()

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Clean up
        run : rm -rf ${{ github.workspace }}/build-linux/test/*

  test-parms-Linux:
    runs-on: [ self-hosted, Linux, X64 ]
    env:
      KDRIVE_TEST_CI_8MO_PARTITION_PATH: ${{ vars.KDRIVE_TEST_CI_8MO_PARTITION_PATH_LINUX }}
    needs: build-Linux
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

      - name: Download common files
        uses: actions/download-artifact@v4
        with:
          name: linux-build-common-files
          path: ${{ github.workspace }}/build-linux/test/

      - name: Load cached dependencies
        id: cache
        uses: herve-er/local-cache@v2
        with:
          path: build-linux/cache
          base: ${{ github.workspace }}/../local-cache
          key: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}
          clean-key: true        

      - name: Download usr libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-usr-lib
          path: ${{ github.workspace }}/build-linux/cache/

      - name: Download QT libs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: linux-build-qt-libs
          path: ${{ github.workspace }}/build-linux/cache/
          
      - name: Copy the cache to the test directory
        run: cp -r ${{ github.workspace }}/build-linux/cache/* ${{ github.workspace }}/build-linux/test/

      - name: Download test executable
        uses: actions/download-artifact@v4
        with:
          name: linux-build-test-parms
          path: ${{ github.workspace }}/build-linux/test/

      - name: Grant tests script execute permission
        run : chmod +x ./infomaniak-build-tools/run-test.sh
      - name: Execute tests
        run : |
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/build-linux/test/
            ./infomaniak-build-tools/run-test.sh ./build-linux/test/ kDrive_test_parms

      - name: Upload tests logs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-tests-logs-tests-parms
          path: /tmp/kDrive-logdir/*
          retention-days: 1
        if: always()

      - name: Clean up log directory
        if: always()
        run : rm -rf /tmp/kDrive-logdir/* || true

# Tests macOS
#  Test-macOS:
#    needs: build-MacOS
#    uses: ./.github/workflows/run-test-mac.yml
#    with: 
#      test_dependencies_version: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}
#      test_common_artifact_name: mac-kDrive_test_common
#      test_common_exe_name: kDrive_test_common
#      test_common_server_artifact_name: mac-kDrive_test_common_server
#      test_common_server_exe_name: kDrive_test_common_server
#      test_server_artifact_name: mac-kDrive_test_server
#      test_server_exe_name: kDrive_test_server
#      test_syncengine_artifact_name: mac-kDrive_test_syncengine
#      test_syncengine_exe_name: kDrive_test_syncengine
#      test_parms_artifact_name: mac-kDrive_test_parms
#      test_parms_exe_name: kDrive_test_parms
#    secrets: inherit
