name: Build kDrive-desktop MSI package

on:
  workflow_dispatch:  
    inputs:
      environment:
        type: environment
        description: Select the deployment environment
        default: Internal beta

concurrency:
  group: kDrive-desktop-release-${{ github.head_ref }}
  cancel-in-progress: true

env:
  KDRIVE_TEST_CI_API_TOKEN: ${{ secrets.KDRIVE_TOKEN }}
  KDRIVE_TEST_CI_ACCOUNT_ID: ${{ vars.KDRIVE_TEST_CI_ACCOUNT_ID }}
  KDRIVE_TEST_CI_USER_ID: ${{ vars.KDRIVE_TEST_CI_USER_ID }}
  KDRIVE_TEST_CI_DRIVE_ID: ${{ vars.KDRIVE_TEST_CI_DRIVE_ID }}
  KDRIVE_TEST_CI_REMOTE_DIR_ID: ${{ vars.KDRIVE_TEST_CI_REMOTE_DIR_ID }}
  KDRIVE_TEST_CI_LOCAL_PATH: ${{ vars.KDRIVE_TEST_CI_LOCAL_PATH }}
  KDRIVE_TEST_CI_REMOTE_PATH: ${{ vars.KDRIVE_TEST_CI_REMOTE_PATH }}
  KDRIVE_TEST_CI_RUNNING_ON_CI: true
  QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
  QT_QPA_PLATFORM: offscreen

jobs:
# Build apps and MSI
  build-Windows:
    runs-on: [ self-hosted, Windows, desktop-kdrive-with-gui ] #with-gui is required for the build_windows action to unlock the release signing certificate
    outputs:
      kDrive_version: ${{ steps.build-windows-step.outputs.kDrive_version }}
    env:
      KDC_PHYSICAL_AUMID: ${{ secrets.KDC_PHYSICAL_AUMID }}
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Windows
        id: build-windows-step
        uses: ./.github/actions/build_windows
        with:  
          physical_cert: ${{ secrets.WINDOWS_PHYSICAL_CERT }}
          physical_cert_pass: ${{ secrets.WINDOWS_PHYSICAL_CERT_PASSWORD }}
          release_build: true
