name: Release kDrive Desktop Beta (internal)

on:
  workflow_dispatch:  
  pull_request:
    branches-ignore:
        - 'release/**'
    types: [synchronize, opened]

concurrency:
  group: kDrive-desktop-release-${{ github.head_ref }}
  cancel-in-progress: true

env:
  KDRIVE_TEST_CI_API_TOKEN: ${{ secrets.KDRIVE_TOKEN }}
  KDRIVE_TEST_CI_ACCOUNT_ID: ${{ vars.KDRIVE_TEST_CI_ACCOUNT_ID }}
  KDRIVE_TEST_CI_USER_ID: ${{ vars.KDRIVE_TEST_CI_USER_ID }}
  KDRIVE_TEST_CI_DRIVE_ID: ${{ vars.KDRIVE_TEST_CI_DRIVE_ID }}
  KDRIVE_TEST_CI_REMOTE_DIR_ID: ${{ vars.KDRIVE_TEST_CI_REMOTE_DIR_ID }}
  KDRIVE_TEST_CI_LOCAL_PATH: ${{ vars.KDRIVE_TEST_CI_LOCAL_PATH }}
  KDRIVE_TEST_CI_REMOTE_PATH: ${{ vars.KDRIVE_TEST_CI_REMOTE_PATH }}
  KDRIVE_TEST_CI_RUNNING_ON_CI: true
  QT_QPA_PLATFORM: offscreen

jobs:

# Check translation files
  check-translations:
    runs-on: [self-hosted]
    steps:
      - name: Check translations
        run: echo "TODO Check translations..."

# Check Release Notes
  check-release-notes:
    runs-on: [self-hosted]
    steps:
      - name: Check release notes
        run: echo "TODO Check release notes..."

# Build apps
  build-Windows:
    needs: [check-release-notes, check-translations]
    runs-on: [ self-hosted, Windows, desktop-kdrive ]
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Windows
        uses: ./.github/actions/build_windows
        with:  
          virtual_cert_id: ${{ secrets.WINDOWS_VIRTUAL_CERT }}
          virtual_cert_pass: ${{ secrets.WINDOWS_VIRTUAL_CERT_PASSWORD }}
          release_build: true
    

  build-Linux:
    needs: check-release-notes
    if: false
    runs-on: [ self-hosted, Linux, X64, desktop-kdrive ]
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Linux
        uses: ./.github/actions/build_linux

  build-MacOS:
    needs: check-release-notes
    if: false
    runs-on: [ self-hosted, macOS, desktop-kdrive ]
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build macOS
        uses: ./.github/actions/build_macos
        with:  
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
    

# Tests Windows
  Test-Windows:
    if: false
    needs: build-Windows
    strategy:
      fail-fast: false
      matrix:
        test_name: ["kDrive_test_common", "kDrive_test_common_server", "kDrive_test_server", "kDrive_test_syncengine", "kDrive_test_parms"]
    runs-on: [ self-hosted, Windows ]
    env:
      KDRIVE_TEST_CI_LOCAL_PATH: "${{ github.workspace }}/test/test_ci"
      KDRIVE_SENTRY_ENVIRONMENT: "windows_ci_runner"
    steps:
       - name: Checkout the PR
         uses: actions/checkout@v4.1.1
         with:
          ref: ${{ github.head_ref }}

       - name: Run test
         uses: ./.github/actions/test_windows
         with:  
            test_name: ${{ matrix.test_name }}
            test_dependencies_version: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}

# Tests Linux
  Test-Linux:
    needs: build-Linux
    strategy:
      fail-fast: false
      matrix:
        test_name: ["kDrive_test_common", "kDrive_test_common_server", "kDrive_test_server", "kDrive_test_syncengine", "kDrive_test_parms"]
    runs-on: [ self-hosted,  Linux, X64  ]
    env:
      KDRIVE_TEST_CI_LOCAL_PATH: "${{ github.workspace }}/test/test_ci"
      KDRIVE_SENTRY_ENVIRONMENT: "linux_ci_runner"
    steps:
       - name: Checkout the PR
         uses: actions/checkout@v4.1.1
         with:
          ref: ${{ github.head_ref }}

       - name: Run test
         uses: ./.github/actions/test_linux
         with:  
            test_name: ${{ matrix.test_name }}
            test_dependencies_version: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}

# Tests macOS
  Test-macOS:
    needs: build-MacOS
    strategy:
      fail-fast: false
      matrix:
        test_name: ["kDrive_test_common", "kDrive_test_common_server", "kDrive_test_server", "kDrive_test_syncengine", "kDrive_test_parms"]
    runs-on: [ self-hosted, macOS ]
    env:
      KDRIVE_TEST_CI_LOCAL_PATH: "${{ github.workspace }}/test/test_ci"
      KDRIVE_SENTRY_ENVIRONMENT: "macos_ci_runner"
    steps:
       - name: Checkout the PR
         uses: actions/checkout@v4.1.1
         with:
          ref: ${{ github.head_ref }}

       - name: Run test
         uses: ./.github/actions/test_macos
         with:  
            test_name: ${{ matrix.test_name }}
            test_dependencies_version: ${{ vars.KDRIVE_TEST_DEPENDENCIES_VERSION }}

# Upload the installer to kDrive
  upload-intaller-to-kDrive:
    needs: [Test-Windows]
    runs-on: [self-hosted]
    env:
        KDRIVE_TOKEN: ${{ secrets.KDRIVE_TOKEN }}
        KDRIVE_ID: ${{ secrets.KDRIVE_ID }}
        KDRIVE_DIR_ID: ${{ secrets.KDRIVE_DIR_ID }}
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-windows
          name: win-release-artifacts-*
          merge-multiple: true

      - name: Upload debug files and installers/appimage to kDrive
        run: powershell ./infomaniak-build-tools/windows/upload-ci.ps1

 
# Upload the artifacts to sentry
  upload-artifacts-to-sentry:
    needs: [Test-Windows]
    runs-on: [self-hosted]
    steps:
      - name: Upload artifacts to Sentry
        run: echo "TODO Upload the artifacts to sentry..."

# Upload to the storage server
  upload-app-to-storage-server:
    needs: [upload-intaller-to-kDrive, upload-artifacts-to-sentry]
    runs-on: [self-hosted]
    steps:
      - name: Upload app to storage server
        run: echo "TODO Upload the app to the storage server..."

# Update kStore
  update-kStore:
    needs: upload-app-to-storage-server
    runs-on: [self-hosted]
    steps:
      - name: Update kStore
        run: echo "TODO Update kStore..."
