name: Package kDrive desktop on all platforms

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to use'
        required: true
        default: 'main'
        type: choice
        options:
        - main
        - develop
        - RELEASE-*
        - KDESKTOP-834-CI-workflows-for-nightly-builds # Remove after testing
  push:
    branches:
      - 'RELEASE-**'
      - 'KDESKTOP-834-CI-workflows-for-nightly-builds' # Remove after testing

concurrency:
  group: packaging
  cancel-in-progress: true

env:
  KDRIVE_TOKEN: ${{ secrets.KDRIVE_TOKEN }}
  KDRIVE_ID: ${{ secrets.KDRIVE_ID }}
  KDRIVE_DIR_ID: ${{ secrets.KDRIVE_DIR_ID }}

jobs:
  package-Linux:
    runs-on: [ self-hosted, Linux, X64, desktop-kdrive ]
    env:
      BRANCH_NAME: ${{ github.ref_name || inputs.BRANCH }} 
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ env.BRANCH_NAME }}
          submodules: recursive

      - name: Grant building script execute permission
        run : chmod +x ./infomaniak-build-tools/linux/build-ci-amd64.sh
      - name: Build kDrive desktop
        run : ./infomaniak-build-tools/linux/build-ci-amd64.sh

      - name: Grant packaging script execute permission
        run : chmod +x ./infomaniak-build-tools/linux/package-ci-amd64.sh
      - name: Build kDrive desktop
        run : ./infomaniak-build-tools/linux/package-ci-amd64.sh

  package-MacOS:
    runs-on: [ self-hosted, macOS, desktop-kdrive ]
    env:
      BRANCH_NAME: ${{ github.ref_name || inputs.BRANCH }} 
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ env.BRANCH_NAME }}
          submodules: recursive

      - name: Unlock keychain to use the certificate
        run : security unlock-keychain -p '${{ secrets.KEYCHAIN_PASSWORD }}' login.keychain

      - name: Build and package kDrive desktop
        run : ./infomaniak-build-tools/macos/build-drive.sh
