name: Run windows tests

on:
  workflow_call:
    inputs:
      test_dependencies_version:
        required: true
        type: string
      test_common_artifact_name:
        required: true
        type: string
      test_common_exe_name:
        required: true
        type: string

jobs:
  test-common-Windows:
    runs-on: [ self-hosted, Windows ]
    env:
      KDRIVE_TEST_CI_8MO_PARTITION_PATH: ${{ vars.KDRIVE_TEST_CI_8MO_PARTITION_PATH_WIN }}
    steps:
        - uses: actions/checkout@v4
        - name: Build Windows
          uses: ./.github/actions/run_test_windows
          with:  
            artifact_name: ${{ inputs.test_common_artifact_name }}
            exe_name: ${{ inputs.test_common_exe_name }}
            test_dependencies_version: ${{ inputs.test_dependencies_version }}