name: Run Linux tests

on:
  workflow_call:
    inputs:
      test_dependencies_version:
        required: true
        type: string
      test_common_name:
        required: true
        type: string
      test_common_server_name:
        required: true
        type: string
      test_server_name:
        required: true
        type: string
      test_syncengine_name:
        required: true
        type: string
      test_parms_name:
        required: true
        type: string

env:
  KDRIVE_TEST_CI_API_TOKEN: ${{ secrets.KDRIVE_TOKEN }}
  KDRIVE_TEST_CI_ACCOUNT_ID: ${{ vars.KDRIVE_TEST_CI_ACCOUNT_ID }}
  KDRIVE_TEST_CI_USER_ID: ${{ vars.KDRIVE_TEST_CI_USER_ID }}
  KDRIVE_TEST_CI_DRIVE_ID: ${{ vars.KDRIVE_TEST_CI_DRIVE_ID }}
  KDRIVE_TEST_CI_REMOTE_DIR_ID: ${{ vars.KDRIVE_TEST_CI_REMOTE_DIR_ID }}
  KDRIVE_TEST_CI_LOCAL_PATH: ${{ vars.KDRIVE_TEST_CI_LOCAL_PATH }}
  KDRIVE_TEST_CI_REMOTE_PATH: ${{ vars.KDRIVE_TEST_CI_REMOTE_PATH }}
  KDRIVE_TEST_CI_8MO_PARTITION_PATH: ${{ vars.KDRIVE_TEST_CI_8MO_PARTITION_PATH_LINUX }}
  KDRIVE_TEST_CI_RUNNING_ON_CI: true
  QT_QPA_PLATFORM: offscreen

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        test_name: ["${{ inputs.test_common_name }}", "${{ inputs.test_common_server_name }}", "${{ inputs.test_server_name }}", "${{ inputs.test_syncengine_name }}", "${{ inputs.test_parms_name }}"]
    runs-on: [ self-hosted, Linux, X64 ]
    env:
      KDRIVE_TEST_CI_LOCAL_PATH: "${{ github.workspace }}/test/test_ci"
    steps:
       - name: Checkout the PR
         uses: actions/checkout@v4.1.1
         with:
          ref: ${{ github.head_ref }}
          submodules: recursive

       - name: Run test
         uses: ./.github/actions/run_test_linux
         with:  
            test_name: ${{ matrix.test_name }}
            test_dependencies_version: ${{ inputs.test_dependencies_version }}