name: Run windows tests

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      test_dependencies_version:
        required: true
        type: string
      test_common_name:
        required: true
        type: string
      test_common_server_name:
        required: true
        type: string
      test_server_name:
        required: true
        type: string
      test_syncengine_name:
        required: true
        type: string
      test_parms_name:
        required: true
        type: string

env:
  KDRIVE_TEST_CI_API_TOKEN: ${{ secrets.KDRIVE_TOKEN }}
  KDRIVE_TEST_CI_ACCOUNT_ID: ${{ vars.KDRIVE_TEST_CI_ACCOUNT_ID }}
  KDRIVE_TEST_CI_USER_ID: ${{ vars.KDRIVE_TEST_CI_USER_ID }}
  KDRIVE_TEST_CI_DRIVE_ID: ${{ vars.KDRIVE_TEST_CI_DRIVE_ID }}
  KDRIVE_TEST_CI_REMOTE_DIR_ID: ${{ vars.KDRIVE_TEST_CI_REMOTE_DIR_ID }}
  KDRIVE_TEST_CI_LOCAL_PATH: ${{ vars.KDRIVE_TEST_CI_LOCAL_PATH }}
  KDRIVE_TEST_CI_REMOTE_PATH: ${{ vars.KDRIVE_TEST_CI_REMOTE_PATH }}
  KDRIVE_TEST_CI_RUNNING_ON_CI: true

jobs:
  Common:
    runs-on:
      - self-hosted
      - ${{ inputs.runs-on }}   
    steps:
        - uses: actions/checkout@v4
        - name: Run test
          uses: ./.github/actions/run_test_${{ inputs.runs-on }}   
          with:  
            test_name: ${{ inputs.test_common_name }}
            test_dependencies_version: ${{ inputs.test_dependencies_version }}
  CommonServer:
    runs-on:
      - self-hosted
      - ${{ inputs.runs-on }}   
    steps:
        - uses: actions/checkout@v4
        - name: Run test
          uses: ./.github/actions/run_test_${{ inputs.runs-on }}   
          with:  
            test_name: ${{ inputs.test_common_server_name }}
            test_dependencies_version: ${{ inputs.test_dependencies_version }}
  Server:
    runs-on:
      - self-hosted
      - ${{ inputs.runs-on }}   
    steps:
        - uses: actions/checkout@v4
        - name: Run test
          uses: ./.github/actions/run_test_${{ inputs.runs-on }}   
          with:  
            test_name: ${{ inputs.test_server_name }}
            test_dependencies_version: ${{ inputs.test_dependencies_version }}
  Syncengine:
    runs-on:
      - self-hosted
      - ${{ inputs.runs-on }}   
    steps:
        - uses: actions/checkout@v4
        - name: Run test
          uses: ./.github/actions/run_test_${{ inputs.runs-on }}   
          with:  
            test_name: ${{ inputs.test_syncengine_name }}
            test_dependencies_version: ${{ inputs.test_dependencies_version }}
  Parms:
    runs-on:
      - self-hosted
      - ${{ inputs.runs-on }}   
    steps:
        - uses: actions/checkout@v4
        - name: Run test
          uses: ./.github/actions/run_test_${{ inputs.runs-on }}   
          with:  
            test_name: ${{ inputs.test_parms_name }}
            test_dependencies_version: ${{ inputs.test_dependencies_version }}